= gdisk

[NOTE]
====
本文译自 man gdisk
====

== 名称

gdisk - 交互式 GUID 分区表（GPT）操纵器

== 语法

**gdisk** [ -l ] [.underline]#device#

== 描述

GPT fdisk（也即 **gdisk**）是一个文字模式下的、菜单驱动的、用来创建和修改分区表的程序。它会自动将一个旧样式的主引导记录（MBR）分区表或存储了不含 MBR 承载分区的 BSD 磁盘标签转换为更新的全局唯一标识符（GUID）分区表（GPT）格式，或载入一个 GUID 分区表。当与 `-l` 命令行参数连用时，该程序会显示当前的分区表并退出。

GPT fdisk 操作主要作用于 GPT 头和分区表；但是，当需要时，它可以也会生成一个新的保护性 MBR。（任何在保护性 MBR 中的启动载入器均不会被扰乱。）若你已经创建了一个不平常的保护性 MBR，比如由 **gptsync** 或 **gdisk** 自己的 hybrid MBR 特性创建的 hybrid MBR，那么它就不应该被大多数常规操作扰乱。一些高级的数据恢复操作要求你明白主数据和备份数据之间的区别，以及 GPT 头和分区表之间的差异。要了解 MBR 和 GPT 之间的比较，以及 GPT 术语和结构，参阅扩展 **gdisk** 文档 link:http://www.rodsbooks.com/gdisk[] 或参阅维基百科。

**gdisk** 程序使用了一个与 Linux 的 **fdisk** 相似的用户界面，但 **gdisk** 修改 GPT 分区。它也有能力将 MBR 分区或 BSD 磁盘标签转换为 GPT 分区。与原始的 **fdisk** 程序类似，直到你明确要求写入修改之前，**gdisk** 都不会修改磁盘结构，因此如果你犯了一个错误，那么你可以用 ‘q’ 选项退出程序，且不会对你的分区做任何修改。

通常情况下，**gdisk** 操作于磁盘设备文件，比如 Linux 下的 [.underline]#/dev/sda# 或 [.underline]#/dev/hda#，Mac OS X 下的 [.underline]#/dev/disk0#，或 FreeBSD 下的 [.underline]#/dev/ad0# 或 [.underline]#/dev/da0#。该程序也可以操作于磁盘镜像文件，它们可以是整个磁盘的拷贝（比如由 **dd** 生成）或由 QEMU 或 VMWARE 等模拟器使用的 raw disk image。注意仅支持 [.underline]#raw# 磁盘镜像；**gdisk** 不可作用于压缩或其它高级磁盘镜像格式。

MBR 分区系统使用 磁柱/磁头/扇区（CHS）寻址和逻辑块寻址（LBA）的组合。前者又旧又局限。GPT 弃用了 CHS 寻址，并排他地使用 64 bit LBA 模式。因此，GPT 数据结构，也包含 **gdisk**，不在需要处理 CHS geometries、以及由它带来的各种问题。**fdisk** 的用户会注意到 **gdisk** 缺少于 CHS geometries 相关的选项和限制。

要获得最佳结果，无论何时，你都应该使用一个 OS 特定的分区表程序。举例来说，创建 Mac OS X 分区要使用 Mac OS X 磁盘工具程序，而 Linux 分区上应该使用 Linux **gdisk** 或 GNU Parted 程序。

在启动时，**gdisk** 会尝试确定磁盘上使用的分区类型。若找到了有效的 GPT 数据，**gdisk** 会使用它。若 **gdisk** 找到了一个有效的 MBR 或 BSD 磁盘标签，但没有找到 GPT 数据，它会尝试将 MBR 或磁盘标签转换至 GPT 格式。（BSD 磁盘标签有可能具有无法使用的首个 和/或 最后的分区，因此它们与 GPT 数据重叠。）GPT fdisk 可以分辨，但无法使用 Apple Partition Map（APM）磁盘中的数据，这类磁盘用于基于 680x0 或 PowerPC 的 Macintoshes。当以 'w' 选项退出时，**gdisk** 以 GPT 替换 MBR 或磁盘标签。[.underline]#该操作具有潜在危险！# 你的系统可能无法启动，若磁盘使用无法识别的类型码，那么分区类型码可能损毁。启动问题则极有可能发生在多重启动不能正确识别 GPT 的操作系统上。若你失误地在 MBR 磁盘上启动了 **gdisk**，你可以通过使用 'q' 选项安全地退出程序，而不执行任何修改。

若原始的 MBR 使用了逻辑分区，那么 MBR 至 GPT 转换会留下至少一个分区数间隔。这些间隔并无危害，若你喜欢，你也可以通过 's' 选项消除它们。（如此操作可能需要你更新你的 [.underline]#/etc/fstab# 文件）。

当创建一个全新的分区表时，可以按下面的顺序做出一些考虑：

* 对于数据（非启动）磁盘，以及在基于 BIOS 的计算机上用 GRUB 作为启动器的启动盘，分区应该以何种顺序创建，且分别需要多大的容量。

* 基于 EFI 的系统的启动磁盘需要一个格式化为 FAT32 的 [.underline]#EFI System Partition#（**gdisk** 内部码 0xEF00）。我建议让该分区有 550 MiB 大小。（更小的 ESP 也常见，但有些 EFIs 具有分片 FAT 驱动器，它需要更大的分区来可靠地操作。）启动相关文件存储在这里。（注意 GNU Parted 会认为这种分区具设置了 “启动标示”。）

* 有些 基于 BIOS 系统的启动器会使用 [.underline]#BIOS Boot Partition#（**gdisk** 内部码 0xEF02），在其中存储了二级启动器，可能没有用到文件系统的好处。（GRUB2 可能可选地使用了这种分区。）该分区通常可以非常小（大约只有 32 至 200 KiB，虽然实际上会使用 1 MiB 或更多），你需要参考你的启动器来了解详情。

* 若 Windows 从 GPT 磁盘启动，那么建议保留一个类型为 [.underline]#Microsoft Reserved# 分区（**gdisk** 内部码 0x0C01）。该分区应该为 128 MiB 大小。通常来说它在 EFI System Partition 之后，且它之后立即跟随 Windows 数据分区。（注意，旧版的 GNU Parted 会将所有的 FAT 分区创建为该类型，这实际上让 Windows 和 Mac OS X 均无法将分区用作普通文件存储。）

* 有些系统的 GPT 工具会在每个分区之后创建一些空白空间（通常为 128 MiB）。主要是让未来的磁盘工具利用这些空间。对于 GPT 磁盘来说这些空白并非必要的，但创建它们可能对未来的磁盘维护有用。你可以使用 GPT fdisk 的相对分区位置选项（比如以 '+128M' 来指定开始扇区）来简单创建这类空白。

== 选项

-l::
罗列指定设备的分区表并退出

大多数与 **gdisk** 的交互发生在它的交互式文本模式菜单中。具有三个菜单：主菜单、恢复和转换菜单、以及专家菜单。主菜单提供了对于典型的分区任务最可能有用的功能，比如创建和删除分区、修改分区类型码、等等。特定的功能有：

b::
保存分区数据值备份（backup）文件。你可以用该选项将当前内存中的分区表备份至一个磁盘文件。生成的文件是一个二进制文件，按顺序包含：保护性 MBR、主 GPT 头、备份 GPT 头、一份分区表的拷贝。注意备份的是内存中的数据结构，因此若你启动该程序，并执行了一些修改，然后再使用该选项，那么备份会反映你锁做的修改。注意还原选项再恢复和转换菜单里；备份选项出现在主菜单里以鼓励使用它。

c::
修改（change）一个分区的 GPT 名。该名称编码为 UTF-16 字符串，但要正确输入和显示任何超过 ASCII 范围的值，均需要合适的 locale 和字体支持。大多数情况下，Linux 忽略分区名，但对于有些系统可能会很重要。GPT fdisk 会依照分区类型码设置一个默认的名称。注意 GPT 分区名和文件系统名不同，文件系统名是彪马在文件系统的数据结构中的。

d::
删除（delete）一个分区。该动作从分区表中删除条目，但不会扰乱磁盘上的原始分配给该分区的扇区中的数据。若存在一个对应的 hybrid MBR 分区，**gdisk** 也会删除它，并将任何相邻的 0xEE（EFI GPT）MBR 保护分区扩展填充至新腾出的空间中。

i::
显示详细的分区信息（information）。由 'p' 命令提供的摘要信息必然会省略很多细节，比如分区的唯一 GUID 以及将 **gdisk** 的内部分区类型码翻译为平直类型名。'i' 选项对一个单一分区显示这些信息。

l::
显示分区类型的一个摘要。GPT 使用一个 GUID 来确定特定系统和用途的分区类型。为了便于数据条目显示，**gdisk** 将它们压缩为 2 字节（四个十六进制数）值，相对于它等价的 MBR 码。特别地，MBR 码会乘以十六进制数 0x100。举例来说，Linux 交换空间的代码在 MBR 中为 0x82，那么在 **gdisk** 中为 0x8200。虽然一一对应是不可能的。最需要注意的是，全部的 FAT 和 NTFS 分区的变种全部映射为单一的 GPT 编码（**gdisk** 中为0x0700）。有些系统使用单一 MBR 编码但在 GPT 中使用多个编码。对于这些来说，**gdisk** 顺序增加代码的数字，比如 FreeBSD 磁盘标签 为 0xa500、FreeBSD 启动 为 0xa501、FreeBSD 交换 为 0xa502，等等。注意这些 2 字节编码在 **gdisk** 中为唯一的。类型码列表可以通过字符串搜索过滤；比如，输入 **linux** 就仅显示分区类型码的描述中包含字符串 [.underline]#Linux#。该查找为大小写不敏感的。

n::
创建一个新的（new）分区。该命令依照等价的 **fdisk** 选项构造，虽然存在一些不同。你输入一个分区号、起始扇区、以及一个结束扇区。开始和结束扇区可以以扇区号的绝对形式出现，也可以以 kibibytes（K）、mebibytes（M）、gibibytes（G）、tebibytes（T）、pebibytes（P）计量的位置；举例来说，**40M** 指定了一个自磁盘开头起 40MiB 的位置。你可以通过在数字前追加 '+' 或者 '-' 来指定一个相对于默认起止点的相对位置；比如 **+2G** 指定了在默认起始扇区后的 2GiB 的位置，或 **-200M** 来指定在最后可用扇区前的 200MiB 的位置。不输入任何值按下回车键，就指定了默认值，默认值为最大可用区块的起始扇区和结束扇区。

o::
清空（clean out）全部的分区数据。包括 GPT 头数据、全部分区定义、以及保护性 MBR。扇区对齐则重置为默认值（在 512 字节的扇区上为 1 MiB，或 2048 个扇区）。

p::
显示（display）基础分区摘要数据。包含分区号、起始和终止扇区号、分区大小、**gdisk** 分区类型码、以及分区名。要了解额外信息，使用 'i' 命令。

q::
退出（quit）程序，且 [.underline]#不保存你锁做的修改#。使用该选项若你仅想看信息，或则你做错了一个事情，希望放弃全部的修改。

r::
进入恢复（recovery）和转换菜单。该菜单包含急救恢复选项（以修复损坏的 GPT 数据结构）以及在自己和其它分区系统之间转换用的选项，这也包括创建 hybird MBR。

s::
排序（sort）分区条目。GPT 分区号不需要匹配磁盘上分区的顺序。若你希望它们匹配，你可以使用该选项。注意，有一些分区工具会在它们执行修改的时候排序分区。这类变化会反映在你的设备文件名上，因此若你使用该选项，你可能需要修改 [.underline]#/etc/fstab#。

t::
修改单一的分区类型（type）码。你以 2 字节二进制数输入类型码，如上文所述。若你具有一个 **gdisk** 不知道的类型，你也可以直接输入一个 GUID。

v::
校验（verify）磁盘。该选项会检查一系列问题，比如不正确的 CRC，以及不匹配的主要数据和备份数据。虽然该选项不会自动改正大多数问题，要改正它们，你必须使用恢复和转换菜单中的选项。若未找到错误，该命令会显示为分配的磁盘空间的概述。

w::
写入（write）数据。使用该命令来保存你的修改。

x::
进入专家（expert）菜单。使用该选项以访问更多特性，以便你猛然扎入比主菜单能允许的更多的麻烦之中。

?::
打印该菜单。输入该命令（或任何其它无法被识别的命令）来查看可用选项的摘要。

**gdisk** 的第二个菜单是恢复与转换菜单，它提供了数据恢复选项以及将分区在不同分区规划之间转换的相关特性（比如将 BSD 磁盘标签转换为 GPT 分区或创建 hybrid MBR）。为了操作方便，该菜单的部分选项复制自主菜单。该菜单的选项为：

b::
从备份（backup）重建 GPT 头。你可以使用该选项从备份 GPT 头重建主 GPT 头。若你的主 GPT 头损坏或损毁（比如说，错误使用了 **dd**），那么它可能很有用。

c::
载入备份分区表。通常情况下，**gdisk** 仅使用主分区表（虽然当你启动程序时，会检查备份的完整）。若主分区表以损坏，你可以使用该选项从磁盘上载入备份，并使用它。注意，若你刚刚将 MBR 磁盘转换为 GPT 格式，那么该选项几乎可以保证无法生成或生成奇怪的分区条目，因为此时磁盘上还没有备份分区表。

d::
使用主 GPT 头并重建备份。若备份 GPT 头已损坏或损毁，那么该选项就会比较有用。

e::
载入主分区表。该选项从磁盘上载入主分区表。大概率仅在你尝试（通过 'c'）使用备份分区表，但发现它比主分区表还糟糕时使用。

f::
载入 MBR 并从它新建一个全新（fresh）的 GPT。当你的 GPT 损坏或与 MBR 冲突，你希望以 MBR 为基础创建一系列新的 GPT 分区时，使用该选项。

g::
将 GPT 转入 MBR 并退出。该选项会尽可多地将分区转入 MBR 形式，摧毁 GPT 数据结构，保存新的 MBR，并退出，若你尝试 GPT 但发现 MBR 更合适时，使用该选项。注意该选项会生成至多 4 个主 MBR 分区；或者 3 个主 MBR 分区，以及尽可能多的逻辑分区。每个逻辑分区都要求在它的首个块前立刻有至少一个未分配的块。因此，它可以以紧包裹（tightly-parcked）分区的形式至多转换磁盘上的四个分区；但是，若在分区创建时在分区见插入了间隙，且磁盘小于 2 TiB，那么应该可以将全部的分区转入 MBR。同样参见 'h' 选项。

h::
创建 hybrid MBR。它是一种丑陋的绕行方法，通过创建 MBR 条目，让无法探测 GPT 的系统、或那些不可同 GPT 启动的系统，可以访问磁盘上至多三个分区。注意这些 hybrid MBR 条目很容易脱离与 GPT 条目的同步，特别是当使用了无法探测 hybrid 的 GPT 工具修改磁盘之后。因此，在你使用了这类工具之后，可能需要重建 hybrid MBR。与 'g' 选项不同，该选项不支持将任何分区转换至 MBR 逻辑分区。

i::
显示详细的分区信息（information）。该选项与主菜单的 'i' 选项相同。

l::
从一个备份文件载入（load）分区数据。该选项是主菜单 'b' 选项的反向操作。注意除了从原始磁盘之外的任何地方恢复分区都是不推荐的。

m::
返回主（main）菜单。该选项让你可以进入主菜单命令。

o::
打印保护性 MBR 数据。你可以通过该选项获得一份保护性 MBR 分区的摘要。它可能可以帮你发现明显的错误，或帮助确定 hybrid MBR 中的分区。

p::
打印（print）分区表。该选项与主菜单中的 'p' 选项相同。

q::
退出（quit）并不保存。该选项与主菜单中的 'q' 选项相同。

t::
将 BSD 分区转换（transform）至 GPT 分区。该选项作用于 GPT（或 转换的 MBR）分区持有的 BSD 磁盘标签。转换后的分区类型码可能需要手动调整。在 **gdisk** 启动时，会尝试转换存储在主磁盘上的 BSD 磁盘标签，但这种转换可能会导致第一个或最后一个分区无法使用。由于众多的 BSD 种类，意味着 **gdisk** 无法转换一个 BSD 磁盘标签的概率是高于 MBR 转换出问题的可能性的。

v::
校验（verify）磁盘。该选项与主菜单中的 'v' 选项相同。

w::
将表写入（write）磁盘并退出。该选项与主菜单中的 'w' 选项相同。

x::
进入专家（expert）菜单。该选项与主菜单中的 'x' 选项相同。

?::
打印菜单。该选项（或任何无法识别的条目）显示菜单选项的摘要。
