= 组件签名

本章介绍与证书组件关联的 OpenPGP 签名，签名施加于：

* 组件密钥，包括主密钥和子密钥
* 身份组件，又称用户 ID 和用户属性

组件签名用于构建和维护证书，以及建模身份验证。

== 自签名与第三方签名

OpenPGP 中的签名分为两大类：

* **自签名**，它是由证书持有者使用证书的主密钥签发的
* **第三方签名**，它是由外部实体，而非证书持有者签发的

=== 自签名

自签名是创建和管理 OpenPGP 证书的基础。它们绑定证书的各个组件形成一个数据结构，并参与证书的生命周期管理。

生命周期管理操作包含：

* 将额外的组件绑定至证书
* 修改组件的过期时间或其它元数据
* 吊销，也就是无效化组件或已有的自签名

自签名由证书的所有者使用证书的主密钥签发。

[NOTE]
====
签发自签名不需要密钥标识。OpenPGP 主密钥默认就可以签发自签名。
====

=== 第三方签名

第三方签名对于 OpenPGP 的去中心化认证至关重要，构成了信任网的基石。它们编码了证书的认证相关的陈述，并链接身份，建立起了身份声明（identity claims）的信任。

第三方签名用于以下特定的陈述：

* 验证身份声明
* 下放验证决策（delegating authentication decisions）
* 吊销，也就是无效化之前的第三方签名陈述

[NOTE]
====
**验证他人（certify others）**密钥标识（`0x01`）是签发第三方签名所必须的。通常来说，仅有证书的主密钥可以具有该密钥标识。
====

=== 自签名和第三方签名在功能上的不同

OpenPGP 签名的恨意极大地依赖于它的签发者。即便自签名和第三方签名具有相同的签名类型，它们也具有完全不同的功能。举例来说：

* 认证用（certifying）自签名（类型 ID `0x10` - `0x13`）将用户 ID 绑定至证书。
* 具有相同类型 ID 的第三方签名认证另一个用户的证书上的用户 ID 的真实性。

另一个例子：

* __当签发为自签名时__，直接密钥签名设置的偏好会作用于整个证书。
* __当签发者为第三方__，特别时它附带了可信签名（trust signature）子包时，一个类似的直接密钥签名将用于信任签名的证书。它可以让签名的证书作为签发者的信任网的信任锚点（trust anchor）。

== 证书中的自签名的格式和管理方式

自签名在构成和管理 OpenPGP 证书的结构上扮演重要的角色。它们作为__绑定签名__出现，连接组件并嵌入元数据。

从内部上来说，OpenPGP 证书基本上就是一系列数据包按顺序排列在一起。当证书以可转移公钥的文件格式存储的时候，数据靠就可以被简单地添加或移除。

OpenPGP 使用密码学签名防止组件的非授权添加或修改。它验证了所有组件——比如子密钥或身份组件——都是由证书的所有者使用主密钥链接至 OpenPGP 证书的。虽然任何人依旧可以向证书数据集中添加无关元素，只要它们不具有与证书之间的有效的密码学连接，OpenPGP 实现都会拒绝它们。

[NOTE]
====
相反地，当处理 OpenPGP 证书数据集时，第三方遗漏数据包则较为容易发生。它可能会导致问题，比如若一个攻击者有意隐藏了吊销包。若无法从其它途径访问到完整的证书源，接收者可能无法探测这些遗漏。
====

但是，证书的一些地方允许第三方向其中添加“未绑定”的数据包（比如，未被证书所有者签名的）。

* 第三方证书通常存储在与之相关的证书的数据包中。这是一个标准实践，让用户可以简单地访问所有相关的证书。（见第三方证书洪水攻击来了解相关的潜在危险。）
* OpenPGP 软件可能会在本地向证书中添加未绑定的身份数据。

=== 将子密钥绑定至证书

子密钥通过子密钥绑定签名（类型 ID `0x18`）链接至 OpenPGP 证书。该签名类型表示了主密钥与子密钥之间的联系。

一个子密钥绑定签名将子密钥绑定至主密钥，并将元数据嵌入签名包。一旦生成，在子密钥本身绑定完成后，子密钥绑定签名包会直接存储在证书中。

那些以签名为目的的子密钥，通过__签名（signing）__密钥标识区分，据有独有的类别和特别的处理方法。见 <<特殊情况：绑定签名用子密钥>>。

子密钥的元数据，比如__密钥过期事件__和__密钥标识__确定的能力集，被包含在子密钥绑定签名包的子包中。

[NOTE]
====
子密钥的有效性自然而然地关联于主密钥。一个过期的主密钥会让所有关联的子密钥无效，这无关子密钥自己的过期设置。

在以往，子密钥可能不具有特定的过期时间。此时，它的过期时间隐式地与主密钥的对齐。额外的，子密钥的创建时间必须比主密钥的更晚。
====

=== 特殊情况：绑定签名用子密钥

绑定至证书的子密钥中，具有__签名（signing）__密钥标识的子密钥据有特殊的情况。虽然与其它子密钥具有类似的绑定流程，但其有一个额外的、至关重要的要求：互关联（mutual association）。

也就是说，要将可签名子密钥绑定至主密钥，仅仅表明“主密钥想关联子密钥”是不够的。子密钥也必须明确标识它“想关联主密钥”。

这种互相绑定对安全至关重要。若没有它，那么一个个体（比如 Alice）可以虚假地声明一个连接至另一个人（比如 Bob）的签名子密钥。这样 Alice 就可以声明签发了实际上是 Bob 签发的签名。要防止这类情况——攻击者可能错误地“接受”了被害者的签名子密钥，会使用双层签名：

* 子密钥绑定签名（类型 ID `0x18`），由证书的主密钥签发
* 主密钥绑定签名（类型 ID `0x19`），由子密钥自己签发。其非正式地称为嵌入式“反向签名”，因为子密钥的签名指向了之前的主密钥。

反向签名强调了子密钥和主密钥之间的互关联性，其作为子密钥绑定签名的子包数据嵌入，强化了绑定的真实性。

=== 将身份绑定至证书

自签名在绑定身份组件——比如用户 ID 或用户属性——至 OpenPGP 证书时也十分重要。

有四种__认证自签名（certifying self-signature）__。最常见的用于绑定用户 ID 的类型时正向认证（positive certification）（类型 ID `0x13`）。除此之外，还可以使用类型 `0x10` 、`0x11` 或 `0x12`。这类绑定签名必须由主密钥签发。

认证自签名包——由主密钥、用户 ID 和签名包的元数据计算而来——会在用户 ID 包之后直接添加至证书中。

=== 添加全局元数据至证书

将子密钥和身份组件绑定至证书的签名由两个功能：将组件链接至证书，以及向组件中添加元数据。

由于我们只是想添加影响整个证书的元数据，它并不要求将任何组件绑定至证书。此时，签名机制将仅用于全局地将元数据绑定至证书。

由两类签名可以执行这类功能：

* 主密钥上的直接密钥签名
* 主用户 ID 绑定签名

通过上述方法与证书关联的元数据类型，通常包括：

* 密钥过期时间
* 密钥标识（能力）
* 特性（features）
* 算法偏好

==== 直接密钥签名

__直接密钥签名__是 OpenPGP 第 6 版中推荐的、为整个证书定义元数据的机制，它与主密钥关联

==== 绑定至主用户 ID 的自签名

在 OpenPGP 第 4 版中，常使用另一个机制管理元数据：将全局证书元数据整合至一个用户 ID 绑定签名中。它特定出现在绑定__主__用户 ID 至证书的绑定签名上。

这种方法导致主用户 ID 绑定签名中混合了两种元数据：一部分作用于那个用户 ID，而另一部分作用于证书全局。

由于该机制在现有的 OpenPGP 证书中的广泛使用，OpenPGP 应用必然要可以分辨和管理它。

=== 吊销自签名：无效化认证组件

吊销自签名（revocation self-signature）是一种重要的自签名，主要用于无效化组件或撤回之前的签名陈述。

吊销签名分为几种，每个都有特定的功能：

* 密钥吊销签名（类型 ID `0x20`）将主密钥标记为已吊销。
* 子密钥吊销签名（类型 ID `0x28`）无效化一个子密钥的绑定。
* 证书吊销（类型 ID `0x30`）无效化一个用户 ID 或用户属性的绑定。

使用吊销的常见场景包含，将证书或独立的子密钥标记为不可用（比如私钥泄露或被替换）或者声明用户 ID 不再有效。

[NOTE]
====
OpenPGP 证书在实践上是一个仅追加（append-only）的数据结构。一旦一个证书的元素被发布了，它们就不可以从密钥服务器或第三方 OpenPGP 系统中移除。实现者通常将所有可用的组件和签名合并到一起。

吊销用于将组件和签名标记为无效的。
====

注意：证书签名可以被设置为不可吊销的（irrevocable）。

==== 硬吊销和软吊销

吊销签名通常包含一个__吊销原因（Reason for Revocation）__子包，其中使用一个代号表明__为什么__签发这个吊销。该代号将确定该吊销是__软的（soft）__还是__硬的（hard）__。

* **软吊销**：它通常用于轻柔地或计划性地无效化组件，比如退让或更新组件。它从吊销签名创建时刻开始无效化组件，但之前的使用保持有效。软吊销可以被一个新的自签名反转。
* **硬吊销**:其不可吊销地无效化组件，影响后者之前和未来所有的使用。它通常用于表示私钥的泄露。

[NOTE]
====
不具有吊销原因的吊销签名包将会被解析为硬吊销。
====
