= 组件签名

:密钥标识_url: https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#name-key-flags
:直接密钥签名_url: https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#name-direct-key-signature-type-i
:子密钥绑定签名_url: https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#sigtype-subkey-binding
:证书吊销签名_url: https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#name-certification-revocation-si

本章介绍与证书组件关联的 OpenPGP 签名，签名施加于：

* 组件密钥，包括主密钥和子密钥
* 身份组件，又称用户 ID 和用户属性

组件签名用于构建和维护证书，以及构建身份鉴别模型。

本章节扩展了xref:73.04、证书.adoc[证书]章节介绍的话题。

== 自签名与第三方签名

OpenPGP 中的签名分为两大类：

* **自签名**，它是由证书持有者使用证书的主密钥签发的
* **第三方签名**，它是由外部实体，而非证书持有者签发的

=== 自签名

自签名是创建和管理 OpenPGP 证书的基础。它们绑定证书的各个组件形成一个数据结构，并参与证书的生命周期管理。

生命周期管理操作包含：

* 将额外的组件绑定至证书
* 修改组件的过期时间或其它元数据
* 吊销，也就是无效化组件或已有的自签名

自签名由证书的所有者使用证书的主密钥签发。

[NOTE]
====
签发自签名不需要link:{密钥标识_url}[密钥标识]。OpenPGP 主密钥默认就可以签发自签名。
====

=== 第三方签名

第三方签名对于 OpenPGP 的去中心化认证至关重要，构成了信任网的基石。它们编码了证书鉴别和链接身份相关的陈述，建立起了身份声明（identity claims）的信任度。

第三方签名用于以下特定的陈述：

* 核证身份声明
* 下放验证决策（delegating authentication decisions）
* 吊销，也就是无效化之前的第三方签名陈述

[NOTE]
====
**核证他人（certify others）**link:{密钥标识_url}[密钥标识]（`0x01`）是签发第三方签名所必须的。通常来说，仅有证书的主密钥可以具有该密钥标识。
====

=== 自签名和第三方签名在功能上的不同

OpenPGP 签名的含义极大地依赖于它的签发者。即便自签名和第三方签名具有相同的link:https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#name-signature-types[签名类型]，它们也具有完全不同的功能。举例来说：

* 核证用自签名（类型 ID `0x10` - `0x13`）将用户 ID 绑定至证书。
* 具有相同类型 ID 的第三方签名认证另一个用户的证书上的用户 ID 的真实性。

另一个例子：

* __当签发为自签名时__，link:{直接密钥签名_url}[直接密钥签名]设置的偏好会作用于整个证书。
* __当签发者为第三方时__，特别时它附带了link:https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#name-trust-signature[可信签名（trust signature）]子包时，一个类似的直接密钥签名将用于信任签名的证书。它可以让签名的证书作为签发者的信任网的信任锚（trust anchor）。

== 证书中的自签名的格式和管理方式

自签名在构成和管理 OpenPGP 证书的结构上扮演重要的角色。它们作为__绑定签名__出现，连接组件并嵌入元数据。

从内部上来说，OpenPGP 证书基本上就是一系列数据包按顺序排列在一起。当证书以名为link:https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#name-transferable-public-keys[可转移公钥]的文件格式存储的时候，数据包就可以被简单地添加或移除。

OpenPGP 使用密码学签名防止非授权地添加或修改组件。它确认了所有组件——比如子密钥或xref:73.04、证书.adoc#_身份组件[身份组件]——都是由证书的所有者使用主密钥链接至 OpenPGP 证书的。虽然任何人依旧可以向证书数据集中添加无关元素，只要它们与证书之间不具有有效的密码学连接，OpenPGP 实现都会拒绝它们。

[NOTE]
====
相反地，当处理 OpenPGP 证书数据集时，第三方容易遗漏数据包。它可能会导致问题，比如攻击者可以隐瞒吊销包。若接收者无法从其它途径访问到完整的证书源，那么其可能无法探测这些遗漏。
====

但是，证书的一些地方允许第三方向其中添加“未绑定”的（比如，未被证书所有者签名的）数据包。

* <<_第三方签名中的鉴别和委派,第三方证书>>通常存储在与之相关的证书的数据包中。这是一个标准实践，让用户可以简单地访问所有相关的证书。（见xref:73.18、进阶材料：证书.adoc#_第三方证书洪水[第三方证书洪水]来了解相关的潜在危险。）
* OpenPGP 软件可能会在本地向证书中添加xref:73.18、进阶材料：证书.adoc#_向证书中添加未绑定的本地用户_id[未绑定的身份数据]。

=== 将子密钥绑定至证书

子密钥通过link:{子密钥绑定签名}[子密钥绑定签名]（类型 ID `0x18`）链接至 OpenPGP 证书。该签名类型表示了主密钥与子密钥之间的联系。

一个子密钥绑定签名将子密钥绑定至主密钥，并将元数据嵌入签名包。一旦生成，子密钥绑定签名包会直接存储在证书中、所绑定的子密钥之后。

那些以签名为目的的子密钥，通过__签名（signing）__link:{密钥标识_url}[密钥标识]区分，据有独有的类别和特别的处理方法。见 <<_特殊情况绑定签名用子密钥,章节 特殊情况：绑定签名用子密钥>>。

子密钥的元数据，比如link:https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#key-expiration-subpacket[__密钥过期时间__]以及通过link:{密钥标识_url}[__密钥标识__]确定的能力集，被包含在子密钥绑定签名包的子包中。

[NOTE]
====
子密钥的有效性自然而然地关联于主密钥。一个过期的主密钥会让所有关联的子密钥无效，无关子密钥自己的过期设置。

在以往，子密钥可能没有过期时间。此时，子密钥的过期时间隐式地与主密钥的对齐。额外的，子密钥的创建时间必须比主密钥的更新。
====

=== 特殊情况：绑定签名用子密钥

具有__签名（signing）__密钥标识的子密钥据有特殊的情况。虽然与其它子密钥具有类似的绑定流程，但其有一个额外的、至关重要的要求：互关联（mutual association）。

也就是说，要将可签名子密钥绑定至主密钥，仅仅表明“主密钥想关联子密钥”是不够的。子密钥也必须明确表示它“想关联主密钥”。

这种互相绑定对安全至关重要。若没有它，那么一个个体（比如 Alice）可以声称连接至另一个人（比如 Bob）的签名子密钥。这样 Alice 就可以声明签发了实际上是 Bob 签发的签名。要防止这类情况——攻击者可能错误地“接受”了被害者的签名子密钥——会使用双层签名：

* link:{子密钥绑定签名}[子密钥绑定签名]（类型 ID `0x18`），由证书的主密钥签发
* link:https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#sigtype-primary-binding[主密钥绑定签名]（类型 ID `0x19`），由子密钥自己签发。其非正式地称为嵌入式“返回签名（back signature）”，因为子密钥的签名指向了之前的主密钥。

返回签名强调了子密钥和主密钥之间的互关联性，其作为子密钥绑定签名的子包数据嵌入，强化了绑定的真实性。

=== 将身份认证绑定至证书

自签名在绑定身份组件——比如用户 ID 或用户属性——至 OpenPGP 证书时也十分重要。

有四种__核证用自签名（certifying self-signature）__。最常见的用于绑定用户 ID 的类型是link:https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#sigtype-positive-cert[正向认证（positive certification）]（类型 ID `0x13`）。除此之外，还可以使用类型 `0x10` 、`0x11` 或 `0x12`。这类绑定签名必须由主密钥签发。

核证用自签名包——由主密钥、用户 ID 和签名包的元数据计算而来——会在用户 ID 包之后直接添加至证书中。

=== 向证书添加全局元数据

将子密钥和身份组件绑定至证书的签名有两个功能：将组件链接至证书，以及向组件中添加元数据。

虽然向证书中添加影响整个证书的元数据是基本需求，但他并不要求绑定任何组件至证书。此时，签名机制讲仅用于将元数据全局式地关联至证书。

由两类签名可以执行这类功能：

* 主密钥上的直接密钥签名
* 主用户 ID 绑定签名

通过上述方法与证书关联的元数据类型，通常包括：

* 密钥过期时间
* 密钥标识（能力）
* 特性（features）
* 算法偏好指示

==== 直接密钥签名

link:{直接密钥签名_url}[__直接密钥签名__]是 OpenPGP 第 6 版中link:https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#section-5.2.3.10-9[推荐的]、为整个证书定义元数据的机制，通过与主密钥关联实现。

==== 绑定至主用户 ID 的自签名

在 OpenPGP 第 4 版中，常使用另一个机制管理元数据：将全局证书元数据整合至一个用户 ID 绑定签名中。它特定出现在绑定link:https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#name-primary-user-id[__主__用户 ID] 至证书的绑定签名上。

这种方法导致主用户 ID 绑定签名中混合了两种元数据：一部分作用于那个用户 ID，而另一部分作用于证书全局。

由于该机制在现有的 OpenPGP 证书中的广泛使用，OpenPGP 应用必然要可以分辨和管理它。

=== 吊销自签名：无效化认证组件

吊销自签名（revocation self-signature）是一种重要的自签名，主要用于无效化组件或撤回之前的签名陈述。

有多种类型的吊销签名，每个都有特定的目的：

* link:https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#name-key-revocation-signature-ty[**密钥吊销签名（key revocation signature）**]（类型 ID `0x20`）吊销主密钥。
* link:https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#name-subkey-revocation-signature[**子密钥吊销签名（subkey revocation signature）**]（类型 ID `0x28`）无效化子密钥的绑定。
* link:{证书吊销签名_url}[**证书吊销（certification revocation）**]（类型 ID 0x30）无效化用户 ID 或用户属性的绑定。

使用吊销的常见场景包含，将证书或独立的子密钥标记为不可用（比如私钥泄露或被替换）或者声明用户 ID 不再有效。

[NOTE]
====
OpenPGP 证书在实践上是一个仅追加（append-only）的数据结构。一旦一个证书的元素被发布了，它们就不可以从密钥服务器或第三方 OpenPGP 系统中移除。实现者通常将所有可用的组件和签名合并到一起。

吊销用于将组件和签名标记为无效的。
====

注意：证书签名可以被设置为link:https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#name-revocable[不可吊销的（irrevocable）]。

==== 硬吊销和软吊销

吊销签名通常包含一个link:https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#name-reason-for-revocation[__吊销原因（Reason for Revocation）__子包]，其中使用一个代号表明__为什么__签发这个吊销。该代号将确定该吊销是__软的（soft）__还是__硬的（hard）__。

* **软吊销**：它通常用于轻柔地或计划性地无效化组件，比如退让或更新组件。它从吊销签名创建时刻开始无效化组件，但之前的使用保持有效。软吊销可以被一个新的自签名反转。
* **硬吊销**：本身不可吊销地无效化组件，影响后者之前和未来所有的使用。它通常用于表示私钥已经泄露。

[NOTE]
====
不具有吊销原因的吊销签名包将会被解析为硬吊销。
====

== 第三方签名中的鉴别和委派

OpenPGP 中的第三方签名主要用于编码身份的鉴别陈述、以及委派信任决策。这些签名可以手动检验或通过 OpenPGP 软件以机器可读的形式进行处理，它是基于用户指定的信任锚来评估证书的真实性的。

=== 核证身份组件

当一个签名者对一个身份签发了一个核证签名，它就表明了身份与证书之间的一个验证过的链接。也就是说，签名者担保该身份声明。

举例来说，Alice 可以通过创建核证签名，来担保 Bob 的用户 ID `Bob Baker <bob@example.com>` 和他的证书 `BB28 9FB7 A68D BFA8 C384 CCCD E205 8E02  D9C6 CD2F 3C7C 56AE 7FB5 3D97 1170 BA83` 是合法链接的。Bob 之后就可以分发 Alice 的核验签名作为他证书的一部分。

其它用户可以自行决定是否要依赖 Alice 的陈述来验证 Bob 的证书的真实性。

=== 信任签名：委派鉴别

OpenPGP 使用link:https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#trust-signature-subpacket[__信任签名（trust signature）__]子包来委派认证决策，将接受方的证书作为用户的“受信介绍人（trusted introducer）”（或称信任锚）。其包含确定暂态委托（transitive delegations）的信任深度（trust depth）（或级别 level），使用数字量化信任，表明介绍人的证书的可靠程度。

信任签名子包在第三方签名中可用，更具体的来说：

* 身份认证签名（类型 ID `0x10` 至 `0x13`）
* link:{直接密钥签名_url}[直接密钥签名（类型 ID `0x1F`）]

==== 信任深度/级别

OpenPGP 中的“信任深度”（或级别）强化了鉴别过程中暂态委托的程度。它确定了一个委托可以从原始受信介绍人扩展至其后中继的程度。基本上来说，若一个证书具有大于 1 的信任深度，那么它就会作为“元介绍人”，让鉴别决策可以跨多个网络。

信任深度为 1 表示其依赖于由可信介绍者直接制作的证书。对于验证身份来说，用户的 OpenPGP 软件将接受由介绍人直接制作的证书。

但是，当信任深度更高时，它按时了委托链可以超越初始的介绍人。用户的软件将识别并介绍不仅仅是主介绍人制作的证书，同时也包含由主要介绍人指定为可信介绍人的其它中间人制作的证书。

其允许更据扩展性的可信证书网络，实现了更广泛更具连接性的信任网。

==== 可信度

“可信度（trust amount）”是一个 `0` 至 `255` 的值，用于量化一个委派的可依赖程度。

更高的值意味着更强的可依赖程度。这个量化值，辅助 OpenPGP 软件，基于多个可信介绍人的证书，推断可信赖程度。

==== 限制委派作用域

当使用__信任签名__子包时，一个委派可以通过一个link:https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#regex-subpacket[__正则表达式__]限制到部分身份上。

通过这个机制，举例来说，可以将鉴别决策仅仅委派至匹配上特定组织的电邮域名的用户 ID 上。

=== 信任网：去中心化信任决策

OpenPGP 中的信任网是一个通过证书和委派网络构建的鉴别决策的可信模型。它的特点被称为link:https://en.wikipedia.org/wiki/Web_of_trust#Strong_set[强集（strong set）]，意思为通过第三方证书强健地相互连接在一起的一组证书。

在这个模型中，用户独立地委派鉴别决策，选择要依赖谁的证书。这个委派是基于可用的证书和第三方签名的，他们的 OpenPGP 软件应用信任网机制来辨别每个身份证书的可靠性。

OpenPGP RFC 并不明确规定信任网的计算该如何执行。它仅定义了可以用于执行信任网计算的数据的格式。

=== 吊销一个第三方签名

要反转一个之前签发的第三方签名，签发者可以生成一个link:{证书吊销签名_url}[证书吊销签名（certification revocation signature）]（类型 ID `0x30`）。该吊销必须有创建原始签名的密钥签发，或者，在过时的实践中，使用专用的link:https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#name-revocation-key[吊销密钥（Revocation Key）]。
