= 数据签名

:crypto-refresh-12_url: https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html

在 OpenPGP 中，__数据签名__保证了特定数据的真实性并（隐含地）保证了其完整性。数据签名的典型用法包括软件包和电邮的鉴别。

“真实性”在这里表示的是，数据签名是由控制签名密钥的实体签发的。但是，它并不自动表示，期望的个体的确控制了签名者证书。OpenPGP 的确提供了__强鉴别__机制，可以将证书与特定身份连接。它验证了要交流的对象就是签名关联的密码学身份。

数据签名仅能被具有__签名__link:{crypto-refresh-12_url}#name-key-flags[密钥标识]的组件密钥签发。

注意，数据签名与xref:73.08、组件签名.adoc[组件签名]完全不同，后者用于构造和维护证书，也可以用于核证证书上的身份。

== 签名类型

OpenPGP 数据签名有两种xref:73.06、OpenPGP 签名.adoc#_openpgp_的签名类型signature_types[签名类型]：

* link:{crypto-refresh-12_url}#sigtype-binary[**二进制签名]（类型 ID `0x00`）**：它是二进制数据的标准签名类型，通常用于文件或数据流。二进制签名直接在原始数据上进行计算，不对原始数据执行任何修改或转换。
* link:{crypto-refresh-12_url}#name-signature-of-a-canonical-te[**文本签名]（类型 ID `0x01`）**：用于文本数据，比如电邮的正文部分。计算文本签名时，会将文本的行尾标识符转换为统一形式（`<CR><LF>`）。该方案解决了不同平台的不同文本编码问题。这对分离式（detached）和明文式（cleartext）签名非常重要，因为信息文件在签名的创建和验证过程中可能会经历重编码的过程。

数据签名首先计算信息内容和 OpenPGP 签名包的元数据的散列值，接着在得到的散列值上计算密码学签名。生成的密码学签名则存储在签名包中。

数据签名有三个截然不同的形式，我们将在下方的文档中说明。

== OpenPGP 数据签名的形式

OpenPGP 数据签名有三种截然不同的形式：

* **分离式（detached）**：OpenPGP 签名作为单独实体出现，与被签名的数据相互独立。
* **内联式（inline）**：原始数据和对应的 OpenPGP 签名被封装在一个 OpenPGP 报文中。
* **明文签名（cleartext signature）**：一个明文信息与其 OpenPGP 签名混合而成的文本格式，保留了原始信息的可读性。

== 分离式签名

分离式签名通过对需要签名的数据计算 OpenPGP 签名来实现。原始数据保持不变，OpenPGP 签名则分开存放——比如一个独立的文件。一个分离签名文件可以与原数据一同或独立分发。原始数据文件的真实性和完整性可以通过分离式签名文件来验证。

这种签名格式适用于签名软件发布，以及其他任何必须确保原始数据在签名过程中不被修改的场景。

== 内联式签名

内联式签名将被签名数据与对应的数据签名合并为一个 OpenPGP 报文。

该方法通常用于签名或加密电邮。大多数可以处理 OpenPGP 通信的电邮软件通常使用内联式签名。

对于更多的细节和内容，见xref:73.21、进阶材料：数据签名.adoc#_内联已签名报文的内部[内联已签名报文的内部]。

== 明文签名

OpenPGP 中的__明文签名框架（Cleartext Signature Framework， CSF）__面向两个主要的目标：

* 让信息保持人类可读的格式，无需 OpenPGP 软件也可以读取
* 与一个 OpenPGP 签名结合，让使用兼容 OpenPGP 软件的用户可以鉴别其身份

=== 案例

我们可以通过 `sq` 命令生成一个明文签名：

[source, sh]
----
echo "hello OpenPGP" | sq sign --signer-file <签名者私钥文件> --cleartext
----

生成的结果明确分为两个部分，首先是明文信息，使用 `BEGIN PGP SIGNED MESSAGE` 开始，并跟随 `BEGIN PGP SIGNATURE` 和 `END PGP SIGNATURE` 包裹的、ASCII 装甲后的签名。前者是人类可读的，而后者包含可以被 OpenPGP 软件验证的签名。

=== 用途

明文签名结合了分离式和内联式签名的优势：

* **自包含格式（self-contained format）**：明文签名让信息和其签名保存在同一个文件中。
* **人类可读性（human readability）**：明文签名中的信息保持明文格式。排除了需要特定软件才能读取信息内容的问题。

这些特性对于签名信息是半人工管理的，且现有的系统架构不支持或只能有限支持 OpenPGP 的情况下非常有用。

=== 明文签名的文本转换

明文签名框架包含了特定的文本标准化过程，保证了信息的完整性和明确性：

* **转义破折号（escaping dashes）**：框架实现了一种原始信息的link:{crypto-refresh-12_url}#name-dash-escaped-text[破折号转义文本]的方法。破折号转义保证了解析器可以正确分辨,签名结构的装甲头部（armor headers）和任何恰好以破折号开头的信息行。
+
[TIP]
====
依照观测应该是在破折号开头的行的开始处插入了一个破折号和一个空格。
====

* **规范化行尾**：与其它<<_签名类型,文本签名>>方式保持一致，明文签名会基于规范化行尾（`<CR><LF>`）后的文本进行计算。这可以让签名在任各种收方实现中都保持正确。

=== 潜在危险

即便被广泛接受，明文签名有其限制，有时也会被当作“过时方法”。RFC 详述了link:{crypto-refresh-12_url}#name-issues-with-the-cleartext-s[明文签名的潜在危险]，比如不兼容语义上有意义的白空格（比如 markdown 文档），对于大型信息的支持，以及与误导性散列头部操作相关的安全漏洞。鉴于这些问题，会建议使用更安全的内联式或分离式签名形式。
