= 总览

== 为什么使用 OpenPGP？

OpenPGP 是总所周知的、IETF 标准化的加密操作集。它广泛用于保证通信安全——比如加密信息和邮件；并且，在大多数 Linux 分发版中，它用来保证软件包的完整性。它拥有大量的库、工具、社区支持论坛组成的生态系统。而且，它的强健性和多功能让 OpenPGP 在其它需要加密和保证完整性的领域也有一席之地——包括文件传输程序、密码管理器、安全数据存储以及为 git 仓库中的源码签名。

它还有一些其它的原因，让你可以考虑在项目中使用 OpenPGP：

. **去中心化信任模型**：OpenPGP 的去中心化定义了一种鉴别（authentication）机制，让个人和实体可以创建和管理自己的密码学身份（cryptographic identities）。与中心化的信任模型不同，去中心化的信任模型让个人和实体管理他们自己的身份，构建了一个社区驱动的信任网（web of trust），而不依赖于中心化的权威，减少了单点故障发生的概率。

. **端对端（end-to-end）加密**：OpenPGP 为实现端对端加密提供了一个强壮的框架。即便信道本身可能已不可信任，内容依旧保持机密（confidential）、可验证（verifiable）、可鉴别（authenticated），并可抵抗非授权的访问。加密在众多场景中都非常关键，特别是在传送一些敏感信息——比如财务数据、个人身份信息（personally identifiable information, PII），或专有商务数据——时。

. **匿名性（Anonymity）与假名性（pseudonymity）**：在敏感或临时的情境下，身份保护是很重要的，OpenPGP 可以用于提供一定层次的匿名性或假名性，已保护用户的身份信息。

. **互通性（Interoperability）**：OpenPGP 是一个结构化的、标准化的协议，广泛被各类公开或私密的实体采用，但又不与任何供应商技术绑定。它支持所有的主流操作系统，比如 Windows、macOS、GNU/Linux、Android 和 iOS。由于其标准化、广泛采用、跨平台兼容、以及可移植性，OpenPGP 的互通性极大地减少了开发的时间、花费和技术壁垒。

== 历史概述

OpenPGP 标准随时间演进，并且仍在活跃开发。

（见 link:https://www.openpgp.org/about/history/[]）

=== Pretty Good Privacy（PGP）

OpenPGP 的历史可以溯回至 __Pretty Good Privacy（PGP）__，由 link:https://en.wikipedia.org/wiki/Phil_Zimmermann[Phil Zimmermann] 编写的软件，其发布于 1991 年。

虽然原始的 PGP 软件从未赋予自由软件许可，但其源码已被作者广泛公开了。link:https://en.wikipedia.org/wiki/Pretty_Good_Privacy#PGP_Corporation_and_Symantec[PGP 的所有权随时间几经转手]，link:https://en.wikipedia.org/wiki/Pretty_Good_Privacy#PGP_Corporation_encryption_applications[PGP 的产品范围和套件都有所扩展]。

=== 标准化 OpenPGP

虽然 PGP 最开始是作为商业软件开发的，但是当时的所有者，PGP 公司，与 IETF 合作开始其标准化，在 1996 年 8 月发表了 link:https://datatracker.ietf.org/doc/html/rfc1991[RFC 1991 “OpenPGP Message Exchange Formats”]。

在 1997 年 7 月，启动了一个在新名称 link:https://en.wikipedia.org/wiki/Pretty_Good_Privacy#OpenPGP[OpenPGP] 下制定一个新的开放标准的进程，在 1995 年 11 月发表了 link:https://datatracker.ietf.org/doc/html/rfc2440[RFC 2440 “OpenPGP Message Format”]。

OpenPGP 这个名称可以被实现自由使用，不像名称 PGP，是一个link:https://uspto.report/TM/74685229[注册商标]。

=== GnuPG，一个早期的自由软件实现

在 link:https://gnupg.org/download/release_notes.html#sec-2-70[1997 年 12 月 20 日首次发布的]，由德国计算机程序员 Werner Koch 编写的 GNU Privacy Guard（GnuPG）是 OpenPGP 标准的一个自由的、开源的实现。

GnuPG 是 OpenPGP 的早期的主要的实现。随着时间推移，GnuPG 的重要性与日俱增，因为它称为了邮件安全、软件签名等的基础工具。它在 link:https://en.wikipedia.org/wiki/Edward_Snowden[Edward Snowden] 发表 link:https://theintercept.com/2014/10/28/smuggling-snowden-secrets/[NSA 文档]中，起到了重要而成功的作用。

因为 GnuPG 程序的二进制文件称为“gpg”，因此“GnuPG”和“gpg”通常互换使用。

== RFC 4880 时代

=== OpenPGP 第 4 版

在 2007 年，IETF 发布了 link:https://datatracker.ietf.org/doc/html/rfc4880[RFC 4880]，定义了第 4 版 OpenPGP。即便到 2023 年后半年，第 4 版依旧是最常用的版本。

在 link:https://www.rfc-editor.org/rfc/rfc6637[RFC 6637] 中，扩展了一个椭圆曲线加密，指定了三个 NIST 质数域曲线的用法。

一些实现尝试了其它非标准化的扩展。值得注意有，基于 Curve 25519 的算法定义在了 link:https://datatracker.ietf.org/doc/draft-koch-eddsa-for-openpgp/[draft-koch-eddsa-for-openpgp] 文档中。虽然这些算法被广泛使用，然该算法从未正式标准化。

=== OpenPGP 的主要实现

如今，有多个 OpenPGP 的实现扮演了重要的角色：

* Mozilla Thunderbird 电邮软件使用了 link:https://www.rnpgp.org/[RNP]，一个 C++ 的 OpenPGP 的实现。
* link:https://gnupg.org/[GNU Privacy Guard（GnuPG）]，OpenPGP 标准的一个关键实现，整合进了无数关键的基础架构中，最突出的就是用于验证 Linux 分发版的软件包的完整性。
* Proton Mail，为大量用户提供了邮件加密服务，使用和维护了 link:https://openpgpjs.org/[OpenPGP.js] 和 link:https://gopenpgp.org/[GopenPGP]，后者是 OpePGP 用 golang 实现的封装库。
* RPM 包管理器软件通过 link:https://sequoia-pgp.org/[Sequoia PGP] 包含了一个 OpenPGP 后端，一个现代的由 Rust 编写的 OpenPGP 实现。Fedora Linux 操作系统自从 38 版开始link:https://sequoia-pgp.org/blog/2023/04/27/rpm-sequoia/[在 rpm 中使用 Sequoia PGP]。

=== 互通性

OpenPGP 在 1997 年实现标准化，并鼓励可互通实现的开发。在早些年它已经成功实现，近些年，<<_openpgp_的主要实现, 开始了更多新的实现的开发>>。

历史上，互通性是基于临时确定的方案进行测试的。自从 2019 年之后，Sequoia 项目维护了link:https://tests.sequoia-pgp.org/[“OpenPGP interoperability test suite”]，来执行严谨和系统性的测试。

== 未来的路

[NOTE]
====
由于内部测试、重大变更、避免混淆、市场决策或技术问题等原因，软件和协议开发有时会跳过版本号。OpenPGP 第 4 版的正式后续版本是 OpenPGP 第 6 版，详情如下。
====

=== OpenPGP 第 6 版

在原文书写时（2023 年），link:https://datatracker.ietf.org/doc/draft-ietf-openpgp-crypto-refresh/[OpenPGP 的第 6 版]已接近发布为 RFC。link:https://datatracker.ietf.org/wg/openpgp/about/#autoid-1[IETF OpenGPG 工作小组]聚焦于更新加密机制，添加新算法，并移除已过时的算法。

本文档描述 OpenPGP 第 6 版，并指出该版本与之前版本中，与开发者相关的不同的部分。

OpenPGP 第 6 版已经得到了多个实现的大力支持，包括:

* link:https://github.com/bcgit/bc-java/issues/1421[Bouncy Castle Java]
* link:https://github.com/ProtonMail/gopenpgp/tree/v3[GopenPGP]
* link:https://github.com/openpgpjs/openpgpjs/releases/tag/v6.0.0-alpha.0[OpenPGP.js]
* link:https://github.com/dkg/PGPy/tree/dkg/crypto-refresh[PGPy]
* link:https://gitlab.com/sequoia-pgp/sequoia/-/tree/crypto-refresh[Sequoia PGP]

在 PGPainless 和 RNP 实现中，已经初步加入了对 OpenPGP 第 6 版的支持。

=== OpenGPG 中的后量子时代加密

已有link:https://datatracker.ietf.org/doc/draft-ietf-openpgp-pqc/[正在进行的工作]，为 OpenGPG 中标准化并添加后量子时代的公钥算法。该项目由link:https://en.wikipedia.org/wiki/Federal_Office_for_Information_Security[德国“BSI”]资助。其目标包括向 Thunderbird 和 GnuPG 中添加后量子时代的加密支持。link:https://datatracker.ietf.org/meeting/113/session/openpgp/[IETF 113] 中有相关的link:https://datatracker.ietf.org/meeting/113/materials/slides-113-openpgp-a-post-quantum-approach-for-openpgp-00[演示]。

== 展示细节：OpenGPG 数据的内部结构

OpenPGP 内部以“包（packet）”的形式构建数据。我们将在本文档的最后几个章节来看一个案例。

了解 OpenPGP 数据的内部结构对了解 link:https://datatracker.ietf.org/doc/draft-ietf-openpgp-crypto-refresh/[RFC] 很有帮助。后者对 OpenPGP 包的内部结构有详尽的描述，而且对排错也有帮助。

(不过，大多数情况下，我们会在更高的抽象层次上查看 OpenPGP 工具。）
