= 签名验证

OpenPGP 协议中的签名验证是一个复杂的过程。由很多因素会影响一个签名的有效性。

首先是它的过期时间：一个签名可以在一个时间点前是有效的，而在这个时间点之后是无效的。

签名可以因为其它签名的缺失或存在（比如吊销）而无效。有些签名可以独立验证，而其它则要求验证整个如链表一般的签名结构，它们大多数时候都存在于签发者的证书中。

== 签名何时有效？

作为必要条件，一个有效的签名必须xref:73.06、OpenPGP 签名.adoc#_验证一个_openpgp_签名包[在密码学上正确]。这意味着签名和输入数据都必须保持原始未变的状态。

但是，签名的__正确性（correctness）__和__有效性（validity）__是不同的：

一个签名可以是密码学正确的，但依旧不被认为是__有效的__签名。用数学语言描述，就是有效的签名是正确的签名的子集。

一个正确的签名的有效性还额外受到一些条件的约束：

* **良构成（well-formedness）**：签名包必须具有良好的构成。这意味着，它们必须包含合适的签名元数据（这包含：必要的签名子包必须出现在正确的子包位置）。这些签名元数据必须不包含未知的关键子包或关键的标注。有一些实现还会额外限制可接受的散列算法、密码学算法和密钥强度。

* **时间有效性（temporal validity）**：大多数签名都具有有限的有效周期，由签名的创建和过期时间限制。

* **认可约束（qualification）**：更进一步，有些签名需要被其它有效的签名__认可__才可以被认为是有效的。这条特别是在签名是由专用签名子密钥创建的情况下非常重要，此时，除了签名本身，绑定签名用的子密钥也必须是有效的。

* **吊销**：最后，签名可以被吊销无效化。

== 签名的良构成

签名必须满足一系列条件才能被认为具有良结构：

* 每个签名**必须**在它的散列子包区域中具有签名创建时间子包。一个仅有未散列的——或者压根就没有的——创建时间的签名不是良构成的。

* 签名不可以比签发它的组件密钥更旧。

* 类似地，具有未来创建时间的签名也应该被拒绝。

* 一个良构成的签名需要持有一个签名者指纹（Issuer Fingerprint）子包，或者一个签名者密钥 ID（Issuer KeyID）子包。通常建议将签名者子包放在签名的散列区域中，但接收端实现也可能会接受仅在未散列区存储该类子包的拷贝的签名。

* 若一个签名具有一个标记为关键的、但接收方实现无法理解的子包，那么该签名也不会认为是良构成的。不具有关键标记的未知子包不影响签名是否是良构成的。

* 对于标注也是相同的。若关键标注无法被接收方读取，那么该签名也不会被认为是良构成的。

== 时间有效性

一个签名仅在特定的时间周期中有效：

* 签名的创建时间是该签名有效性的下限。一个签名仅在创建时间之后才是有效的。硬吊销签名是一个例外：在定义中它们在任何时间都是有效的，没有下时间限制。

* 签名的过期时间若存在，则其作为该签名有效性的自然时间上限。

当检查一个签名的有效性时，会使用参考时间（reference time）。签名的有效性是在参考时间点上评估的。

参考时间可以是：

* 验证时的当前时间，或者

* 另一个对签名有效性来说非常重要的时间点。比如，当检查一个电邮的签名的时候，参考时间可能是签名的创建时间，或者电邮的接收时间。

若一个签名要想被验证为有效的，它必须处于生效的时间之内。也就是说，参考时间必须在签名的创建和过期时间之间。

若一个签名需要依赖于其它签名的有效才有效的时候，所有相关的签名必须在同一个参考时间上都有效。

== 自判定和非自判定签名

有一些签名可以仅凭自己验证，而另一些则依赖于签名者证书上的其它签名的有效性。我们称前一种为__自判定（self-qualifying）__签名。

通常情况下，自判定签名是自签名，也就是说签名所在的组件是由它所在证书的 OpenPGP 主密钥签发的。

自判定签名的例子有：

* 直接密钥自签名（`0x1F`），
* 用户 ID 自核证（`0x10` - `0x13`），
* 密钥吊销自签名（`0x20`），
* 证书吊销自签名（`0x30`）或
* 用于绑定或吊销子密钥的自签名（`0x18`、`0x19`、`0x28`）。

非自判定的例子有：

* 数据签名（`0x00`、`0x01`）以及
* 通过第三方证书签发的签名，比如：
** 第三方直接密钥签名（`0x1F`），
** 第三方密钥吊销（`0x20`），
** 第三方证书（`0x10`-`0x13`），或
** 第三方证书吊销签名（`0x30`）。

== 签名判定

要验证一个非自判定签名，不仅仅需要检查签名本身。

这是由于组件密钥必须具有特定的资格才能签发这类签名（比如：必须具有特定的密钥标识）。这种能力一般来自于密钥上的自签名。

简而言之，必须达成从末端签名到签名者证书的主密钥之间的有效签名链。

举例来说，若一个子密钥希望签发一个在电邮正文上的数据签名，那么该子密钥必须有效地通过子密钥绑定签名绑定至签发者的证书上。那个绑定签名必须包含一个__密钥标识__子包，将子密钥标记上__签名__能力。同样的，在第三方证书上签发证书签名，要求签发者密钥具有一个有效的自签名，且该密钥具有__核证__密钥标识。

自判定签名没有类似的限制。

举例来说，一个由主密钥和单一密钥吊销自签名的证书，包含验证该吊销的所有信息，由于密钥吊销自签名是自判定的。这种结构被称为link:https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html#name-openpgp-v6-revocation-certi[吊销证书]。

另一面，要验证文本文档上的数据签名，实现者不仅需要验证数据签名本身，还需要验证用来判定签名子密钥的绑定签名（和反向签名）的有效性。

== 吊销

一个签名可以被一个吊销签名所__无效化__。

吊销可以限制其作用范围，比如，一个子密钥吊销签名仅吊销一个子密钥。更近一步，吊销可以通过在吊销签名中，包含一个软吊销原因和过期原因，将其约束至特定的有效周期。
