= 在 OpenPGP 中管理私钥

== 私钥概览

本章讨论 OpenPGP 中的私钥管理。

== 术语：“证书”与“私钥”

术语__OpenPGP 证书__表示通常意义上的“OpenPGP 公钥”。OpenPGP 证书是组件公钥、身份组件、绑定自签名、三方认证的组合。

本章聚焦于证书元素的对应部分：组件密钥的__私钥__。

在本文档中，我们认为私钥在逻辑上与 OpenPGP 证书是分离的。使用私钥的操作通常通过不同的子系统完成。将 OpenPGP 证书和关联的私钥视为两个相关但全然不同的元素是很有帮助的：

在特定的情况下，密码学私钥会嵌入 OpenPGP 证书 之中。此类操作在可转移私钥（transferable secret keys, TSKs）的情境中出现。

TSK 格式在备份 OpenPGP 密钥或转移密钥至不同的电脑时十分有效。

====
术语：
可转移私钥有时通俗地称为“OpenPGP 私钥”。
====

历史上，TSK 的概念——将一个 OpenPGP 证书的所有元素及其关联的私钥合并在一起——有时会与 OpenPGP 私钥操作交叉。但是，TSK 主要用于（备份）存储和迁移；通常来说，它不应该用于私钥存储（private keystore）之中。

== 用密码（passphrases）保护密钥

在 OpenPGP 格式中，私钥可以可选地被一个密码保护。

当未授权方获取了 OpenPGP 密钥数据之后，若其不知道密码，那么它就无法访问和使用该密钥。

=== 将密码转换为对称密钥

在 OpenPGP 中，当我们保护私钥时，一个对称密钥会派生自用户的密码。该派生的密钥则会用于保护 OpenPGP 私钥数据。

要实现它，OpenPGP 标准定义了一组被称为字符串转密钥（string-to-key, S2K）的机制。S2K 机制，使用密钥派生函数（key derivation funtion, KDF），从低熵（low-entropy）的密码中生成高熵（high-entropy）的对称加密密钥。

该对称密钥用于在被动状态（passive state）——比如存储在硬盘上——下保护私钥。要使用密码保护的 OpenPGP 私钥，它首先需要使用对称密钥解密，之后才能用作私钥操作，解密后的私钥会在内存中短暂地保持解锁状态。

==== 对称密钥生成的机制

随时间推移，OpenPGP 开发了各种用于 S2K 机制的对称密钥生成方法，同时伴随密码学实践的演进。目前，有两种推荐的通用机制：

* **Argon2**：在 OpenPGP 第 6 版中推出，Argon2 是一种耗费内存（memory-hard）的机制，设计为减轻使用特殊硬件进行快速暴力破解的攻击。
* **迭代加盐 S2K（Iterated and Salted S2K）**：该机制是 OpenPGP 第 4 版的主要机制。

=== 基于组件的密码保护

OpenPGP 中保护私钥的机制是独立应用在每个组件密钥上的：

* 同一个证书中的不同组件密钥的私钥可以使用不同的密码和加密机制来保护。
* 部分组件密钥可以以不保护的方式记录，而其它的可以保持加密。

通常情况下，在创建一个证书时，用户的软件会使用相同的加密机制和密码来保护所有的组件密钥。这可能会让人误以为所有的私钥是一次性被一种加密算法和一个密码加密的。

但是，使用多种组合是可行的，比如向一个已有的证书中加入新的子密钥时，软件和用户就可以尝试使用不同的加密算法和密钥，以符合最新的实践方法。

== 私钥的 OpenPGP 卡（OpenPGP card）

（略）

== 私钥操作

虽然 OpenPGP 具有广泛的密码学机制，但是对私钥存储（private keystore）的核心操作是简单而有限的。

准确来说，OpenPGP 私钥存储实现了两类原语：

. 给定一个支持解密算法的私钥，他可以解密一个__会话密钥__。
. 给定一个支持签名算法的私钥，他可以计算一个散列摘要的__密码学签名__。
