= 证书（certification）

OpenPGP 基本上是建立在“OpenPGP 证书（OpenPGP certification）”——又称“OpenPGP 公钥”——的概念上的。这些证书是复杂的数据结构，用来验证身份、数据加密和数字签名。理解其结构和功能是高效使用 OpenPGP 标准的核心内容。

一个 OpenPGP 证书，从定义上来说，不含有私钥内容。

== 术语：理解“密钥（keys）”

=== 公钥 vs 私钥

在没有其它语境的情况下，术语“（密码学）密钥”可以指代非对称密钥中的公钥或私钥。额外的，在 OpenPGP 中，对称密钥可以用于加密私钥，额外添加了一层安全性和复杂度。

=== OpenPGP 中密钥的层级

在 OpenPGP 中，术语“密钥”可能指代三个完全不同的层级，每个都有独特的作用：

. 一个（单纯的）“密码学密钥”包含了私钥和/或公钥参数构成的密钥。举例来说，就 RSA 私钥来说，密钥包含了指数 `d` 以及两个质数 `p` 和 `q`。

. 一个 OpenPGP __组件密钥（component key）__ 包含一个“OpenPGP 主密钥（primary key）” 或一个“OpenPGP 子密钥（subkey）”。它是 OpenPGP 证书的组成部分，前者自身由一个密码学密钥对以及一些不可变元数据——比如密钥创建时间——组成。

. 一个“OpenPGP 证书”（或称“OpenPGP 密钥”）由数个组件密钥、身份组件（identity components）及其它一些元素构成。这些证书是动态的，会由于组件的增加、过期或标记为失效而变化。

== OpenPGP 证书的结构

一个 OpenPGP 证书（或“OpenPGP 密钥”）是以下任意数量的元素的集合：

* 组件密钥
* 身份组件
* 额外的元数据，包括证书的各个组件之间的关联

本文将组件密钥和身份认证密钥统称为“证书的组件”。

一个 OpenPGP 整数的每个元素都围绕着一个中心组件：__OpenPGP 主密钥__。对于证书的所有者来说，主密钥如同个人的__证书认证中心（certification authority, CA）__，支持子密钥、身份验证、过期、吊销等密码学声明。

[NOTE]
====
OpenPGP 证书通常具有很长的生命周期，而且有可能随着时间被（通常是所有者）修改。在证书的整个生命周期中，组件可能会被添加或无效化。但是，一旦证书被发布，那么它的组件是不可以被移除的。
====

== 组件密钥

一个 OpenPGP 证书通常包含多个组件密钥。组件密钥有两个角色：要么是“OpenPGP 主密钥”，要么是“OpenPGP 子密钥”。

OpnPGP 组件密钥逻辑上包含一个非对称密码学密钥对，以及一个创建时间戳。一旦创建，组件密钥的这些属性就保持固定（对于 ECDH 密钥，会有另外两个额外的参数构成组件密钥的数据部分）。

包含了私钥的组件密钥也会包含关于密码保护方案的元数据。它是另一方面的元数据，如同我们之前提到的创建时间戳以及特定算法的额外参数。但是，我们这里仅讨论 OpenPGP 证书，也就是说组件密钥仅包含其密码学密钥数据中的公钥部分。

=== 指纹（fingerprint）

每个 OpenPGP 组件密钥都具有一个 __OpenPGP 指纹__。该指纹由公钥、创建时间戳、（若有）ECDH 参数衍生而来。

OpenPGP 组件密钥的指纹一般为 512bit，表示为 16 组两字节十六进制数。

[NOTE]
====
实际上，即便组件密钥的指纹在理论上并非唯一的，但实际上指纹实际上是作为唯一标记使用的。在生成指纹的时候使用的密码学散列算法，使得两个不同的组件密钥几乎不可能具有相同的指纹。
====

=== 主密钥

OpenPGP 主密钥是一个组件密钥，它在 OpenPGP 证书中具有特殊的、中心用途：

* 它的指纹将作为整个 OpenPGP 证书的身份认证。
* 它将作用于整个生命周期中的操作，比如添加或无效化一个证书中的子密钥或身份认证。

[NOTE]
====
在 RFC 中，OpenPGP 主密钥有时也被称为“top-level key”。在非正式的情况下，它也会被称为“master key”。
====

=== 子密钥

现代 OpenPGP 证书，在主密钥之外，通常还包含数个子密钥，虽然这些子密钥是可选的。

虽然子密钥的结构化属性于主密钥相同，但是它们的作用并不相同。子密钥以密码学的方式与主密钥关联。

== 身份组件

OpenPGP 证书中的身份组件用来被证书持有者（certificate holder）表明它们是由特定的身份（identity）（比如名称或电邮地址）而被认知的。

=== OpenPGP 证书中的用户 ID（User ID）

OpenPGP 证书可以包含多个 User ID。每个 User ID 通过一个身份认证与证书关联。

一个典型的 User ID 身份由一个 UTF-8 编码的一个名字和一个电邮地址组成的字符串构成。按照惯例，User ID 与 RFC2822 定义的格式一致时，称为 __name-addr__。

**分离用户 ID（split User ID）**

有一个提议中的，User ID 中的编码身份的变体被称为“分离用户 ID”。虽然并不常见，但目前并没有什么重大的技术壁垒阻止实现这个格式。

分离用户 ID 的合理理由为，姓名和邮箱地址的不同，它们代表了一个个体的身份证明的两面。分离这些元素简化了第三方验证一个身份是可以合法地与一个证书关联的流程。

考虑以下场景：一个三方确信一个个体基于电邮地址的身份（比如 `<alice@example.org>`），也有意愿认证它。但是，他们却没有足够的信息来确定基于姓名的身份验证（比如 `Alice Adams`），因此他们可能并不愿意扩展相同的认证级别。分离用户 ID 就可以通过分离这两类身份，从而分别进行验证。

=== 主用户 ID（Primary User ID）的隐藏作用

在一个证书中，一个特殊的用户 ID 会作为主用户 ID 使用。

每个用户 ID 都具有关联的偏好设置，比如偏好的加密算法。当一个证书在特定身份认证的语境下使用的时候，就会使用与那个身份组件关联的偏好设置。当一个证书在不参考特定身份的情况下使用时，会默认使用直接密钥签名（direct key signature），或者主用户 ID 的偏好设置。

在历史上，主用户 ID 是偏好设置的主存储位置，该偏好会作用于整个证书。

=== OpenPGP 中的用户属性（user attributes）

虽然用户属性类似于用户 ID，但是它们并不常见。

当前，OpenPGP 标准仅定义了一种可以存储在用户属性的格式：一个 JPEG 格式的图片。通常情况下，该图片表示密钥的拥有者，虽然它并非必须的。

== 组件的链接

要构成一个 OpenPGP 证书，独立的组件需要被证书持有者通过它们的 OpenPGP 软件关联在一起。在 OpenPGP 中，该过程称为“绑定（binding）”，比如“一个子密钥绑定至一个主密钥”中的一样。这些绑定通过密码学签名实现。

在抽象层面，证书的主密钥是作为信任的根基或“证书授权中心”存在的。它的作用是：

* 签发签名，该签名用来表达证书持有者使用特定子密钥或身份组件的意图。
* 准许其它生命周期操作，包括设置过期日期以及标记组件为无效的或“吊销的”。

使用数字签名绑定组件后，一个 OpenPGP 证书的接收者仅需要验证主密钥的真实性。通常来说，它是通过手动验证主密钥的__指纹__来完成的。一旦主密钥完成验证，用户的 OpenPGP 软件就可以自动获取其余组件的验证状态。总的来说，如果证书中的一个被主密钥签名的陈述是有效的，那么证书的组件就是有效的。

== 证书中的元数据

OpenPGP 证书，其组件密钥和身份拥有的元数据并不存储在相关组件中。相反，这些元数据存储在签名包中，而签名包是 OpenPGP 证书结构的组成部分。

密钥属性，比如能力（capabilities）（比如__签名能力__和__加密能力__）以及过期时间，就是不存储在组件密钥数据中的。这些数据该如何存储，则依赖于组件：

* **主密钥元数据** 要么定义在主密钥的直接密钥签名上（OpenPGP 第 6 版推荐的），要么与主用户 ID 关联在一起。

* **子密钥元数据** 在子密钥绑定签名中，后者将子密钥与证书链接在一起。

* **身份组件元数据** 通过认证用自签名（certifying self-signature）关联，后者将身份认证（通常以用户 ID 的形式）链接至证书。

需要指出的是，OpenPGP 证书的组件在创建后就是静态的。使用签名来存储元数据可以在不修改原始组件的情况下执行之后的修改。举例来说，证书持有者可以通过签发一个新的替代签名（superseding signature）来更新一个组件的过期时间。

=== 使用密钥标识（key flags）定义组件密钥的操作能力（operational capabilities）

每个组件密钥都具有一组“密钥标识”确定了一个密钥可以执行的操作。

通常使用的密钥标识有：

* **签发证书（certification）**：启动签发第三方证书
* **签名（signing）**：允许该密钥签名数据
* **验证（authentication）**：主要用于 SSH 验证

[NOTE]
====
每个组件密钥处理不同的操作。仅有主密钥可以签发证书，当然它也可以有额外的能力、子密钥可以用于签名、加密和验证，但它们不可以签发证书。技术上来说，一个组件密钥可以有多个能力。但是，良好的做法是为每个能力设置不同的密钥。

值得一提的是，在很多算法中，加密和签名相关的功能（比如，签发证书、签名和验证）是互斥的，因为算法仅支持两大类操作中的一种。
====

=== 算法偏好和特性标记（feature signaling）

OpenPGP 具有明显的“密码学灵活性（agility）”。它并不依赖于固定的算法集。相反，它定义了一整套密码学原语（primitives），用户可（或应用）可以以进行选择。

这种灵活性使得向标准中加入新的密码学原语更为简单，转换更加无缝。用户可以逐渐迁移至新密码学机制而不被打断。

但是，这种方法要求 OpenPGP 软件确定通信对端能够处理和希望使用的密码学机制。OpenPGP 为该目标设计了多种机制，让发送端和接收端可以协商。特别明确，OpenPGP 不是一个在线协议，因此该协商是单向的。主动的那一方解析被动一方在证书中表达出来的偏好。

OpenPGP 中的协商机制包括：

* 偏好的散列算法
* 偏好的 v1 SEIPD 对称加密
* 偏好的 AEAD 加密套件
* 偏好的子包
* 偏好的加密算法

除了这些明确表述的偏好，实现方也会通过 OpenPGP 证书具有的版本来推断通信对象的能力。

==== 用户 ID 特定的偏好

作为起始点，一个证书具有一组可以通常性使用的偏好。它们要么定义在直接密钥签名中，要么伴随在证书的主用户 ID 中。

额外的，OpenPGP 允许设置用户 ID 相关的偏好。想法是，一个用户可能想在私人电邮账户上使用与工作电邮账户不同的算法套件。这类身份认证相关的偏好可以表达在将用户 ID 绑定至证书的认证签名上。

== 吊销（Revocations）

当一个证书持有者需要无效化他们证书的特定组件，抑或是无效化整个证书，他们将通过“吊销”来实现。吊销主密钥会让整个证书失效。

值得注意的是，吊销并非让组件无效的唯一方法。其它因素，比如越过了组件的过期时间，也会导致组件失效。

== 第三方（身份）认证

自从其产生，第三方身份认证就是 OpenPGP 生态环境的基石。最开始的 PGP 设计者们，自 Phil Zimmermann 开始，就致力于创建去中心化的信任模型，而非依赖中心化认证机制。OpenPGP 中，这种去中心化的方法被称为“信任网（Web of Trust）”

第三方认证是 OpenPGP 用户的陈述，它用来确定一个具有特定身份认证的用户就是特定 OpenPGP 证书的所有者。

举例来说，Bob 的 OpenPGP 软件会签发一个证书，表明 Bob 已经确认了用户 ID `Alice Adams <alice@example.org>` 和具有指纹 `AAA1 8CBB 2546 85C5 8358 3205 63FD 37B6  7F33 00F9 FB0E C457 378C D29F 1026 98B3` 的证书具有有效的关联。

该流程假设 Bob 知道 `Alice Adams` 这个人，且确认 `alice@example.org` 是 Alice 的邮箱地址。Bob 同样确认了它的 OpenPGP 中与 Alice 关联的证书就是 Alice 在使用的证书。本质上来说，用户双方都必须拥有 Alice 的证书，且证书的指纹必须一致。OpenPGP 第 6 版不希望终端用户手动对比指纹，但替代的检验机制依旧在开发中。验证机制必须在足够安全的通道——比如端对端加密视频或面对面会议——中达成。
