= 解密

信息解密时将加密后的信息恢复为明文形式的过程。它包含多个步骤。

实现一般先处理 SEIPD 包前的 PKESK 和 SKESK 包，来确定 *ESK 包的可解密性。若 PKESK 包所包含的接收方的密钥 ID，匹配上了用户证书的一个（子）密钥，那么它就可用于解密。通常来说，SEIPD 包之前的所有 *ESK 包，在解密之后，都具有相同的__会话密钥__。

[NOTE]
====
匿名接收方（anonymous-recipient） PKESK 的接收方密钥 ID 为 `0`，若没有合适的非匿名 PKESK，那么会使用任何可用的解密（子）密钥（见 xref:73.25、进阶材料：解密.adoc#_匿名接收者[]）。
====

若没有合适的 PKESK 包，则会接着尝试 SKESK 包，意味着用户通常会被提示输入一个解密密码。

一旦上述任何一个方法成功了，则解密出的__会话密钥__会用来解密 SEIPD 包。

== 密码保护的会话密钥（SKESK）

解密 SKESK 包来恢复__会话密钥__，会基于用户提供的密码，来反向执行加密步骤。

第 4 版和第 6 版的 SKESK 包都会提示用户输入密码，输入的密码会经过 SKESK 包中描述的 S2K 函数。但是，之后的步骤会有所不同，见下。

=== SEKESK v4

S2K 函数的结果是一个对称密钥，这个密钥要么用于解密 SKESK 包中的会话密钥，或者——较少见——直接用作会话密钥（见 <<直接方法>>，direct-method）。

[NOTE]
====
“直接方法”——S2K 函数的结果直接用作会话密钥——仅在只有一个 SKESK 包时才可用。
====

在第 4 版 SKESK 包——仅和第 1 版 SEIPD 包组合使用——中，__会话密钥__直接作为__信息密钥__，没有中间的派生过程。

==== 直接方法

在第 4 版 SKESK 包中，被加密的会话密钥是可选的。若没有加密后的会话密钥，则提示使用“直接方法”，也就是输入的密码经过 S2K 函数的结果，会直接作为会话密钥/信息密钥。

当使用直接方法时，SKESK 包的对称加密算法 ID 决定了从 SEIPD 包解密出明文的加密算法。

否则，用于解密 SEIPD 包的加密算法 ID 会附加在解密后的会话密钥之前。

检查解密后的会话密钥的算法 ID 会作为非常早期的快检步骤，来确认密码是正确的。对会话密钥更进一步的检查，见<<检验会话密钥的成功解密>>。

=== SKESK v6

在第 6 版 SKESK 包中，输入的密钥经过 S2K 函数的结果将作为__初始密钥材料（initial keying material，IKM）__，使用 HKDF（一种密钥派生函数）派生出一个对称__密钥加密密钥__。HKDF 函数本身不使用任何盐，它的 __info__ 参数是从 SKESK 包的参数组合而来的。

下一步，对称密钥将使用 AEAD 解密__会话密钥__。AEAD 函数使用关联的 SEIPD v2 包的信息作为__额外数据__。该函数也会使用 SEIPD v2 的盐作为自己的盐。SKESK 包的 __AEAD Auth Tag__ 会作为鉴别标签。

其结果是__会话密钥__。

== 密钥保护的会话密钥（PKESK）

比 SKESK 包更常用的是 PKESK 包，后者使用接收者的加密密钥保护会话密钥。

=== PKESK v3

在第 3 版 PKESK 中，接收者的私有加密（子）密钥直接用于解密和加密__会话密钥__。使用的子密钥的 Key ID 会记录在 PKESK 的 key-id 字段中。值 `0` 表示一个匿名接收者（见 xref:73.25、进阶材料：解密.adoc#_匿名接收者[]）。

要检测一会儿应该使用哪种对称密钥算法解密 SEIPD v1 包，每种公钥算法使用稍微不同的编码来解包，解密后种的会话密钥种的对称算法标签。见标准的对应章节。典型的，密码算法 ID 追加在实际会话密钥之前。

==== PKESK v6

第 6 版 PKESK 包的解密流程与第 3 版类似。

与第 3 版 PKESK 不同之处在于，第 6 版 PKESK 种的加密后的会话密钥不包含用于解密 SEIPD 包的对称密码算法。密码算法 ID 是直接编码进 SEIPD v2 包中的。

== SEIPD（v1）

第 1 版 SEIPD 包必须仅与第 3 版 PKESK 包和/或第 4 版 SKESK 包结合使用。任何其它的组合是不被允许的，必须导致一个损坏的信息。

[NOTE]
====
由于 SEIPD 第 1 版在特定的情况下有受到降级攻击的风险，所以在任何可能的情况下，都建议使用 SEIPD 第 2 版。
====

要解密第 1 版 SEIPD 包的内容，会使用前序步骤得到的会话密钥。密码算法要么提取自解密后的会话密钥（算法 ID 一般追加在解密后的会话密钥之前），或者——在 SKESK 包的直接方法中——使用 SKESK 密码算法字段。

一旦密码算法初始化完成，SEIPD 包的整个加密后数据会被解密。

=== 检验快检字节

要快速检验解密过程中使用了正确的会话密钥，第 14 和 15 索引号上的字节会与第 16 和 17 索引号上的字节做对比（索引以 0 开始）。若这两对字节不匹配，则表示使用了错误的会话密钥，解密过程将放弃。

=== 检验篡改检测码（mdc）

SEIPDv1 包的内容通过额外的篡改检测码来对抗未被发现的篡改。它是通过计算，除了最后 20 个字节（这些字节是发送者实际计算的校验和）外的，整个解密后的明文的 SHA1 校验和。

得到的结果会与最后那 20 个字节比较，来检测密文的篡改。

== 具有 AEAD 的 SEIPD（v2）

首选模式。第 2 版 SEIPD 包**必须**仅与第 6 版 PKESK 包和/或第 6 版 SKESK 包组合使用。任何其它的组合都是不被允许的，会导致一个损坏的信息。

一旦会话密钥从 PKESK 或 SKESK 中获取到了，它将用于派生一个__信息密钥（message key）__和一个 IV。派生过程则是将会话密钥传递给一个加了盐的 HKDF 函数，盐本身则是每信息独有的，需要从 SEIPD 包中获取。

其结果会分解为信息密钥和 IV 的前半部分。

之后 SEIPD 加密后数据的内容会被分块，并按序逐个处理。每块会使用 AEAD 解密，后者会使用 SEIPD 包的参数作为__额外数据__。对于每个数据块，从 0 开始的数据块索引将作为 IV 的后半部分传入函数。

所有解密的明文块会不断向后追加，构成解密过程的结果。

当所有块都处理结束，在最后的 AEAD 步骤中，明文的字节总计数会追加至__额外数据__中，SEIPD 包的最后的 AEAD auth tag 会被处理。

== SED

SEIPD 包之前是对称加密数据（Symmetrically Encrypted Data， SED）包，后者目前已经弃用了。由于缺少完整性保护，该包受到一大类攻击者修改密文的攻击的影响。因此，实现禁止产生这类包，并鼓励不接受来自不可信源的 SED 包。
