= 进阶材料：证书

== 何时证书是有效的？

证书是由被签名链接在一起的组件构成的。

一个证书可以作为一个整体有效或无效化。但是，即便一个证书是有效的，其中独立的组件（子密钥或身份认证）也可以是无效的。

在本章节中，我们将讨论证书和其组件的有效性。本讨论与签名的有效性紧密关联，并建立在后者之上。

关联一个证书的签名的自身的有效性是必须的预备条件。有两个概念紧密关系到证书和组件的有效性：

* 过期
* 吊销

=== 过期

证书和组件是可以“过期的”，过期会导致它们无效化。证书了每个组件都可以有一个过期时间，或者也可以在时间有效性上保持永久有效。

发送方的 OpenPGP 软件会拒绝使用过期的证书加密电邮，也会拒绝使用过期的加密用组件密钥。发件人的软件会拒绝使用加密密钥，这主要是出于对证书所有者的礼貌，尊重他们在证书元数据中表达的偏好。

OpenPGP 中的过期机制，具有一个扩展/更新过期时间的机制作为补充。

使用过期机制有两个有用的理由：

* 一个过期的证书意味着该证书不可以继续使用。它强制让使用该证书的用户（或它们的 OpenPGP 软件）拉取该证书的更新。比如，从一个密钥服务器拉取更新。
* 这是一种被动的让证书“无效”的方法，比如，当它们的所有者无法再控制它们，或者因为任何原因无法广播一个吊销的时候。

组件密钥使用__密钥过期时间__子包来表达过期时间。身份组件依赖其绑定签名的__签名过期时间__子包。若绑定签名过期，则绑定无效化，而组件也被认为是过期了。

=== 吊销

由于 OpenPGP 证书是“仅追加”数据结构，现有的组件或签名不可以简单地“移除”。相反，它们可以被签发的吊销签名标记为无效。这些追加的吊销签名会添加至证书中。

每个组件，比如用户 ID 和子密钥，可以被单独吊销而不影响证书的其余部分。

__主用户 ID__是一个特例：当它被吊销时，整个证书都被认为是无效的。

通过__密钥吊销签名__（类型 ID `0x20`）吊销主密钥，会将整个证书，包含它所有的组件，标记为无效和无法使用的。

=== 吊销的语义（semantics）

与过期不同，吊销通常是最终的、无法撤销的。

一个吊销意味着组件不应该被使用。组件上的吊销签名使用一个__吊销理由__子包来进一步指出组件和证书的吊销的原因。OpenPGP 格式定义了一系列不同的__吊销原因的值__，并额外提供了一个人类可读的自由文本字段，来注解吊销。

一些库，例如 Sequoia PGP，向用户公开了这些不同的原因，使撤销者能够提供细致的机器可读的语句。其它实现主要集中于区分“硬”和“软”吊销。

就定义的吊销类型，__密钥被废止（superseded）__、__密钥已退位（retired）__以及__用户 ID 不再有效（valid）__被认为是“软”吊销。任何其它的理由（包括没有__吊销理由__子包）被认为是“硬”吊销。

软吊销和硬吊销，在特定的参考时间上评估组件和签名的有效性时，有着截然不同的作用：硬吊销有不受限制的时间有效性，它们甚至在它们自身创建的时间点之前都起效，因此会在整个时间上无效化被吊销的组件或签名。

反过来说，软吊销让被吊销的组件或签名，在吊销钱签名创建时间点之前，保持有效。一个软吊销在技术上是可以——比如说，通过一个新的绑定签名——被覆盖的（新的绑定签名和它的元数据将遮蔽吊销，并重连和再次有效化组件）。

硬吊销处理这些问题：若私钥泄露，那么攻击者就可以使用这个密钥签发证书。也就是说，攻击者可以签发一个在吊销时间之前的签名，来冒充密钥的持有者。若密钥是软吊销的，该签名的接收者会错误地认为冒充的签名是有效的。要处理这个问题，有理由明确将泄露的密钥标记为在任何时候都是可疑的。这就是硬吊销的作用。

另一边，若子密钥通过软吊销温和地退位，而证书的持有者转义至另一个子密钥，那么在密钥退位之前创建的签名，依旧是有效的。

== 证书实际上是仅追加数据结构

OpenPGP 证书实际上是__仅追加数据结构__。一旦发表，于证书关联的包是不可以“撤回”的。第三方（比如其它用户，或密钥服务器）可能会保存和/或分发这些包的拷贝。

一旦这些元素公开与一个 OpenPGP 证书关联，即使我们不能__移除__这些元素，我们依旧可以向证书中添加新的元数据将其无效化。新的元数据可以为组件设置__过期时间__，或明确__吊销__这个组件。无论是哪者，我们没有从证书中移除任何包。

无效化在语义上构成了组件的移除。组件不再是证书的有效元素，至少是从某个时间点开始。即便无效组件出现，处理证书的实现也可能直接忽略它们。

我们需要区分证书的“包级别”信息以及应用级别视角下的证书。它们两者可能不同。

=== 分发系统中，仅追加属性的原由

OpenPGP 去中心的和分布式的系统。用户可以使用各种机制持有或传送他们自己的证书信息，以及其它用户的证书。这些机制包括密钥服务器、手动处理、网络密钥目录（Web Key Directory, WKD）以及 Autocrypt。

随着时间的前进，不同用户的 OpenPGP 软件可能持有相同证书的不同“视角”（view）。每个用户的 OpenPGP 实例都需要调和和存储它们从不同来源获取的元素，并将它们合并起来。

实际上，这意味着不同的 OpenPGP 用户对任何给定的证书可能会有不同的视角。出于各种原因，并非所有的用户都能持有最新的、完整的版本的证书。

这个现实关联了一系列潜在的问题：用户可能无法知晓一个组件已被证书持有者无效化。吊销可能还没有传递至部分第三方。举例来说，它们可能不知道证书持有者已经轮转了它们的加密子密钥至新的一个，并且不想再接收使用先前的加密用子密钥加密的信息。

处理部分问题的一个机制是__过期__：通过让它们的证书在一定时间之后过期，证书持有者可以强制他们的通信伙伴刷新它们的证书，比如从密钥服务器上。

一个优秀的实践，比如设置了合适的过期时间，可以缓解证书的固有的分布特性的复杂度。

但是，这种缓解在理论上，不能应对所有可能的过期证书的情况，特别是在 OpenPGP 这种去中心化的、异步的系统中。所以，在处理由于不同用户具有一个证书的不同视角的时候，采取防御性措施通常是合理的。

当我们思考边界情况时，常常需要“假设最差情况”。举例来说：

* 接收者可能无法定期获取证书的更新（它可能出于各种原因，包含但不限于，被恶意用户干扰）。
* 证书关联的数据过于复杂，导致证书可能并不便于处理，即便是执行一些常规的操作（举例来说，一个证书可能接受了非常非常多有效的第三方证书）。若这类问题出现，那么理论上，证书持有者无法处理它：注意证书持有者不能“撤回”现有的包。

=== 一个证书会有不同的“视角”

从另一个角度来说，不用的 OpenPGP 用户对任何证书都可能有不同的视角。名义上会有一个“官方”版本的证书，但我们不能确认每个用户都准确具有它的拷贝。除了证书持有者关联的证书的传播问题，第三方证书在设计上就是一个分发系统。一个第三方证书由第三方签发，它可能有也可能没有被广泛地分发。在部分情况下，不广泛分发第三方证书是完全合理的。

通常来说，OpenPGP 用户总是希望获取他们交互的证书的最完整的版本。

但是，也有尽量使用一个证书的尽量少的元素的子集。我们将在<<证书最小化>>章节讨论它。

== 合并

如上所述，OpenPGP 证书实际上是仅添加数据结构。作为该事实的实现，OpenPGP 软件需要__合并__一个证书的不同拷贝。

举例来说，Bob 的 OpenPGP 软件可能在本地有一份 Alice 证书的拷贝，同时又从密钥服务器上取得了 Alice 的一份不同版本的证书。实现的目标则是将任何 Alice 证书的新信息添加至本地拷贝中。Alice 可能添加了新的身份认证，用新的子密钥替换了旧的，或者吊销了她证书中的部分组件。或者，Alice 也可能吊销了她的证书，表明她不再想让通信同伴使用这个证书。所有这些更新对 Bob 来说都是至关重要的。

合并两个版本的证书包含了应该保留哪些包的决策。不同版本的证书通常包含一些完全相同的包。合并后版本的包中不应该含有完全相同的包的多个拷贝。额外的，若新获取的拷贝包含了与证书完全无关的包，那么这些部分也不应该被保留（第三方可能会加入无关的包，可能是失误了，也可能是恶意的）。

=== 处理未验证的信息

至于哪些__的确__与证书关联，但并未通过自签名绑定的信息，没用通常意义上的正确做法。接收端实现必须解决这些情况，可能是在一个上下文特定的情况下。这类情况包含：

* 第三方证书。这些可能是很有价值的信息，此时第三方证明一个身份认证和证书的关联是有效的。另一方面，它们也可能是一种垃圾信息。
* 签名包的非散列部分中的子包。再次，它们可能包含对接收者来说有用的信息。但是，这些信息可能是无效的，甚至是错误的/有害的。
