= 进阶材料：私钥

== 私钥存储

本节考察 OpenPGP 中私钥存储的不同架构和操作机制。我们聚焦于各种设计选择，它们功能的作用，以及它们是如何安全管理私钥材料。

=== 设计变种

OpenPGP 框架中的私钥子系统的设计有多种，提供了密码学操作的不同实现方法：

. **分离后端操作**：有些设计在不同的后端中执行主要密码学操作，仅使用密码学密钥材料。这种方法特别容易兼容通用的硬件密码学设备，比如可信平台模块（TPM）。

. **基于模块密钥的系统**：一个 OpenPGP 私钥子系统可能围绕着组件密钥，特别是密钥子包的内容进行构建。这些包包含了某些特定的操作需要的元数据。比如，ECDH 操作，就需要元数据作为 KDF 参数。

. **完整可转移密钥**（**full transferable secret keys**）：一些设计会在密钥子系统中保留完整的 TSK 拷贝，以方便私钥操作。

虽然密钥存储操作需要组件密钥，但它们不需要访问整个 OpenPGP 证书。


[NOTE]
====
第三个设计，需要在私钥子系统中存储完整的 TSK，可能会导致“神经分裂（split brain）”问题。

举例来说，一个私钥存储可能会包含一个具有过期证书元数据的 TSK，将整个证书标记为过期的，而本地公钥存储中的更新版本会指向一个延期了的过期时间。

这个问题在 GnuPG 1.x 中表现得较为明显，其它在私密存储组件中存放独立 TSK 拷贝。类似地，Thunderbird 的 OpenPGP 子系统的当前设计也会导致用户面临这种问题。
====

=== 两级（two-tier）架构

从核心上说，OpenPGP 私钥子系统执行的操作仅需私钥密码写密钥材料，正如上方“分离后端操作”模型描述的。

但是，子系统同样支持那些需要额外访问组件密钥的元数据的操作。这些补充了核心密钥存储操作的操作，不涉及私钥材料。

当实现一个基于如 OpenPGP 卡的硬件密码学设备的密钥存储，它的设计就会包含两层：

* **核心层**：直接处理私钥材料，以及
* **补充层**：执行那些不需要直接使用密钥材料的，额外的密码学操作，比如 ECDH 的 AES key wrap。

[NOTE]
====
使用 ECC 算法的解密过程，特别是 ECDH，具有多个步骤。初始步骤，可能会被类似于 OpenPGP 卡的设备执行，直接使用密钥材料来生成一个“分享的机密（shared secret）”。在此之后，如“AES key wrap”的操作在硬件设备之外的软件中进行操作。

该过程的更多细节见“Advanced Encryption Standard (AES) Key Wrap Algorithm”RFC 3394。
====

=== 定位不同的密钥

私钥存储的一个关键部分就是确定用户该如何定位不同的密钥。

一个通用的做法是使用每个组件密钥的指纹。这些指纹的可用性，却依赖于密钥存储的底层技术。比如，在基于软件的私钥存储或 OpenPGP 卡中，组件密钥的指纹通常是即刻可用的。依赖通用密码学硬件（比如 TPM）的密钥存储，需要实现它们自己的对每个密钥进行追踪和管理的机制。

=== 密钥存储的额外职责

除了密钥管理，一个密钥存储通常还需要一系列的补充功能：

* **跟踪设备**：密钥存储可能需要跟踪哪个设备包含特定的组件密钥。

* **处理机密**：这包含管理敏感信息，比如软件密钥的密码，或者 OpenPGP 卡的 PIN。

* **用户交互警告**：密钥存储也可能需要在特定操作中提示用户进行必要的交互。比如，OpenPGP 卡可能要求用户触摸以确认授权每个密码学动作。
