= 加密

:crypto-refresh-12_url: https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html
:加密_url: {crypto-refresh-12_url}#name-confidentiality-via-encrypt
:加密机制总览_url: {crypto-refresh-12_url}#section-10.3.2.1
:经公钥加密的会话密钥_url: {crypto-refresh-12_url}#name-public-key-encrypted-sessio
:经对称密钥加密的会话密钥_url: {crypto-refresh-12_url}#skesk
:经对称加密的完整性保护数据_url: {crypto-refresh-12_url}#name-symmetrically-encrypted-int
:对称加密数据包_url: {crypto-refresh-12_url}#name-symmetrically-encrypted-dat
:openpgp_报文_url: {crypto-refresh-12_url}#name-openpgp-messages
:第_1_版_seipd_url: {crypto-refresh-12_url}#version-one-seipd
:第_2_版_seipd_url: {crypto-refresh-12_url}#version-two-seipd
:第_3_版_pkesk_url: {crypto-refresh-12_url}#v3-pkesk
:第_4_版_pkesk_url: {crypto-refresh-12_url}#v4-skesk
:第_6_版_pkesk_url: {crypto-refresh-12_url}#v6-pkesk
:第_6_版_skesk_url: {crypto-refresh-12_url}#v6-skesk

link:{加密_url}[加密]是 OpenPGP 的核心功能之一。它提供了机密性。

OpenPGP 中加密数据的更深入的、包级别的理解，见xref:抽丝剥茧：加密数据的包结构[]。

== 术语

[cols="1,5"]
|===
| 术语 | 描述

| SEIPD 包
| __经对称加密的、完整性受保护的数据（Symmetrically Encrypted, Integrity Protected Data）__包，包含加密后的信息载荷

| SKESK 包
| __经对称密钥加密的会话密钥（Symmetric-Key Encrypted Session Key）__包，包含了或提供了密码加密的会话密钥

| PKESK 包
| __经公钥加密的会话密钥（Public-Key Encrypted Session Key）__包，包含了使用非对称公钥加密了的会话密钥

| 会话密钥（session key）
| 对称加密密钥，要么作为信息密钥直接使用，要么从前者派生出后者。

| 信息密钥
| 用来加密 SEIPD 包的数据的对称加密密钥
|===

== 信息加密流程概述

OpenPGP 中的加密分为两个不同的步骤：

. **对称加密**：明文基于一个（秘密的）对称密钥——link:{加密_url}[__会话密钥__]——进行加密。即便生成的（可能更大）的密文需要发给多个接收者，密文也仅需要被存储一次。所有接收者使用相同的共享的__会话密钥__来解密信息。

. **会话密钥传输**：对于信息的每个接收者，会生成一个包含了保护后的会话密钥的副本的包。
** 通常，__会话密钥__会通过接收者的公共加密组件密钥进行加密。
** 或者——或额外地——__会话密钥__可以被一个密码加密。这是特定的、少见的操作模式，它不需要 OpenPGP 证书。

[NOTE]
====
上文中，“明文”是下列含义之一：

* __字面量数据（Literal Data）__包，
* __压缩后数据（Compressed Data）__包或
* __已签名报文__。

一个 __已签名报文__，则表示一个包序列，符合下面两种描述之一：

* 可组装为一个 __内联签名报文__（夹在一个或多个__一次性签名__和各自__签名包__之间的__字面量数据__包），或者
* 一个 __前缀签名（prefixed-signed）__报文（一个或多个__签名__包，之后跟随一个__字面量数据__包）
====

== 加密机制的版本

OpenPGP 的加密机制一直在演变。RFC 展示了link:{加密机制总览_url}[加密机制的总览]，以及他们可以如何被组合起来。

当前，OpenPGP 中存在两代加密机制，而且在可见的未来它们都会同时存在。

两种机制的主要不同在于其中对称加密的不同，使用__经对称加密的、完整性受保护的数据__包（简称“SEIPD”）的版本 1 和版本 2 表示。这两个版本使用不同的机制来保证不可篡改性（non-malleability），见下方详述。

OpenPGP 中存在旧的过时的加密机制。但是，这些机制禁止再用作加密手段。使用过时机制加密的信息依旧可以被解密，但是必须要小心。要了解更多，参阅xref:73.11、解密.adoc[解密]章节。

SEIPD 包使用两种机制的组合来存储__会话密钥__：

* link:{经公钥加密的会话密钥_url}[经公钥加密的会话密钥]（PKESK）包，和
* link:{经对称密钥加密的会话密钥_url}[经对称密钥加密的会话密钥]（SKESK）包

OpenPGP 中常见的用于加密的机制的组合是xref:73.03、密码学概念和术语.adoc#_混合密码系统[混合加密系统]，包含一个或多个link:{经公钥加密的会话密钥_url}[经公钥加密的会话密钥]（PKESK）包，之后是一个link:{经对称加密的完整性保护数据_url}[经对称加密的完整性保护数据]（SEIPD）包。

在这个组合中，非对称密码学机制用于加密 PKESK 包中的__会话密钥__。__会话密钥__则用于在 SEIPD 数据包中使用对称密钥加密保护明文。

== 经过加密的会话密钥：PKESK、SKESK

经加密的会话密钥（ESK）包，是两类用于加密对称密钥的机制：

* link:{经公钥加密的会话密钥_url}[PKESK]：使用非对称 OpenPGP 密钥来保护一个会话密钥，以及
* link:{经对称密钥加密的会话密钥_url}[SKESK]：使用密码来保护对称密钥（这一种比较不常见）

在同一个信息中可以使用任意数量的 PKESK 和 SKESK。也可以混用两者，生成的信息可以被任何一个目标 OpenPGP 密钥、或者密钥解密。这样就可以让多个已知的收件人获取信息，而且也可以让之后的接收者提供密码。

=== PKESK：使用非对称 OpenPGP 密钥加密的会话密钥

要为一个接收者加密一个 OpenPGP 信息，会话密钥会使用接收者的公钥加密。生成的经加密会话密钥会被打包为 PKESK 包，其中包含了必要的元数据，比如接收者的加密（子）密钥的 ID。

该过程为每个信息接收者重复，所有生成的 PKESK 包都追加在 SEIPD 包（见下）之前，而后者则包含实际的信息。

通常情况下，发送者也会将他们自己设置为一个接收者，这样他们就可以在之后使用他们自己的密钥解密信息了。

=== PKESK：使用密码加密会话密钥

作为一个替代（或补充增强）PKESK 包的方案，一个信息也可以被对称密码加密。这由 SKESK 包完成，其使用 S2K 机制从密码中派生出对称密钥。这个密钥要么直接作为会话密钥，或者更常见的，作为密钥封装密钥（key-encapsulation-key, KEK）来加密会话密钥。

参见 https://flowcrypt.com/docs/guide/send-and-receive/send-password-protected-emails.html

作为密钥的保护机制，在生成 SKESK 包时，选择正确的 S2K 参数十分重要。规范当前建议使用 __Iterated and Salted S2K__ 或 __Argon2__。

== 数据的对称加密，SEIPD

经对称加密的、完整性受保护的数据（SEIPD）__代表了 OpenPGP 加密机制的对称的部分。这些包的功能与（非对称）OpenPGP 密钥完全独立。

SEIPD 包包含了实际的载荷：信息加密后的密文。对于较大的被加密信息，SEIPD 包也会更大。

[NOTE]
====
SEIPD 包是link:{对称加密数据包_url}[对称加密数据包（Symmetrically Encrypted Data）]的继任者，而后者则已经弃用。
====

（规范）定义了两个版本的 SEIPD 包（其通过版本号区分）。版本 1，在 RFC4880 中提出，应用于 OpenPGP v4；而 SEIPD 版本 2 则在 OpenPGP v6 中被引入。两个版本都可以用于 OpenPGP v4 或 v6 密钥，虽然 OpenPGP v4 密钥必须在 __特性（Feature）__签名子包中声明支持 SEIPD 版本 2。

在解密后，SEIPD 包中包含的数据将组成一个 link:{openpgp_报文_url}[OpenPGP 报文]。也就是说，解密后的数据包含一系列 OpenPGP 包。

在两个版本的 SEIPD 中，解密器在处理 SEIPD 包之前，都必须从之前的步骤中取得__会话密钥__。使用该会话密钥，解密器可以解密 SEIPD 包，并处理其中含有的明文。

=== v1 SEIPD，基于 MDC

link:{第_1_版_seipd_url}[第 1 版 SEIPD] 机制被所有现代的 OpenPGP 第 4 版的实现所支持。它在 link:https://www.rfc-editor.org/rfc/rfc4880.html#section-5.13[RFC 4880] 中介绍，并替换 __SED（对称加密数据）__包。SEIPD v1 使用对明文的 SHA-1 校验和，作为密文的篡改检测码（modification detection code），来实现完整性保护。

第 1 版 SEIPD 仅能与link:{第_3_版_pkesk_url}[第 3 版 PKESK] 和/或link:{第_4_版_pkesk_url}[第 4 版 SKESK] 包结合。

在这版 SEIPD 包中，会话密钥是直接作为信息密钥使用的，也就是说载荷是直接使用会话密钥加密的。

当与多个收件人通信时，但凡其中一些收件人的 OpenPGP 软件只支持 OpenPGP 版本 4，那么就必须使用这种机制。

==== 为明文准备快检和篡改检测码

在加密明文之前，数据会在前方添加“快检（quick check）”，并在后面追加篡改检测码。

快检由 16 个随机挑选的字节，以及重复一次前者的最后两个字节构成（共 18 字节）。这个机制用于快速检测是否使用了正确的会话密钥解密信息。这些快检字符会附加在明文前。

另一边，添加篡改检测码则用来检测对密文的篡改。标记字节 `0xD3` 和 `0x14`附加在明文后。然后，会计算包含了快检和明文以及尾部标记字节在内的数据的 SHA1 校验和，并将校验和附加在标记字节之后。

最后，整个修改过后的明文会被对称加密。

=== v2 SEIPD，基于 AEAD

link:{第_2_版_seipd_url}[第 2 版 SEIPD] 机制在 OpenPGP 第 6 版中引入。因此，只有所有的接收者，都明确使用__特性__签名子包，声明支持这个机制，才可以使用这个加密方法。他使用__AEAD（附加数据的认证加密 authenticated encryption with additional data）__来提供对密文的完整性保护。

v2 SEIPD 仅可以与link:{第_6_版_pkesk_url}[第 6 版 PKESK] 和/或link:{第_6_版_skesk_url}[第 6 版 SKESK] 包组合。

在第 2 版 SEIPD 中，__会话密钥__会转基于，一个单独存储在 v2 SEIPD 包中的、每信息（不同的）盐值（salt value），换为__信息密钥__。之后信息密钥会用在一个 AEAD 方案中加密信息载荷。

[NOTE]
====
会话密钥和信息密钥可以使用不同的对称算法。
====

这个额外的步骤在协议中引入了密钥分离（key-separation），对抗了特定的攻击，比如一个 link:https://www.metzdowd.com/pipermail/cryptography/2015-October/026685.html[OpenPGP SEIP 降级攻击]。
