= 进阶材料：证书

== 何时证书是有效的？

证书是由被签名链接在一起的组件构成的。

一个证书可以作为一个整体有效或无效化。但是，即便一个证书是有效的，其中独立的组件（子密钥或身份认证）也可以是无效的。

在本章节中，我们将讨论证书和其组件的有效性。本讨论与签名的有效性紧密关联，并建立在后者之上。

关联一个证书的签名的自身的有效性是必须的预备条件。有两个概念紧密关系到证书和组件的有效性：

* 过期
* 吊销

=== 过期

证书和组件是可以“过期的”，过期会导致它们无效化。证书了每个组件都可以有一个过期时间，或者也可以在时间有效性上保持永久有效。

发送方的 OpenPGP 软件会拒绝使用过期的证书加密电邮，也会拒绝使用过期的加密用组件密钥。发件人的软件会拒绝使用加密密钥，这主要是出于对证书所有者的礼貌，尊重他们在证书元数据中表达的偏好。

OpenPGP 中的过期机制，具有一个扩展/更新过期时间的机制作为补充。

使用过期机制有两个有用的理由：

* 一个过期的证书意味着该证书不可以继续使用。它强制让使用该证书的用户（或它们的 OpenPGP 软件）拉取该证书的更新。比如，从一个密钥服务器拉取更新。
* 这是一种被动的让证书“无效”的方法，比如，当它们的所有者无法再控制它们，或者因为任何原因无法广播一个吊销的时候。

组件密钥使用__密钥过期时间__子包来表达过期时间。身份组件依赖其绑定签名的__签名过期时间__子包。若绑定签名过期，则绑定无效化，而组件也被认为是过期了。

=== 吊销

由于 OpenPGP 证书是“仅追加”数据结构，现有的组件或签名不可以简单地“移除”。相反，它们可以被签发的吊销签名标记为无效。这些追加的吊销签名会添加至证书中。

每个组件，比如用户 ID 和子密钥，可以被单独吊销而不影响证书的其余部分。

__主用户 ID__是一个特例：当它被吊销时，整个证书都被认为是无效的。

通过__密钥吊销签名__（类型 ID `0x20`）吊销主密钥，会将整个证书，包含它所有的组件，标记为无效和无法使用的。

=== 吊销的语义（semantics）

与过期不同，吊销通常是最终的、无法撤销的。

一个吊销意味着组件不应该被使用。组件上的吊销签名使用一个__吊销理由__子包来进一步指出组件和证书的吊销的原因。OpenPGP 格式定义了一系列不同的__吊销原因的值__，并额外提供了一个人类可读的自由文本字段，来注解吊销。

一些库，例如 Sequoia PGP，向用户公开了这些不同的原因，使撤销者能够提供细致的机器可读的语句。其它实现主要集中于区分“硬”和“软”吊销。

就定义的吊销类型，__密钥被废止（superseded）__、__密钥已退位（retired）__以及__用户 ID 不再有效（valid）__被认为是“软”吊销。任何其它的理由（包括没有__吊销理由__子包）被认为是“硬”吊销。

软吊销和硬吊销，在特定的参考时间上评估组件和签名的有效性时，有着截然不同的作用：硬吊销有不受限制的时间有效性，它们甚至在它们自身创建的时间点之前都起效，因此会在整个时间上无效化被吊销的组件或签名。

反过来说，软吊销让被吊销的组件或签名，在吊销钱签名创建时间点之前，保持有效。一个软吊销在技术上是可以——比如说，通过一个新的绑定签名——被覆盖的（新的绑定签名和它的元数据将遮蔽吊销，并重连和再次有效化组件）。

硬吊销处理这些问题：若私钥泄露，那么攻击者就可以使用这个密钥签发证书。也就是说，攻击者可以签发一个在吊销时间之前的签名，来冒充密钥的持有者。若密钥是软吊销的，该签名的接收者会错误地认为冒充的签名是有效的。要处理这个问题，有理由明确将泄露的密钥标记为在任何时候都是可疑的。这就是硬吊销的作用。

另一边，若子密钥通过软吊销温和地退位，而证书的持有者转义至另一个子密钥，那么在密钥退位之前创建的签名，依旧是有效的。
