= 从 OpenPGP v4 迁移到 OpenPGP v6

OpenPGP 协议在持续开发，并将一直如此，以面对新的挑战和需求。

有一些修改可能很细微，比如添加新的散列算法，而另一些则更有侵略性，比如新的 OpenPGP 密钥格式。

因此，有必要迁移实现、以及现有的用户密钥和证书。

本章，我们将探索从 RFC4880 定义的 OpenPGP v4 迁移至 v6（密码学更新）的可能步骤。

== 接受新特性

新标准介绍了一系列新特性，其增强了协议的安全性。有些特性仅能在 OpenPGP 第 6 版密钥中使用，并要求用户迁移至全新的密钥。

其它特性可以用在现有的 OpenPGP 第 4 版中，一旦实现支持了这些特性，用户的证书折射出了用户软件支持的特性。

=== SEIPD v2

新引进的可以被用在现有的 v4 密钥的一个完美的例子，就是新的 SEIPD v2 包。

现有的 OpenPGP v4 密钥可以通过证书中的一个 __特性（Feature）__子包简单地宣称支持 SEIPD v2。通过证书公开这类更新后的__特性__集，表明用户的 OpenPGP 软件可以处理 SEIPD v2。

可以产生这类新加密模式的发送者，就可以在加密至该接收者时使用它。

=== S2K 用法模式 AEAD

另一个不错案例是私钥加密的 S2K 机制。

这个特性关心每个用户机器上的 OpenPGP 私钥的本地拷贝。也就是说，从定义上，该特性无需考虑交互性：私钥材料的密码保护是每个用户机器上的本地实现细节。

RFC 表明：“**推荐**用户迁移至 AEAD。”

在本章的语境下，它表示加密后的私钥应该由用户的 OpenPGP 软件升级使用 S2K 用法模式 253（AEAD）来加密用户的私钥材料。

注意 S2K 用法模式 253（AEAD）可以用于版本 6 和版本 4 的私钥，只要 OpenPGP 软件足够新。推荐所有版本的私钥都使用该 S2K 用法模式。

==== S2K 方法 Argon2

独立地，RFC 建议，当可用时，使用 Argon2 S2K 方法来散列密码。该机制同样考虑了私钥材料的本地密码保护。

Argon2 仅能与 AEAD 结合使用。

用户可以且应该将他们的私钥保护迁移至 Argon2（结合 AEAD 用法模式）。

=== OpenPGP v6 签名

第 6 版签名不可以由 OpenPGP v4 密钥生成。仅有 OpenPGP v6 密钥可以签发 v6 签名。

在接收侧/检验侧，v6 签名可以被任何支持 v6 证书以及 v6 签名检验的 OpenPGP 软件检测。这包括那些当前使用 v4 密钥的 OpenPGP 用户。

=== 软件迁移

随着时间的推移，会有越来越多的 OpenPGP 库和工具支持 OpenPGP v6 特性。实现们需要花些时间来迁移。

OpenPGP v6 标准为库作者写了份让 OpenPGP 实现支持第 6 版的指导，在 Appendix B. Upgrade Guidance 中。

== 密钥迁移

有些 OpenPGP v6 特性仅在使用 v6 格式的密钥时才可用。

举例来说，仅有一个 OpenPGP v6 密钥可以签发 v6 签名。

另一方面，OpenPGP v6 密钥__仅能__签发 v6 签名，所以若你需要兼容 v4 验证者，则你还不应该迁移至 v6 密钥/证书。

当迁移至一个 v6 密钥时，生成一个全新的 v6 密钥是推荐的方式。

不可能将 v4 子密钥直接嵌入 v6 密钥中，因为 v6 主密钥的所有子密钥也必须是 v6 子密钥，见 OpenPGP v6 证书结构。

=== 将 v4 组件密钥转换至 v6 组件密钥

也就是说，将现有的 v4 组件密钥中的密钥材料，转换为 v6 组件密钥，以用在 OpenPGP 第 6 版证书中。

====
**简而言之：**

别这么做。
====

==== 转换的动机

将现有的密钥转换为 v6 格式可能是很吸引人的。不过这种步骤应该非常小心地考虑。

非常不幸，密钥不可能简单地转换为新格式，并无缝地使用。比如说，具有相同密钥材料的第 4 版和第 6 版组件密钥的指纹是不同的（同理，密钥 ID 也不同，因为后者是指纹的短版本）。

一个 OpenPGP v4 指纹来自自归一化（normalized）的公钥包的 SHA-1 校验和，它是一个 20 字节的指纹（通常表示为 40 个十六进制字符）。v4 密钥 ID 包含该指纹的__最后__ 64 位。

另一边，v6 指纹来自归一化的公钥密钥包的 SHA-256 校验和，它包含 32 字节。v6 密钥 ID 由指纹的__前__ 64 位。

结果就是，OpenPGP 产物中的组件密钥身份认证——比如签名中的签发者子包，或者 PKESK 包中的接收者密钥 ID——即便使用相同的密钥材料，由 v4 签发的和 v6 签发的也不同。

更近一步，v6 密钥仅可以签发 v6 签名，v6 证书也只能用于验证 v6 签名。否则，就可能存在降级向量，从而诱使验证者针对 OpenPGP v6 证书验证特制的 v4 签名。如果 OpenPGP v4 在某个时候出现漏洞，而后者允许攻击者伪造有效的 v4 签名，这就可能会影响 OpenPGP v6 证书。

==== 保持解密旧信息的能力

另一个转换旧密钥材料的动机可能是解密由旧密钥加密的信息。这并非开箱即得的，因为对应的 PKESK 包的密钥 ID 不再匹配转换后的密钥。因此，至少，用户的实现必须要能映射密钥 ID。当然它并非流行的功能。

另一个替代方案——不要求用户的 OpenPGP 软件的特殊处理——是替换信息的 PKESK 头部。每个信息的会话密钥都可以简单地使用旧密钥解密信息得到，而会话密钥则依照转换后的 v6 密钥，或者全新生成的 v6 密钥加密。这个新的 PKESK 包可以添加或替换至信息中。

==== 总结

总结，将 v4 密钥材料转换为 v6 来验证旧签名并非一个很强的理由。使用转换后的密钥读取旧信息实际上也不现实，因为简单的方法是用新的 v6 密钥重新创建一个新的 PKESK 头部。
