= 进阶材料：数据签名

:crypto-refresh-12_url: https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html

== 内联已签名报文的内部

内联已签名报文是 xref:73.07、对数据签名.adoc#_openpgp_数据签名的形式[OpenPGP 数据签名]的一种形式。一个内联已签名报文将已签名的数据和其对应的数据签名结合为单一的 OpenPGP 报文。

OpenPGP 定义了两种内联已签名报文的形式：

. **单程式已签名报文**（**one-pass signed message**）：它是内联签名报文常用的格式。一个签名者和一个验证者可以单程式地验证该格式。
. **前缀式已签名报文**（**prefixed signed message**）：该格式在单程式已签名格式之前，它在概念上更简单一些。但是，它已经很少使用，并可以被认为是过时格式。

=== 单程式已签名报文

这是常用的内联已签名报文的格式。

==== 结构

一个单程式已签名 OpenPGP 报文由三段组成：

. **单程式签名包**：一个或多个在已签名数据之前的包，并允许（在创建时的和验证时的）签名计算一次性完成。
. **OpenPGP 报文**：包含原始数据载荷（比如报文的正文），其被签名而不需要额外的解释或转换。在内部，一个已签名link:{crypto-refresh-12_url}#name-openpgp-messages[报文]包含一个或多个 OpenPGP 包。该载荷通常使用字面量数据包（Literal Data Packet）或压缩数据包（Compressed Data Packet）存储。
. **数据签名包**：它们包含了已签名的数据的密码学签名。

[NOTE]
====
即便名字中有“签名”二字，单程式签名包并非签名包的一个类型。

相反，它是一种辅助包，与签名包结合之后，可高效地生成和检查内联已签名报文。

单程式签名包的结构紧密镜像 OpenPGP 签名包。但它不包含密码学签名。
====

==== 单程式签名包的功能

该包的目的是高效地以__流式__模式处理内联已签名报文。该特性在已签名报文巨大、超过了可用内存的时候非常有用。

如果没有这个数据包，签名数据包在内联已签名 OpenPGP 报文中的位置就需要权衡：

* 一个已签名 OpenPGP 报文的生产者希望希望流式处理签名计算，使得其可以产生已签名数据的同时计算密码学签名。在签发者侧，签名包很容易存储在已签名数据后。

* 另一边，验证者，需要签名包的一些信息，才能执行签名验证流程。具体来说，验证者需要指导使用哪个散列算法计算签名，以在信息数据上执行相同的散列操作。

结果就是，若没有单程式签名包，要么：

* 生产者需要处理输入数据两次：
** 第一次是计算密码学签名，以及
** 第二次来产生已签名数据（该格式获得一个<<前缀式已签名报文>>），或者

* 验证者需要处理 OpenPGP 报文两次：
** 第一次读取尾部的签名包来确定散列算法，并
** 第二次处理报文的正文，计算其散列值以验证签名。

单程式签名包通过，同时允许已签名报文的单程_创建__和__验证__，解决该问题。单程签名数据包实际上包含了，签名数据包中数据的提前拷贝（advance copy），但没有包含密码学签名数据。

签名者可以很容易地，在完整地处理报文之前，在一次性签名包中产生元数据。对于验证者来说，使用已签名报文的开头的元数据，就可以处理报文正文。

即便在流式处理模式下，签名者也可以高效地生成单程已签名报文，而验证者可以高效地检查它们。

==== 创建

要产生一个单程内联签名，签名者确定一个散列算法，并生成一个单程签名包置入 OpenPGP 报文。其包含基础信息，比如签名密钥的指纹，计算签名摘要的散列算法。签名者之后处理被签名报文的整体，生成一个或多个包，一并置入报文中。一旦数据处理完成，签名者使用得到的散列值计算密码学签名。最后，结果作为数据签名包置入输出的报文中，整个包序列就可以被高效地存储或传输了。

==== 验证

要高效验证，应用必须知道，如何在读取 OpenPGP 报文之前处理它。该要求由，位于内联已签名报文头部的单程签名包，来满足。这种设置让验证者可以，在单个流程中正确而高效地处理数据。

严格来说，仅需知道散列算法就足够开始验证流程。但是，提前知道签名者的指纹或密钥 ID，可以让 OpenPGP 软件在处理整个（可能很大的）已签名数据之前，获取签名者的证书。这可能包含从密钥服务器上下载证书。若获取签名者证书失败，或者要求用户额外的输入，那么最好在处理数据之前提示用户。

单程内联已签名报文，让验证可以高效地在单程中完成，其结构如下：

. **以单程签名包起始**：这些包启动验证流程。它们包括签名者的 ID/指纹，主要用于确定签名验证的合适公钥。

. **处理 OpenPGP 信息**：本步骤包括求数据散列值，准备签名验证。

. **验证签名包**：，这些包在报文末尾，之前计算的散列摘要会与之对比。

要点，签名者的公钥，对最终的验证步骤十分关键，并不嵌入在报文中。验证者必须从外部请求该密钥（比如从密钥服务器上）来验证签名。

==== 嵌套单程签名

一个单程已签名报文可能实际上包含多个嵌套的签名。

正式来说，因为在 link:{crypto-refresh-12_url}#name-openpgp-messages[OpenPGP 报文语法]中，当一个输入的 OpenPGP 报文被单程签名，生成的包也被认为是一个 OpenPGP 报文。

因此，已签名的报文可以再次被单程签名。这种结构意味着单程签名可以一层层嵌套。

===== 嵌套签名的两种语义

嵌套单程签名有两个不同的用途和语义：

* 多个签名者各自签发的密码学签名存储在一个共享的（这样空间利用率高）内联已签名报文。此时，每个签名者就仅对已签名报文制作一个密码学陈述。这些签名是相互独立的。
* 或者，一个签名者不仅仅可以对输入的信息进行签名，也可以在他们的签名中包含之前的签名。此时，一个签名者可以为之前已有的签名和已签名报文制作一个密码学陈述。这意味着新签名者认可之前的签名。

===== 如何选择

当嵌套单程签名时，默认的期望是每个签名都对其封装的整个报文（包括内部报文的任何单程签名）制作陈述。

签名的签发者可以选择他们签名的语义，使用单程签名包的link:{crypto-refresh-12_url}#section-5.4-3.8.1[“nested”标识]。“nested”标识的值为 `1` 或者 `0`。

“nested”标识的含义为：

* `0` 表示一个该签名封装的单程签名__未经__签名/证明。新签名不对直接封装的签名制作密码学陈述。若直接封装的单程单程签名的“nested”标识依旧为 `0`，则被封装签名的散列值同样不包含其内部的签名，以此类推。
* `1` 表示这个单程签名对整个包含的报文（以及其中所有已有的签名）制作了一个密码学陈述。

一个典型的用法是在最内部的签名上设置“nested”为 `1`，在所有其它封装的签名上设置“nested”为 `0`。这种用法让所有签名相互独立。每个签名都仅对最内部的信息载荷（其存储在字面量数据包中）产生一个陈述。

===== 案例

一个实际的案例，考虑如下符号：

* `LIT("Hello World")` 表示一个字面量数据包，其内容为 `Hello World`。
* `COMP(XYZ)` 表示一个压缩后数据包，其内容为其它的包 `XYZ`。
* `OPS~1~` 表示一个单程签名包，其 nested 标识设置为 `1`。同理， +
`OPS~0~` 表示其 nested 标识设置为 `0`。
* `SIG` 表示一个签名包。

一个普通的单程签名包类似：`OPS~1~ LIT("Hello World") SIG`

此处，签名在载荷 `Hello World` 上计算。即便已签名报文以这样的形式存储 `OPS~1~ COMP(LIT("Hello World")) SIG`，其签名也不会变化（见<<计算一个内联签名的已签名载荷的散列值>>）。

若有多个独立的单程签名在相同的载荷上进行计算，那么该报文类似于 `OPS~0~ OPS~0~ OPS~1~ LIT("Hello World") SIG SIG SIG`，所有三个签名都计算了相同的载荷 `Hello World`。

反过来说，一个报文，其签名者已经认可了已签名的报文，则具有如下格式 `OPS~1~ OPS~1~ LIT("Hello World") SIG SIG`。其内部的签名在常规载荷 `Hello World` 上计算，而外部的签名则在 `OPS~1~ LIT("Hello World") SIG` 上计算。

=== 前缀已签名报文

一个前缀已签名报文由签名包和之后的信息组成。对于验证者，处理单已程签名和前缀已签名报文同等方便。但是，在签名者端，要使用更多的资源来生成前缀已签名报文。

这是一个过时的格式。并非所有的现代实现都支持它。但是，举例来说，GnuPG 2.4.x 支持验证该签名格式的报文。

==== 结构

在这个格式中，签名包存放在信息本身之前：

. **数据签名包**：一个或多个包含原始数据对应的密码学签名的包。
. **OpenPGP 信息**：其包含未经额外解析或转换的原始数据（比如，信息的正文）。

与单程已签名报比较，该格式没有单程签名包，而且（等价的）签名包存放在已签名数据前。

[NOTE]
====
即便一个前缀已签名报文包含多个签名包，每个签名包都仅包含独立的、对信息载荷的签名。签名不会在散列值中包含之前的签名，每个签名都只针对信息的原始载荷数据。
====

==== 该格式对于签名者并不高效

就验证来说，该格式与单程已签名报文格式同等方便。

但是，当签名者创建前缀已签名报文的时候，已签名数据必须处理两次：

* 第一次读取它，并计算密码学签名，并
* 再额外读取一次，以在签名包之后生成 OpenPGP 报文。

=== 计算一个内联签名的已签名载荷的散列值

当内联签名一个信息，已签名内容的散列值，仅对字面量数据包中的原始载荷计算。字面量数据包的元数据不会参与已签名散列。即便有压缩数据包包裹字面量数据包，内联签名也仅针对未压缩的字面量数据包的内容。

内联数据签名的计算在两个方面都与众不同：

* 大多数 OpenPGP 签名计算都会包括包的元数据，但对于字面量数据包，仅计算其载荷的散列值。
* 包通常不会执行任何转换，而是直接计算散列值。但是该模式下，会解压压缩数据包的内容。

但是，这种方法让分离式签名和内联式签名在完全相同的数据上进行计算。

一种格式可以在事后转换成另一种格式，而不需要签名者的私钥材料。可以插入或移除压缩层，而不会影响现有签名的有效性。
