= 进阶材料：签名

:crypto-refresh-12_url: https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html

== 注释签名子包

link:{crypto-refresh-12_url}#notation-data[注释签名（notation signature）]子包可以通过用户定义的注释，有效地用于扩展 OpenPGP 中有限的签名子包类型。签发者可以使用这些注释向一个 OpenPGP 签名中添加键值对。

注释名——以 UTF-8 编码——可以置于“用户命名空间”。该命名空间的特点是一个注释标签，跟随一个 DNS 域名，两者均以 UTF-8 格式编码。

注释，如上所述，允许用户定义的 OpenPGP 签名子包类型扩展。一个实际的流行的使用该功能的应用，可见于 Keyoxide，一个去中心化的身份认证服务。Keyoxide 在 `ariadne.id` 命名空间中使用注释。该实现的细节，见 link:https://docs.keyoxide.org/wiki/ariadne-identity/[Keyoxide 文档]。

== 为一个签名选择散列算法

签名包的中心元素是输入数据的散列摘要。OpenPGP 软件通常支持一系列散列算法。这种可以在多个选项中进行选择的能力，是让 OpenPGP 在密码学中灵活的原因，这是一种称为__密码学敏捷性__（__cryptographic agility__）。被选择的机制则用于计算散列摘要。

不同的散列机制提供不同的取舍：

* __散列摘要的大小__：散列摘要的大小是至关重要的考虑因素。通常来说，更大的散列大小表示对抗密码分析（cryptanalysis）时更加强健。散列摘要相对较小——通常 32 至 64 字节大小。但是，在有些情况下——特别是小信息在带宽有限的网络中传输时——更大的散列大小会不可接收地增大信息的大小。
* __计算消耗__：不同的散列算法具有不同的计算消耗。当计算环境有限时，有些 OpenPGP 用户可能会限制这个消耗。

选择散列算法并非随意的，它是由与 OpenPGP 证书关联的特定的偏好所指导的。下面的章节将讨论这些偏好时如何影响散列算法的选择的。

=== 常规签名上下文，本地算法选择

在很多时候，一个签名并非为特定的个人或实体而创建。反之，这些签名被设计为对任何可能接触它们的接收者来说都可用。

举例来说，证书的自签名面向广泛的受众——基本上就是任何可能与证书交互的人。另一个例子就是软件报的数据签名。这些签名并非面向单个接收者，而是任何会去验证签名的用户和系统，而且可能会横跨数年。

由于没有特定接收者，签名的签发者可以自由地选择散列算法。该选择是基于签发者自己的标准和需求，与任何第三方无关。

=== 特定的签名上下文，接收者驱动的选择

当一个信息是为特定的接收者准备的时候，签名包的散列算法的选择则由，link:{crypto-refresh-12_url}#name-hash-algorithm-preferences[接收者的散列算法偏好]所指引。

接收者的散列算法偏好在他们的 OpenPGP 证书的元数据中定义。见xref:73.04、证书.adoc#_算法偏好和特性标记feature_signaling[算法偏好和特性标记]了解详情。

在这个流程中，签名过的散列摘，由接收者的偏好和发送者的能力与偏好，交叉选定的散列算法创建。

== 签名版本

如 link:{crypto-refresh-12_url}#name-signature-packet-type-id-2[RFC] 中描述的，生成的签名包的版本必须服从签发该签名的密钥的版本。

也就是说：

* OpenPGP 第 6 版密钥必须生成第 6 版签名包
* OpenPGP 第 4 版密钥必须生成第 4 版签名包

由于部分历史原因，需要处理旧 OpenPGP 数据的应用依旧需要面对第 3 版签名包。这些第 3 版签名包将会由第 4 版密钥生成。
