= 进阶材料：签名验证

:crypto-refresh-12_url: https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-12.html

== 属性遮蔽

当确定密钥的偏好的时候，可能需要检查多个签名。

举例来说，当使用签名子密钥来生成数据签名，一个实现可能希望检查子密钥绑定签名上的散列算法偏好。但是，RFC link:{crypto-refresh-12_url}#section-5.2.3.10-2[表明]，OpenPGP 证书的主密钥的直接密钥签名（也可能包含偏好）中的签名子包也会作用于整个 OpenPGP 密钥，也会作用于签名子密钥。

此时，实现会使用子密钥绑定签名中的偏好，但是，若没有最后的绑定签名中没有这类子包，则回退到使用直接密钥签名的偏好。这种行为被称为属性遮蔽，因为直接密钥签名子包作用在所有子密钥上，同时其也被绑定签名子密钥所遮蔽。

[NOTE]
====
属性遮蔽在算法偏好上可较为直接的理解。对于其它的子包类型，遮蔽可能让人困惑，并且/或者具有未定义的语义（比如，密钥过期时间子包）。
====

== 签名遮蔽

在检查 OpenPGP 证书的一个组件的签名的时候，每个功能实际起效的签名，都是最新的那个。

换句话说：

* 一个子密钥有三个绑定签名 `A`、`B`、`C`，其中
** `A` 创建于时间 `t0`，
** `B` 在 `t1`，
** `C` 在 `t3`，且
** `t0 < t1 < t2 < t3`

* 则在 `t2` 时，实现仅需考虑签名 `B`，
** 因为 `C` 还未起效，且
** `A` 被遮蔽，因为它比 `B` 旧。

[NOTE]
====
签名遮蔽不应该与属性遮蔽混淆。
====

由于属性和签名遮蔽可以同时存在，在给定的时间点上，一个密钥具有的属性可能并不那么显而易见。

== 哪个签名具有优先权？

一个 OpenPGP 证书或组件可以添加多个签名。这些签名可能包含冲突的信息。

当验证一个非自判定（self-qualifying）的签名时，一个实现需要检查签发者证书的自判定签名来进行判定。证书的一个组件可能包含多个签名。

举例来说，一个子密钥可能具有多个子密钥绑定签名。可能是由于原有的绑定签名已经过期，证书的持有者会签发一个新的扩展了过期时间的绑定签名。

通常来说，对于每个类别的签名（比如特定子密钥的绑定签名），具有最新的创建时间的签名具有优先权，且仅考虑该签名。

与之前所述不同，不同类型的签名之间可能存在判定竞争，比如，在主用户 ID 上的直接密钥签名和自认证签名。这两者具有的元数据都和整个证书关联。默认情况下，OpenPGP 第 6 版偏向直接密钥签名。

基于证书是如何“定位的”，可能的候选签名的元数据可以互相“遮蔽”。RFC link:{crypto-refresh-12_url}#name-notes-on-self-signatures[表明]，当 OpenPGP 软件“通过一个身份认证”一个证书，那么与该身份认证关联的元数据就优先于更全局的元数据，比如那些通过直接密钥签名关联的证书主密钥的元数据。

举例来说，最新的直接密钥签名可以列举“SHA256、SHA384”作为散列算法偏好，而最新的用户 ID“Bob”的自认证可能仅列举了“SHA256”。对于另一个用户 ID“Bobby”，自签名可能没有列举任何散列算法偏好。若用户想使用关联的 OpenPGP 密钥制作一个签名信息，那他就需要确定使用哪个偏好。

规范建议实现应该通过证书是如何“确定”的，来决定签名的优先权。

若用户想以“Bob”的身份写一封邮件，那么他应该考虑“Bob”上的签名，因此 SHA265 应该作为散列算法。若用户想以“Bobby”的身份写，那么实现就应该检查“Bobby”的自证明。但是，由于这个签名不包含任何散列算法偏好子包，此时实现必须回退至直接密钥签名。

更加复杂的情况是：子密钥绑定签名的算法偏好比直接密钥签名更优先，但并不比用户 ID 的自认证更优先。

一个组件可以有多个签名。举例来说，可能会有三个直接密钥签名（比如，密钥过期时间被扩展了两次）。总的来说，对于每个组件，仅有最新的自签名是“起效的”，旧签名被“遮蔽”。对于每个证书，最多仅有一个“激活的”直接密钥签名，对于每个用户 ID，最多有一个激活的自认证，对于每个子密钥，仅有一个子密钥绑定。

== 包格式的复杂性

OpenPGP 证书可以包含复杂的偏好设置。额外地，以 TPK 格式存储证书地时候，OpenPGP 包格式允许很大的灵活性。

用户 ID 包，举例来说，在 TPK 中不具有固定的位置。这意味着一个攻击者（或一个实现的内部证书规范化流程）可以修改用户 ID 在证书包序列中的顺序。

举个实例的例子，考虑一个具有多个用户 ID 的证书，其所有的用户 ID 都标记为主用户 ID。或类似地，一个具有多个用户 ID 的证书，没有任何用户 ID 标记为主用户 ID。客户端可能会使用不同的方式，确定哪个用户 ID 作为实际的主用户 ID。

这种细微的证书表现形式的变化，会导致不同的 OpenPGP 实现解释出不同的偏好设置。
