= 进阶材料：数据签名

== 内联已签名信息的内部

内联已签名信息是 xref:73.07、对数据签名.adoc#_openpgp_数据签名的形式[OpenPGP 数据签名]的一种形式。一个内联已签名信息将已签名的数据和其对应的数据签名结合为单一的 OpenPGP 信息。

OpenPGP 定义了两种内联已签名信息的形式：

. **单程式已签名信息**（**one-pass signed message**）：它是内联签名信息常用的格式。一个签名者和一个验证者可以单程式地验证该格式。
. **前缀式已签名信息**（**prefixed signed message**）：该格式在单程式已签名格式之前，它在概念上更简单一些。但是，它已经很少使用，并可以被认为是过时格式。

=== 单程式已签名信息

这是常用的内联已签名信息的格式。

==== 结构

一个单程式已签名 OpenPGP 信息由三段组成：

. **单程式签名包**：一个或多个在已签名数据之前的包，并允许（在创建时的和验证时的）签名计算一次性完成。
. **OpenPGP 信息**：包含原始数据载荷（比如信息的正文），其被签名而不需要额外的解释或转换。在内部，一个已签名信息包含一个或多个 OpenPGP 包。该载荷通常使用字面量数据包（Literal Data Packet）或压缩数据包（Compressed Data Packet）存储。
. **数据签名包**：它们包含了已签名的数据的密码学签名。

[NOTE]
====
即便名字中有“签名”二字，单程式签名包并非签名包的一个类型。

相反，它是一种辅助包，与签名包结合之后，可高效地生成和检查内联已签名信息。

单程式签名包的结构紧密镜像 OpenPGP 签名包。但它不包含密码学签名。
====

==== 单程式签名包的功能

该包的目的是高效地以__流式__模式处理内联已签名信息。该特性在已签名信息巨大、超过了可用内存的时候非常有用。

如果没有这个数据包，签名数据包在内联已签名 OpenPGP 信息中的位置就需要权衡：

* 一个已签名 OpenPGP 信息的生产者希望希望流式处理签名计算，使得其可以产生已签名数据的同时计算密码学签名。在签发者侧，签名包很容易存储在已签名数据后。

* 另一边，验证者，需要签名包的一些信息，才能执行签名验证流程。具体来说，验证者需要指导使用哪个散列算法计算签名，以在信息数据上执行相同的散列操作。

结果就是，若没有单程式签名包，要么：

* 生产者需要处理输入数据两次：
** 第一次是计算密码学签名，以及
** 第二次来产生已签名数据（该格式获得一个<<前缀式已签名信息>>），或者

* 验证者需要处理 OpenPGP 信息两次：
** 第一次读取尾部的签名包来确定散列算法，并
** 第二次处理信息的正文，计算其散列值以验证签名。

单程式签名包通过，同时允许已签名信息的单程_创建__和__验证__，解决该问题。单程签名数据包实际上包含了，签名数据包中数据的提前拷贝（advance copy），但没有包含密码学签名数据。

签名者可以很容易地，在完整地处理信息之前，在一次性签名包中产生元数据。对于验证者来说，使用已签名信息的开头的元数据，就可以处理报文正文。

即便在流式处理模式下，签名者也可以高效地生成单程已签名信息，而验证者可以高效地检查它们。

==== 创建

要产生一个单程内联签名，签名者确定一个散列算法，并生成一个单程签名包置入 OpenPGP 信息。其包含基础信息，比如签名密钥的指纹，计算签名摘要的散列算法。签名者之后处理被签名信息的整体，生成一个或多个包，一并置入信息中。一旦数据处理完成，签名者使用得到的散列值计算密码学签名。最后，结果作为数据签名包置入输出的信息中，整个包序列就可以被高效地存储或传输了。

==== 验证

要高效验证，应用必须知道，如何在读取 OpenPGP 信息之前处理它。该要求由，位于内联已签名信息头部的单程签名包，来满足。这种设置让验证者可以，在单个流程中正确而高效地处理数据。

严格来说，仅需知道散列算法就足够开始验证流程。但是，提前知道签名者的指纹或密钥 ID，可以让 OpenPGP 软件在处理整个（可能很大的）已签名数据之前，获取签名者的证书。这可能包含从密钥服务器上下载证书。若获取签名者证书失败，或者要求用户额外的输入，那么最好在处理数据之前提示用户。

单程内联已签名信息，让验证可以高效地在单程中完成，其结构如下：

. **以单程签名包起始**：这些包启动验证流程。它们包括签名者的 ID/指纹，主要用于确定签名验证的合适公钥。

. **处理 OpenPGP 信息**：本步骤包括求数据散列值，准备签名验证。

. **验证签名包**：，这些包在信息末尾，之前计算的散列摘要会与之对比。

要点，签名者的公钥，对最终的验证步骤十分关键，并不嵌入在信息中。验证者必须从外部请求该密钥（比如从密钥服务器上）来验证签名。

==== 嵌套单程签名

一个单程已签名信息可能实际上包含多个嵌套的签名。

正式来说，因为在 OpenPGP 信息语法中，当一个输入的 OpenPGP 信息被单程签名，生成的包也被认为是一个 OpenPGP 信息。

因此，已签名的信息可以再次被单程签名。这种结构意味着单程签名可以一层层嵌套。

