= 进阶材料：组件签名

== 证书的配方

OpenPGP 中不同的签名服务于各式各样的特定目标。本解提供了创建这些签名的实践指导，每个都给出了具体实例。

=== 修改算法偏好

要修改一个密钥的偏好的对称、加密、散列或 AEAD 算法，密钥的持有者需要在主密钥上签发一个直接密钥签名（类型 ID `0x1F`）。

签名应该具有以下结构：

|===
| 子包 | 区域 | 关键性 | 必要性 | 备注

| 签名创建时间 | 散列区 | 真 | 真 | 当前时间
| 签发者指纹 | 散列区 | 真或假 | 强烈建议 | 主密钥是签发者
| 密钥标识 | 散列区 | 真 | 假 | 从之前的自签名中获取密钥标识
| 特性 | 散列区 | 真 | 假 | 从之前的的自签名中获取特性
| 密钥过期时间 | 散列区 | 真 | 假 | 若有之前的自签名有，则从其中获取
| 散列算法偏好 | 散列区 | 假 | 假 | 新的偏好
| 压缩算法偏好 | 散列区 | 假 | 假 | 新的偏好
| 对称算法偏好 | 散列区 | 假 | 假 | 新的偏好
| AEAD 算法偏好 | 散列区 | 假 | 假 | 新的偏好
|===

=== 修改过期时间

要修改 OpenPGP 证书的过期时间，必须签发一个新的、具有修改后的密钥过期子包的，__直接密钥__签名。该签名的结构与前修改算法偏好的章节完全一致。

额外的，过期时间可以为每个用户 ID（细节见下）或每个子密钥（见 xref:73.08、组件签名.adoc#_将子密钥绑定至证书[章节 8.2.1]）修改。

=== 添加用户 ID

要将一个用户 ID 绑定至一个证书，需要使用一个证书签名（类型 ID `0x10` 至 `0x13`），且其具有如下结构：

|===
| 子包 | 区域 | 关键性 | 必要性 | 备注

| 签名创建时间 | 散列区 | 真 | 真 | 当前时间
| 签发者指纹 | 散列区 | 真或假 | 强烈建议 | 主密钥是签发者
| 主用户 ID | 散列区 | 真 | 假 | 可选
| 签名过期时间 | 散列区 | 真 | 假 | 可选
|===

除了这些子包，用户 ID 的自证书（self-certification）可以包含其它字段——比如密钥标识、特性、算法偏好——正如之前的表格所描述的。这样就能为与证书相关的每个身份指定独特的能力和偏好。

=== 移除或吊销一个用户 ID

由于 OpenPGP 证书通常通过密钥服务器的方式分发，一个证书上的新签名通常“xref:73.18、进阶材料：证书.adoc#_合并[合并]”至接收方本地现有的证书拷贝。

这种合并的过程意味着实际上不可能直接从证书移除签名或用户 ID，因为没有方法告诉接收方移除一个包。

要有效地将一个用户 ID 标记为无效的，用户可以发布一个证书的拷贝，其中无效的用户 ID 会追加一个证书吊销签名（类型 ID `0x30`）。该签名表明特定的用户 ID 不再有效，或与证书持有者相关联。

证书吊销签名的结构如下：

|===
| 子包 | 区域 | 关键性 | 必要性 | 备注

| 签名创建时间 | 散列区 | 真 | 真 | 当前时间
| 签名者指纹 | 散列区 | 真或假 | 强烈建议 | 主密钥是签名者
| 吊销理由 | 散列区 | 真 | 假 | 区分软或硬吊销
|===

对于用户 ID 吊销，__吊销理由__子包十分关键。值 `0` 意味着没有特定的理由，也就导致一个硬吊销，而 `32` 标识用户 ID 不再有效，导致一个软吊销。忽略理由子包等同于硬吊销。

通常见使用理由码 `32` 来吊销用户 ID。

