= 容器隔离

容器共用一个系统内核，若一个容器能控制宿主机的内核，那么它就能控制所有在该宿主机上运行的容器，以及所有宿主机上运行的非容器进程。同样的，若一个容器能直接控制底层的文件系统，那么它就有可能随意读写文件系统上的任何文件。从这种意义上来说，容器安全的首要任务就是保护内核和文件系统不被容器随意修改。

== 只读 Linux 内核伪文件系统

Linux 内核通过特定的文件系统，让进程可以与内核通信，并配置内核。我们需要保护这些文件系统，防止受限容器修改它们。

Linux 内核的伪文件系统通常挂载在 **/proc** 和 **/sys** 下。大多数进程需要读取这些文件系统下的数据，但仅有管理员需要额外的写入权限。通常来说，内核会要求 root 权限，或者具有 **CAP_SYS_ADMIN** 能力（capability）的进程来修改这些文件系统。

在处理挂载至 **/proc** 和 **/sys** 的伪文件系统的时候，Podman 仅会以只读的方式挂载部分 **/sys** 下的文件系统，而 **/proc** 则与宿主系统上的 **/proc** 完全不同（这样容器内的进程就只能控制容器内启动的进程了）。而且，部分文件/文件夹会包含宿主系统的关键信息，这些文件会被挂载为 **/dev/null**，文件夹会被挂载上只读的 tmpfs，以防止泄露数据。

[NOTE]
====
在容器中运行 `mount` 命令，可以查看容器内部的挂载情况。
====

=== Unmask 已经 mask 的路径

我们可以在创建容器的时候，指定不要被 mask 的路径。比如 **/proc/scsi** 默认是被 mask 的：

[source, sh]
----
# 检查 mount 情况，从返回值可以看到，/proc/scsi 被挂载了一个 0k 大小的只读 tmpfs
podman run --rm fedora:41 mount | grep /proc/scsi

# 检查 /proc/scsi 的内容，从返回值可以知晓，这个目录下什么也没有
podman run --rm fedora:41 ls -l /proc/scsi
----

之后，我们在创建容器的时候，可以通过 `--security-opt unmask=<路径>` unmask **/proc/scsi**

[source, sh]
----
# 在 unmask /proc/scsi 的情况下，枚举该路径下的文件，可以看到其中具有一些内容
podman run --rm --security-opt unmask=/proc/scsi fedora:41 ls -l /proc/scsi
----

[NOTE]
====
阅读 podman-create 的帮助中，有关于 security-opt 的 unmask 的部分，可以知晓 podman 默认 mask 的路径。
====

=== Mask 额外的路径

`security-opt` 可以 unmask 已经 mask 了的路径，就可以 mask 还未 mask 的路径。

[source, sh]
.mask **/proc/sys/dev**
----
# 首先检查 /proc/sys/dev 下的内容
podman run --rm fedora:41 ls -l /proc/sys/dev

# mask 这个路径
podman run --rm --security-opt mask=/proc/sys/dev fedora:41 ls -l /proc/sys/dev
----

== Linux 能力（capabilities）

现在有一个问题，若容器可以知晓容器挂载的路径，那么我们如何阻止容器中以 root 身份运行的程序解挂载、或将只读挂载重挂载为读写模式，进而攻击内核呢？

大多数用户知道 Linux 有两类用户，具有完整权限的 root 用户，以及具有有限权限的非 root 用户。当一个非 root 用户需要执行高权限的程序的时候，非 root 用户需要提权操作（比如 `sudo` 和 `ping`），这个操作是通过给特定程序文件设置 **setuid** 位来实现的。当非 root 用户运行了具有 **setuid** 的程序文件的时候，新进程就具有了 root 权限。

这种简单地将用户/进程区分为特权和非特权的方式，在 2000 年左右迎来了其终结。Linux 内核工程师们将 root 权限拆分为了数个特权能力（capabilities）。我们可以通过 `man 7 capabilities` 了解这些能力。 +
要想了解当前内核支持的能力，可以读取 **/proc/sys/kernel/cap_last_cap**。它表示当前内核支持的最大能力序号，也就是说，当前内核支持从 0 号能力到文件所给出的最大能力之间的所有的能力。不过很可惜的是，我们并不能直接通过软件获得能力序号与名称之间的关系，我们需要搜索 Linux kernel 的源码来了解对应关系：**/usr/src/kernels/$(uname --kernel-release)/include/uapi/linux/capability.h**

要了解当前用户所具有的能力，以及（通过诸如 setuid）可以获得的能力，可以使用 `capsh --print` 命令。 +
`capsh --print` 返回值中的 `Current=` 表示当前用户已经具有的能力，而 `Bouding set=` 则表示可能可以获得的能力的最大范围。

=== 移除的 Linux 内核能力

由于容器内的进程不应该修改操作系统，因此，Podman 控制的容器，即便其中的进程具有 UID=0，它也仅具有少数几个 Linux 内核能力。我们可以在容器中运行 `capsh --print` 来查看容器进程具有的能力。

[source, sh]
----
podman run --rm fedora:41 capsh --print
----

[NOTE]
====
在容器中检查 **/proc/sys/kernel/cap_last_cap** 会获得与宿主机上一致的结果，毕竟容器使用的内核和宿主机上的一致。
====

=== 手动移除或添加 Linux 内核能力

使用 `--cap-drop=` 和 `--cap-add=` 可以移除和添加 Linux 内核能力。

[source, sh]
----
# 比如，我们不需要容器可以绑定端口号小于 1024 的能力
podman run --rm --cap-drop CAP_NET_BIND_SERVICE fedora:41 capsh --print

# 比如，我们要创建一个自定义的 IP 包
podman run --rm --cap-add CAP_NET_RAW fedora:41 capsh --print
----

=== 阻止获取新的 Linux 内核能力

使用 `--security-opt no-new-privileges` 可以阻止容器内的进程获取新的内核能力。这样，即便容器内的进程执行了具有 setuid 的软件，进程也无法获得新的能力。同时，这个选项还会阻止进程执行 SELinux 上下文切换。

== UID 隔离：用户命名空间（User namespace）

虽然移除 Linux 内核能力能大大增强容器内进程的安全性。但以 root 身份运行的程序依旧可以修改所有者为 root 账户的文件；以 root 账户运行的程序，可以修改系统文件，并诱使管理员运行这些修改过的文件；而且部分客户端-服务器设计的程序会直接相信以 root 账户运行的进程（比如 Docker）。Podman 使用用户命名空间来解决这些问题。

在 xref:76.06、rootless 容器.adoc[] 中，我们介绍了有关用户命名空间的概念。这样我们在容器中的 root 账户，在系统看来则不是，解决了上述问题。

对于 rootless 用户来说，还有一个问题：默认情况下，素有的容器都是在同一个用户命名空间中运行的。在理论上，仅从用户命名空间的角度来说，一个容器是可以攻击另一个容器的，因为它们具有相同的 UID。而且，若容器内的进程突破了容器，那么它们就可以任意修改你主文件夹中的任意文件，因为 rootless 容器内部的 root 账户，对应的是运行容器的用户的账户。

=== 使用 `--userns=auto` 隔离容器

Podman 是可以为每个启动的容器分配一组独占的 UID 的。在 rootless 模式下，创建容器的时候使用 `--userns=auto` 会自动执行如下的操作：

* 不将主机上当前用户的 UID 映射为容器内 UID 0
* 自动配置映射，将中间 UID 映射为容器 UID +
默认的效果是，读取 **/etc/subuid** / **/etc/subgid** 中可使用的 UID/GID 范围，判断当前系统上已经独占的 subuid/subgid，从可用的 subuid/subgid 的起点，并占用之后的 1024 个 subuid/subgid。
+
[NOTE]
====
* 默认的 1024 这个值，可以通过修改 `storage.conf` 中的 `auto-userns-min-size` 来修改。
* 在命令行设置中，我们可以使用 `--userns:size=<所需长度>` 为容器精确设置映射长度。
====

[TIP]
====
关于用户命名空间的额外解释，见 xref:76.99、关于 unshare 和命名空间的一些题外话.adoc[]
====

=== 用户命名空间中的 Linux 能力

在前面的章节中，我们提到了 Linux 能力。在一个用户命名空间中，用户也可以具有 Linux 能力。但这些能力仅能作用于该用户命名空间下的资源（比如网络资源），对于修改 UID/GID 的能力，则仅限于已经映射至该用户命名空间中的 UID/GID。

=== 使用 `--userns=auto` 后的 volume

如上文所述，当我们使用了 `--userns=auto` 后，每个容器的 UID 范围会有所不同，这会导致我们会较难以确定要挂载的 volume 应该使用什么 UID。

比如我们用 Podman 运行的账户创建了一个文件夹，比如 **$HOME/mountable**。然后我们在创建容器的时候，设置 `--userns=auto`，并使用 `--volume $(realpath $HOME/mountable):/mnt/mountable:Z` 挂载这个目录到容器中。就会发现，容器中挂载的路径的 UID 和 GID 被映射为了 nobody，这种情况下，我们是不能随意操作该挂载路径下的文件的（至少是不能使用 chown 改所有权的）。

在这种情况下，我们当然可以从容器的 PID 获取 uid_map 和 gid_map 信息，然后手动将 volume 的所有者修改为容器可以使用的 UID/GID。不过这个操作略显麻烦，我们可以在挂载容器的时候使用参数 `U`，让 Podman 在实际挂载 volume 的时候，自动检查修改文件的所有者为容器的 root。比如上述的挂载命令就可以修改为 `--volume $(realpath $HOME/mountable):/mnt/mountable:Z,U`。

[TIP]
====
Podman 现在还支持一种 `idmap` 的挂载参数，是更“智能”的 `U` 参数，但目前仅能用于高权限容器中，这里暂且不表。
====

== 进程隔离：PID 命名空间

PID 命名空间让容器中的进程只能看见容器内的进程，而不能看见容器外的进程，进一步阻止有害容器进程攻击容器外的进程。

有一些容器应用会要求访问宿主系统上的进程，对于这类容器，在创建容器的时候，我们可以添加参数 `--pid=host` 让该容器运行在宿主机的 PID 命名空间下。

====
与用户命名空间不同，PID 命名空间没有固定的映射方式。在宿主机系统上，每个进程都有自己的“每 PID 命名空间进程号”，可以通过 **/proc/<PID>/status** 文件的 **NStgid**、**NSpid**、**NSpgid**、**NSsid** 查询到。（完整字段含义见 `man 5 proc_pid_status`）

举例来说，我们可以启动一个容器，然后在容器中运行一个持续运行的进程，比如 `top`。然后我们就可以在宿主机上运行 `podman ps --ns` 来查看运行容器所在的命名空间号。这里我们关注的是 **PIDNS** 这一列，假设容器对应的 PID 命名空间号为 **__pid_ns_number__**。则我们可以通过 `sudo ps -O pidns | grep __pid_ns_number__` 来过滤出该 PID 命名空间中所有的进程。然后我们就可以使用 `cat /proc/<PID>/status | grep NS` 来打印特定进程**跨 PID 命名空间**的进程号（特别关注 `NSpid` 的结果）。此时，我们对比容器中正在运行的 `top` 命令的返回结果，就可以看到同一个进程在宿主机和容器中的进程号的对应关系。
====

使用 `--pid=host` 后，我们就能看到容器外部的进程了，而且容器内的进程的 PID 和宿主机上看到的 PID 是一致的。

[IMPORTANT]
====
如果你在不隔离 PID 命名空间的情况下，也没有隔离用户命名空间。那么容器中的进程是可以**轻易修改**宿主机上运行 Podman 的用户的进程的。因为容器的 root 账户等价于宿主机上 Podman 所在的账户，又不隔离 PID，这样宿主机上当前用户的进程对于容器来说，就是可读可写的。

**这种配置有很强的风险。**
====

== 网络隔离：网络命名空间

如 xref:76.06、rootless 容器.adoc[] 所述，默认情况下，rootless 容器使用 pasta 作为网络接入服务。pasta 本身较为简单，它仅拷贝了主机的 IP 地址和路由信息，不做任何 NAT 处理，这样容器中暴露出来的端口就如同直接在宿主机上暴露出来的一样。如果我们希望容器与容器之间通过一个桥进行连接，而不直接依赖宿主机的网络栈，Podman 也提供了桥接功能。

默认情况下，Podman 会创建一个名为 `podman` 的桥：

[source, sh]
----
podman network list
podman network inspect podman
----

我们可以创建一个网络桥：

[source, sh]
----
podman network create my_bridge
podman network list
podman network inspect my_bridge
# 当然，我们可以为这个桥执行更详细的配置
# 首先移除我们前面创建的桥
podman network rm my_bridge
# 可以为桥接设置具体的 DHCP 配置
# 特别的，由于我们可以为一个容器配置多个网络，因此在手动指定网络信息的时候，必须遵循 --subnet --gateway --ip-range 的顺序
podman network create --subnet 10.10.10.0/24 --ip-range 10.10.10.100-10.10.10.200 my_bridge
# 枚举网络接口，并检查我们刚刚创建的网络接口
podman network list
podman network inspect my_bridge
----

如果一个容器在创建时使用了 pasta 作为网络接入服务，那么是不可以切换到桥接的，我们需要在创建容器的时候，就指定网络使用桥接：

[source, sh]
----
podman create --network my_bridge <镜像名称>
----

一个容器使用了桥接之后，我们就可以使用 `podman network connect` 和 `podman network disconnect` 将容器添加至一个桥接中，或从一个桥接中移除：

[source, sh]
----
podman network connect <桥接名称> <容器名称>
podman network disconnect <桥接名称> <网络名称>
----

=== 手动创建两个网络命名空间之间的虚拟以太网连接

. 首先，我们要创建一个用户命名空间，之后所有的操作都仅限于该命名空间 `unshare --map-auto -- /usr/libexec/catatonit/catatonit -P &` +
记录返回的 PID（下称 __userns_pid__）。 让 **catatonit**“持有”该命名空间，让其在后台运行。

** `--map-auto` 会自动执行 `--map-groups=auto`，后者会自动更新创建的进程的 **/proc/<PID>/gid_map**，并保持进程的 **/proc/<PID>/setgroups** 为 allow，这样我们后面就可以通过 `nsenter` 进入这个用户命名空间中。 +
有关联的 issue，见 xref:https://github.com/util-linux/util-linux/issues/3553[util-linux/util-linux#3553] 和 xref:https://github.com/shadow-maint/shadow/issues/1256[shadow-maint/shadow#1256]
** `/usr/libexec/catatonit/catatonit -P` 我们要创建的进程为 `catatonit -P`，这是 Podman 最常用的持有用户命名空间的简易程序，当然我们也可以创建 **bash**，不过我们后面是需要额外用其它 shell 再入这个用户命名空间的，因此这里就用 **catatonit** 替代了。
** `&` 让 **unshare** 在后台运行，因为 **catatonit -P** 本身会在前台运行，占用我们的 shell。 +
Shell 语义上是让 unshare 在后台运行，但实际上，在内存中，由于 catatonit 替换了 unshare 的程序镜像，因此是 catatonit 在后台运行。

. 【可选】检查创建的用户命名空间 +
使用 `cat /proc/__userns_pid__/uid_map` 和 `cat /proc/__userns_pid__/gid_map` 查看 UID 和 GID 的映射情况；并使用 `cat /proc/__userns_pid__/setgroups` 确认其值为 `allow`。

. 开启一个新的 shell，并使用 `nsenter --target __userns_pid__` 进入该命名空间中，使用 `unshare --net` 创建一个网络命名空间。使用 `echo $$` 记录下当前 shell 的 PID，下称 __netns_a__。

. 重复上一步操作，在一个新的 shell 中创建一个新的网络命名空间。其 shell 的 PID 下称 __netns_b__。

. 在 __netns_a__（__netns_b__ 也可以）中使用这个命令创建一个 veth 设备对：`ip link add <设备名1> type veth peer name <设备名2>`， +
比如 `ip link add veth1 type veth peer name veth2`。这样我们就创建了一对相互连接的 veth 接口。

. 为 veth2 设置新的网络命名空间：`ip link set veth2 netns __netns_b__`。（将 veth2 “移动至”另一个命名空间）
** 若你在 __netns_b__ 中创建的设备，那么就要将 netns 的参数修改为 __netns_a__。
** 是移动 veth1 还是 veth2 过去并不重要，这里我们假设移动过去的是 veth1。

. 分别在两个网络命名空间中为设备设置 IP 地址 `ip address add dev veth1 10.10.10.1/24`，`ip address add dev veth2 10.10.10.2/24`
. 分别在 `ip link set veth1 up` 和 `ip iink set veth2 up` 启用端口
. 尝试 ping 对面的 IP 地址，发现可以 ping 通，如果你安装了 netcat 之类的软件，还可以尝试 TCP 通信。
