= 关于 unshare 和命名空间的一些题外话

== unshare

=== unshare 是什么

unshare 函数，是一个系统调用，它将当前进程的部分的共享资源独立出来，这样当前进程就可以独立控制这一部分的资源，而不干扰系统上的其它进程的资源。

unshare 命令的作用是，依照传入的参数，将自己的进程进行 unshare（同时也创建了各种命名空间）。然后将自己进程的程序镜像替换为目标程序的，并执行新程序（不使用 `--fork` 参数）；或者 fork 出一个新的子进程，让目标程序在新的子进程中运行（使用 `--fork` 参数，Podman 的默认行为）。

== 关于 Podman 是如何使用用户命名空间的

=== Podman 实际是如何执行 uidmap 和 gidmap

查询了 `man podman-create` 的 `--uidmap` 的部分可知：

若我们使用了 `--uidmap`，对于 rootless 容器来说，UID 映射经过了两步：

host UID（主机 UID） -> intermediate UID（中间 UID） -> container UID（容器 UID）

其中“主机 UID”至“中间 UID”的映射是 Podman 软件定义的，主机上的当前用户 UID 映射到“中间 UID”的 0，**/etc/subuid** 中定义的 UID 则顺次映射到“中间 UID”的 1,2,3,4。`--uidmap` 定义的是，“中间 UID”到“容器 UID”之间的映射，选项参数 `from_uid` 对应的是“中间 UID”的起点，`container_uid` 对应的是“容器 UID”的起点，`amount` 对应的是映射的长度。

=== 验证 Podman 的执行逻辑

对于使用了 `--userns` 选项，或者自定义了 uidmap 或 gidmap 的容器：

我们可以通过 `podman ps --ns` 查看运行容器的 PID 和用户命名空间。然后我们可以通过 `sudo lsns --tree` 来查看系统上所有的命名空间，之后我们就可以进行对比。我们可以发现，除了运行 Podman 时产生的一个用户命名空间，每个容器自己还会在 Podman 的命名空间中再创建一个用户命名空间。这与我们上面了解的 rootless 容器的“两步映射”是对应的。

我们可以进一步使用 `podman container inspect <容器名> --format '{{json .HostConfig.IDMappings}}'` 查看容器的 UID/GID 映射来验证我们的猜想。返回的数组，比如 **["0:1:1024"]** 表示的就是 `--uidmap` 的参数 **["容器 UID:中间 UID:映射长度"]**。

下面我们假设，通过 `sudo lsns --tree` 得到的 Podman 启动的 `catatonit -P` 进程的 PID 为 **__podman_pid__**，而得到的容器的主进程的 PID 为 **__container_pid__**。

我们可以接着使用 `nsenter --target __podman_pid__ --user cat /proc/__container_pid__/uid_map`，进入 Podman 初始创建的用户命名空间；来查看，站在 Podman 的视角下，容器主进程的 UID 的映射情况。我们可以发现，返回的内容与上面 podman inspect 返回的内容保持一致。这再次验证了 `--uidmap` 文档中所说的“二次映射”的行为。（对于这种容器的用户命名空间直属于 Podman 初始创建的用户命名空间，可以用 `--parent-user` 参数代替 `--target __podman_pid__` 参数）

除此之外，我们还可以在宿主机系统的命名空间下，查看 **/proc/__container_pid__/uid_map** 的内容。可以发现，由于当前进程所处的命名空间不同，即便是同一个 **uid_map** 文件的内容也是不同的，验证了我们 xref:76.06、rootless 容器.adoc[] 中的说法。另外，如果我们同时观察 **/proc/_podman_pid__/uid_map** 的内容，也可以发现 Podman 的“两步映射”是怎么逐步将宿主机系统上的 UID 映射到容器上的。
