= WSL 安装&设置记录

== 可选的预备工作

安装 link:https://aka.ms/terminal[Windows Terminal] 以及 link:https://code.visualstudio.com/[VSCode]

== WSL 的安装

[IMPORTANT]
====
安装时执行手动安装的步骤，不要使用 `wsl --install`
====

官方的手动安装说明文档： link:https://learn.microsoft.com/en-us/windows/wsl/install-manual[Manual installation steps for older versions of WSL]

=== 开启必要的 Windows 组件

. Windows 设置 -> 应用 -> 程可选功能 -> 更多 Windows 功能
. 在“Windows 功能”中勾选
.. “适用于 Linux 的 Windows 子系统”
.. 虚拟机平台
. 确认，等待系统安装，并重启 Windows

=== 手动下载 WSL 更新包

[NOTE]
====
如果已经是 Windows 11 系统，则不需要执行下载安装包的操作，直接从 <<再次更新 WSL 至最新的版本>> 步骤执行即可
====

从上面提到的官方文档网址中，找到 link:https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package[Step 4 - Download the Linux kernel update package]，下载 link:https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi[WSL2 Linux kernel update package for x64 machines] 并安装

=== 再次更新 WSL 至最新的版本

安装完成后，在 powershell 中执行下面的命令，以将 WSL 更新到最新

[source, powershell]
----
wsl --update
----

== Host 主机的基础设置

在 powershell 中执行下面的操作，让 WSL 以 WSL2 的方式运行

[source, powershell]
----
# 检查 wsl 默认运行的版本
wsl --status
# 若默认版本为 1，则执行下面的设置
wsl --set-default-version 2
----

另外还有一些主机配置

[source, ini]
.%USERPROFILE%/.wslconfig
----
[wsl2]
# 如果你自行编译了 WSL 的 Linux 内核
#kernel="X:\\wsl\\MSLK-HEAD"

# 限制每个虚拟磁盘的最大大小，单位是 byte
# 默认是 1TiB，这里我们限制为 64 GiB
defaultVhdSize=68719476736

# 每个 WSL 实例启动时，显示 debug 窗口（打印启动时的内核信息）
debugConsole=true

# 在运行 systemctl status 后，若返回中有 “Tainted: cgroupsv1” 的字样，则表明 WSL 运行在 cgroup v1 下，禁用它，强制使用 cgroup v2
#kernelCommandLine = cgroup_no_v1=all

[experimental]
# 启动 sparse 存储
# 特别的，如果你希望让 Hyper-V 中的虚拟机也可以使用这个磁盘镜像，则不要开启这个选项
#sparseVhd=true
----

== 手动导入 Guest 系统

=== 下载镜像

从 link:https://mirrors4.tuna.tsinghua.edu.cn/lxc-images/images/[清华大学镜像站 lxc-images] 中可以获得我们需要的 rootfs 文件

这里以 Fedora 41 镜像举例，找到如下目录 **/fedora/41/amd64/default/** 找到最新的时间点目录，找到其中的 **rootfs.tar.xz** 文件，并下载。

之后需要解压 **rootfs.tar.xz** 文件得到 **rootfs.tar** 文件（可以使用 7-zip 解压 .xz 文件）。

[NOTE]
====
一般来说，一个操作系统的分发商会提供 Docker image 或 OCI image，也可以下载来使用。 +
需要注意的是，这些 image 具有特殊的格式，可能需要多次解包，找到其中的纯粹的 rootfs 才能使用。
而且由于这些 image 是面向 docker/podman 形制的容器使用的，有一些基础的软件没有安装，需要我们在导入之后进行补充。
====

=== 通过命令行将 rootfs.tar 导入为 WSL Guset

执行下面的 powershell 命令

[source, powershell]
----
wsl --import <自定 WSL Guest 名称> <目标虚拟磁盘位置> <rootfs.tar 路径>
----

比如

[source, powershell]
----
wsl --import fedora X:\wsl\fedora ~\Downloads\rootfs.tar
----

== 首次启动 Guest 系统

重启 Windows Terminal，并在下拉列表中选择刚刚安装的 Guest 系统

稍等片刻，就可以看到 Windows Terminal 出现 bash 提示符，文件管理器左侧下方也出现了 `Linux` 网络位置。

=== 初步配置 Guest 系统

* 创建一个 wheel 账户
+
--
如果你的系统上没有 `sudo` 这个包，则安装它

[source, sh]
----
dnf install sudo
----

[%collapsible]
.关于安装 `sudo` 带来的额外修正
====
如果上面导入的镜像选用的是 Docker image 或者 OCI image，那么我们后面在使用 `passwd` 命令为管理员账户设置密码时，可能会报 `passwd: Permission Denied` 错误。
这是由于 Docker image/OCI image 是给 docker/podman 使用的，它们一般不需要设置任何用户密码或者创建额外的可登录用户。因此，虽然镜像中包含了 `passwd`，却没有安装另一个重要的包 `pam`。我们在安装 `sudo` 的时候，`pam` 会作为 `sudo` 的依赖一同安装。
====

之后通过下面的命令添加一个账户，并为之设置密码

[source, sh]
----
useradd -G wheel <账户名>

passwd <账户名>
----
--

* 额外的配置
+
--
我们还可以额外为 Guest 系统配置 WSL 相关的配置文件，以获得“更好”的体验。

创建 `/etc/wsl.conf` 文件：

[source, ini]
./etc/wsl.conf
----
[boot]
systemd = true # 启用 systemd 支持

[automount]
enabled = false # 如果你不需要从 WSL 中访问 Windows 上的文件资源，则可以设置该选项

[interop]
enabled = false # 关闭从 Guest 启动 Host 的进程的功能
appendWindowsPath = false # 禁用将 Host 的 PATH 环境变量解析为 Guest 的 PATH

# 如果你在 Guest 中创建了常用的 Linux 用户，则这里可以设置 WSL 启动时默认登陆的账户
[user]
default = <创建的用户名>
----

之后，我们在 powershell 中强制关闭 WSL，下次启动 WSL 时，这些配置文件就会被读取出来

[source, powershell]
----
wsl --shutdown
----
--

=== 启用 systemd 之后需要的额外配置

WSL 并没有通过 DHCP 给出 ip 地址，因此，我们可以关闭 systemd-networkd.service +
另外我们还要关闭 systemd-networkd-wait-online.service

systemd-homed.service 也是无法兼容 WSL 的，所以也可以一并关闭了

[source, sh]
----
systemctl disable systemd-networkd.service systemd-networkd.socket systemd-networkd-wait-online.service systemd-homed.service
----

最后，重启 Guest 系统

[source, sh]
----
reboot
----

到此为止，Guest 系统就能在启用了 systemd 之后正常联网了

== 其它小问题的解决

=== 从 Guest 系统访问 Host 提供的网络服务

修改“高级安全 Windows Defender 防火墙”的配置

首先是启用 入站规则 中的 虚拟机监控(回显请求 - ICMPv4-In)

接着，对于 Guest 要访问的 Host 网络服务，关闭边缘遍历，将该服务的“配置文件”包含“公用”，并将其作用域的远程地址限制在 172.16.0.0/12

=== fedora 镜像默认无 man 帮助文件

如下，注释 /etc/dnf/dnf.conf 中的下面这行

[source, ini]
./etc/dnf/dnf.conf
----
# tsflags=nodocs
----

安装 man

[source, sh]
----
dnf install man
----

之后，我们可能需要重新安装所有的包，以补全所有的帮助文件

[source, sh]
----
sudo dnf reinstall -y $(dnf repoquery --installed)
----

=== 缩减 vhdx 大小

wsl2 的 vhdx 默认只扩大，不缩小，有时候在我们删除了大量文件之后，可以手动缩小 vhdx 来节省硬盘空间

首先停止 wsl2

[source, powershell]
----
wsl --shutdown
----

以管理员模式启动 powershell，并运行

[source, powershell]
----
Optimize-VHD -Path <ext4.vhdx 路径> -Mode Full
----

就可以缩小 vhdx 盘的大小

注意我们不用手动修改 ext4 文件系统的大小。

=== 无法启动 WSL2 中带 GUI 的应用程序

解决方案：link:https://github.com/microsoft/WSL/issues/6999#issuecomment-2303010704[]

简单来说，创建文件 **/etc/tmpfiles.d/wslg.conf**，内容如下：

[source, conf]
----
#  This file is part of the debianisation of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.

# See tmpfiles.d(5) for details

# Type Path           Mode UID  GID  Age Argument
L+     /tmp/.X11-unix -    -    -    -   /mnt/wslg/.X11-unix
----
