= resolve.conf
:gethostname(2):link:https://man7.org/linux/man-pages/man2/gethostname.2.html[gethostname(2)]


== 名称

resolv.conf - 解析器配置文件

== 语法

/etc/resolv.conf

== 描述

__解析器__是一组 C 库的例程，这些例程用于提供访问互联网域名系统（DNS）。解析器配置文件包含的信息，将在解析器例程被一个进程首次调用时读取。文件被设计为人类可读的，并包含了一系列具有值的关键字，它们用于提供各种类型的解析器的信息。配置文件被认为是一个可信的 DNS 信息源；参见下方的 `trust-ad` 选项了解详情。

若该文件不存在，仅会请求本地机器的名称服务器，且搜索列表所包含的本地域名由主机名决定。

不同的配置选项为：

`nameserver` 域名服务器 IP 地址::
解析器应该请求的名称服务器的互联网地址，要么是一个 IPv4 地址（用点号标记法表示）,或者依照 RFC 2373 定义的由分号（可能为点号）分隔的 IPv6 地址。最多支持列举 `MAXNS`（当前为 3，参见 `<resolv.h>`）个名称服务器。若有多个服务器，则解析器库会依照列表的顺序顺次发送请求。若没有出现 `nameserver` 条目，则默认值为使用本地机器上的名称服务器。（被使用的算法为，尝试一个名称服务器，若请求超时，则尝试下一个，直到用尽名称服务器，之后再重新尝试所有的名称服务器，直到达到最大的重试次数）。

`search` 主机名的查找列表::
默认情况下，查找列表包含一个条目，本地域名。它由 {gethostname(2)} 返回的本地主机名决定；本地域名来自首个点号 `.` 之后的全部内容。最后，若主机名不包含点号 `.`，那么就假设本地域名为根域。 +
这可以通过在关键字 `search` 后罗列需要的域搜索路径来实现，多个名称之间可以用宫格或者制表符分隔。解析器的请求若少于 __ndots__ 个点（默认为 1），那么就逐次测试搜索路径，直到首个匹配。对于具有多重子域名的环境，轻阅读下方的 **options ndots:__n__** 来避免中间人工具，以及非必要的根 DNS 服务器流量。注意该过程可能较慢，并当所罗列的域名的服务器并不在本地时，生成大量的网络流量，并且若当某个域名没有可用的服务器时，请求会超时。 +
若有多个 `search` 指令，则会使用最后一个出现的搜索列表。 +
在 glibc 2.25 和之前的版本，搜索列表被限制为 6 个域，且总长度为 256 个字符。在 glibc 2.26 之后，搜索列表就没有限制了。 +
`domain` 指令是 `search` 指令的遗弃名称，该指令仅能处理一个搜索列表条目。
