= DNSMASQ

== 名称

dnsmasq - 一个轻量的 DHCP 以及缓存型 DNS 服务器。

== 语法

**dnsmasq** __[选项]...__

== 描述

dnsmasq 是一个轻量的 DNS、TFTP、PXE、路由宣告及 DHCP 服务器。它意在为局域网提供耦合的 DNS 和 DHCP 服务。

dnsmasq 接受 DNS 请求，要么从一个小型的、局部的缓存回应请求，要么将它转发至一个真实的、递归的 DNS 服务器上。它读取 /etc/hosts 的内容，以解析未出现在全局 DNS 的本地主机名，并响应由 DHCP 所配置的主机的 DNS 请求。它可以作为一个或多个域名的权威 DNS 服务器存在，允许将本地名追加至全局 DNS 中。它也可以被配置未执行 DNSSEC 验证。

dnsmasq DHCP 服务器知此恨静态地址分发，以及多重网络。它会自动发送有意义的默认 DHCP 选项集，也可以被配置未发送任何所需要的 DHCP 选项集，包括 vendor-encapsulated 选项。它包含一个安全的、只读的 TFTP 服务器，允许 DHCP 主机执行 net/PXE 启动，同时也支持 BOOTP。对 PXE 的支持是全功能的，并包含一个代理模式，它支持向客户端发送 PXE 信息的同时把 DHCP 地址分配交由用另一个服务器执行。

dnsmasq DHCPv6 服务器提供了与 DHCPv4 服务器相同的特性，额外的，它包括了路由宣告，且支持一个不错的特性：它允许为使用 DHCPv4 的客户端命名，而仅对 IPv6 配置使用无状态自动配置。它也支持为子网分配地址（通过 DHCPv6 或者 RA），该子网是通过 DHCPv6 前缀授权动态授权的。

dnsmasq 在编写时谨记微型嵌入式系统。它的目标就是在支持功能的同时做到最小的内存印记，并允许不需要的功能从编译后的程序中隐去。

== 选项

[WARNING]
====
译者注：本段**仅记录翻译者本人**认为较为有用的选项，完整列表请参阅 +
link:https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html[]
====

注意，通常来说，允许丢失参数，者将关闭该功能，比如 `--pid-file` 将金庸写入一个 PID 文件。在 BSD 上，除非链接了 GNU getopt 库，否则选项的长形式无法在命令行中使用；但依旧可以在配置文件中识别。
