= DNSMASQ
:resolv_conf_man5: xref:85.1、resolv.conf.adoc[resolv.conf(5)]

== 名称

dnsmasq - 一个轻量的 DHCP 以及缓存型 DNS 服务器。

== 语法

**dnsmasq** __[选项]...__

== 描述

dnsmasq 是一个轻量的 DNS、TFTP、PXE、路由宣告及 DHCP 服务器。它意在为局域网提供耦合的 DNS 和 DHCP 服务。

dnsmasq 接受 DNS 请求，要么从一个小型的、局部的缓存回应请求，要么将它转发至一个真实的、递归的 DNS 服务器上。它读取 /etc/hosts 的内容，以解析未出现在全局 DNS 的本地主机名，并响应由 DHCP 所配置的主机的 DNS 请求。它可以作为一个或多个域名的权威 DNS 服务器存在，允许将本地名追加至全局 DNS 中。它也可以被配置未执行 DNSSEC 验证。

dnsmasq DHCP 服务器知此恨静态地址分发，以及多重网络。它会自动发送有意义的默认 DHCP 选项集，也可以被配置未发送任何所需要的 DHCP 选项集，包括 vendor-encapsulated 选项。它包含一个安全的、只读的 TFTP 服务器，允许 DHCP 主机执行 net/PXE 启动，同时也支持 BOOTP。对 PXE 的支持是全功能的，并包含一个代理模式，它支持向客户端发送 PXE 信息的同时把 DHCP 地址分配交由用另一个服务器执行。

dnsmasq DHCPv6 服务器提供了与 DHCPv4 服务器相同的特性，额外的，它包括了路由宣告，且支持一个不错的特性：它允许为使用 DHCPv4 的客户端命名，而仅对 IPv6 配置使用无状态自动配置。它也支持为子网分配地址（通过 DHCPv6 或者 RA），该子网是通过 DHCPv6 前缀授权动态授权的。

dnsmasq 在编写时谨记微型嵌入式系统。它的目标就是在支持功能的同时做到最小的内存印记，并允许不需要的功能从编译后的程序中隐去。

== 选项

注意，通常来说，允许丢失参数，者将关闭该功能，比如 `--pid-file` 将金庸写入一个 PID 文件。在 BSD 上，除非链接了 GNU getopt 库，否则选项的长形式无法在命令行中使用；但依旧可以在配置文件中识别。

--test::
读取配置文件并检查语法。若退出码为 0，则可用，否则不可用。不会启用 dnsmasq。

-w, --help::
显示全部命令行选项。`--help dhcp` 将显示已知的 DHCPv4 配置选项，`--help dhcp6` 将显示 DHCPv6 选项。

-h, --no-hosts::
不要读取 /etc/hosts 中的主机名。

-H, --addn-hosts=<file>::
额外的主机文件。同时读取指定的文件和 /etc/hosts。若给出了 `--no-host`，那么仅读取所指定的文件。该选项可指定多次来追加多个 hosts 文件。若给定了一个文件夹，则读取文件夹中的所有文件。

--hostsdir=<path>::
读取目录中的全部 hosts 文件。新加入的文件或者修改过的文件会被自动读取。参见 `--dhcp-hostsdir` 了解详情。

-E, --expand-hosts::
向 /etc/hosts 中的简单名称追加域名，如同 DHCP 发送的名称一样。注意这不适用于 cnames、PTR 记录、TXT 记录中的域名。

-T, --local-ttl=<time>::
当返回来自 /etc/hosts、配置文件、DHCP 租用文件的信息时，dnsmasq 默认会将 time-to-live 字段设置为 0，表示请求者自身不应该缓存信息。该设置在几乎全部的情况下都是正确的。该选项允许指定这些返回的 time-to-live（单位为秒）。它能降低服务器的负载，但会在在部分情况下导致客户端使用过期的数据。

--dhcp-ttl=<time>::
同 `--local-ttl`，但仅影响回复自 DHCP 租用的信息。如果两者都给出，`--dhcp-ttl` 应用于 DHCP 信息，`--local-ttl` 应用于其它。将该值设置为 0 将会消去 `--local-ttl` 对 DHCP 的影响。

--neg-ttl=<time>::
来自上游服务器的否定回答中的 SOA 记录通常包含 time-to-live 信息，该信息被 dnsmasq 用于缓存。若上游服务器隐去了该信息，dnsmasq 就不会缓存该信息。该选项给出了否定回答的默认 time-to-live 值（以秒计），当否定回复缺少 SOA 记录，dnsmasq 就会使用该选项的值来缓存记录。

--max-ttl::
设置将要发送给客户端的最大 TTL 值。若真实的 TTL 值比该值低，那么将向客户端发送该选项指定的最大 TTL。实际的 TTL 会存放在缓存中来防止对上游 DNS 服务器的冲击。

--max-cache-ttl=<time>::
设置缓存中的条目的最大 TTL 值。

--min-cache-ttl=<time>::
当缓存它们时，将 short TTL 值扩大至该值。TTL 值。注意，通常来说，人工扩大 TTL 的值都是坏注意，除非有充分的理由，并了解自己在做什么，否则不要使用它。dnsmasq 将该选项的值限制在了 1 小时，该限制仅能通过重编译修改。

--auth-ttl=<time>::
设置来自权威服务器的回答的 TTL 的值。

-k, --keep-in-forground::
不要像通常启动一样启动后就切入后台运行。它用于让 dnsmasq 运行在 daemontools 或 lauchd 的管理下。

-d, --no-daemon::
debug 模式：不要 fork 到后台，不要写入一个 pid 文件，不要修改 uid，在接到 SIGUSR1 后生成一个完整的 cache dump，同时向 stderr 和 syslog 写入日志，不要 fork 出新的进程来处理 TCP 请求。注意该选项仅用于 debug，要在生产环境中阻止 dnsmasq 自身的后台化，请使用 `--keep-in-forground`。

-q, --log-queries::
将 dnsmasq 处理的 DNS 请求的结果记录入日志。当收到 SIGUSR1 时，生成一个完整的 cache dump。若给定了参数 `extra`，比如 `--log-queries=extra`，那么会在日志的行首提供额外的信息。它包含了一个序列号，以及与序列号绑定的日志行，这些行包含独立的请求以及请求者的 IP 地址。

-8， --log-facility=<facility>::
dnsmasq 将把 syslog 条目发送给 __facility__，默认为 DAEMON，在 debug 模式中为 LOCAL0。若 __facility__ 至少包含一个 `/` 字符，那么该值被认为是文件名，dnsmasq 将向给定文件而非 syslog 写入日志。若 __facility__ 为 `-`，那么 dnsmasq 将日志写入 stderr。（在读取配置文件时产生的错误依旧会进入 syslog，但一次成功的启动的所有输出、以及运行时的全部输出都将排他地进入文件）。当向文件记录日志时，dnsmasq 将在收到 SIGUSR2 时关闭并重开文件。它允许日志文件被 rotate，而不需要停止 dnsmasq。

--log-async[=<lines>]::
启用异步日志写入，并可选地设置当 syslog 缓慢时，dnsmasq 可以队列的行的数量。dnsmasq 可以异步地写入日志：它允许 dnsmasq 继续其功能，而非被 syslog 阻塞运行，并允许 syslog 使用 dnsmasq 来查询 DNS，而不必冒生成死锁的风险。若日志行的队列已满，那么 dnsmasq 会记录该溢出，并记录丢失的信息的数量。默认的队列长度为 5，恰当的取值范围应该在 5 至 25 之间，最大值限制在了 100。

-x, --pid-file=<path>::
指定 dnsmasq 用于记录 pid 的文件的路径。通常为 `/var/run/dnsmasq.pid`

-u, --user=<username>::
指定在 dnsmasq 启动后，要切换至的用户。通常情况下，dnsmasq 必须以 root 身份启动，但在启动后，它就会抛弃 root 身份，并以另一个用户的 id 运行。该用户通常为 **nobody**，也可以通过该选项切换。

-g, --group=<groupname>::
指定 dnsmasq 运行时使用的组。若可用，则默认为 **dip**，这是为了访问 `/etc/ppp/resolv.conf`，而该文件通常并不是任何账户可读的。

-v, --version::
打印版本号。

-p, --port=<port>::
监听端口号 __port__ 而非标准 DNS 端口（53）。设置为 0 将完全关闭 DNS 功能，仅留下 DHCP 和/或 TFTP。

-P, --edns-packet-max=<size>::
指定被 DNS 转发者支持的最大 EDNS.0 UDP 包大小。默认为 4096，也是 RFC5625 的推荐大小。

-Q, --query-port=<query_port>::
用指定的 UDP 端口号 __query_port__、而非随机端口发送出站 DNS 请求，并监听其回复。注意，使用该选项将导致 dnsmasq 对 DNS 嗅探攻击的安全性下降，但可能提高速度并降低资源占用。将该值设置为 0 将导致 dnsmasq 使用由 OS 分配的单一端口：该行为在 2.43 版本前为默认行为。

--min-port=<port>::
不要使用小于该端口号的端口作为出站 DNS 请求的源端口。dnsmasq 将选择随机端口作为外部端口：当指定该选项后，所使用的端口将永远比指定的值大。对于防火墙后的系统很有用。默认值为 1024。

--max-port=<port>::
使用小于该端口号的端口作为出站 DNS 请求的源端口。nsmasq 将选择随机端口作为外部端口：当指定该选项后，所使用的端口将永远比指定的值小。对于防火墙后的系统很有用。

-i, --interface=<interface name>::
仅监听所指定的一个或多个接口。当使用 `--interface` 选项时，dnsmasq 会自动追加回环接口至接口列表。若不指定 `--interface` 或 `--listen-address` 选项，那么 dnsmasq 将监听除了由 `--except-interface` 选项给出的接口之外的全部可用接口。在 Linux 上，当 `--bind-interfaces` 或者 `--bind-dynamic` 起效，将识别 IP 别名接口标签（比如 **eth1:0**），而非接口名。在简化的情况下，当一个接口仅有一个地址时，它们指向同一个事情，但当一个接口具有多个地址时，它允许控制接受哪些地址。在默认的模式下，也可以使用 `--listen-address` 达到相同的效果。一个简单的通配符——一个尾缀的 `*`——可以用在 `--interface` 以及 `--expect-interface` 选项中。

-I, --except-interface=<interface name>::
不要监听指定的接口。注意，`--listen-address`、`--interface` 以及 `--except-interface` 选项的指定顺序并不重要，因为 `--except-interface` 选项将永远覆盖其它的。`--listen-address` 中描述的接口标签在这里同样适用。

--auth-server=<domain>,[<interface>|<ip-address>...]::
对到达特定接口或地址的请求启用 DNS 权威模式。注意这些接口或地址不需要在 `--interface` 或 `--listen-address` 配置中指出，`--auth-server` 将在特定接口上覆盖这些选项，并提供一个不同的 DNS 服务。__domain__ 为 **glue 记录**。它应该将全局 DNS 解析为指向 dnsmasq 所监听的 A 和/或 AAAA 记录。当指定接口时，它可以使用 `/4` 或者 `/6` 来指明仅监听与该接口绑定的 IPv4 或 IPv6 地址。由于任何定义好的权威 zone 同样作为受 dnmasq 支持的通常的递归 DNS 服务的一部分，所以也可以以无接口或地址，仅指定一个主外部名称服务器的方式声明 `--auth-server`。

--local-service::
仅接受地址在本地子网上的主机的 DNS 请求，比如服务器的接口所在的一个子网。该选项仅在没有 `--interface`、`--except-interface`、`--listen-address`、`--auth-server` 选项时起效。它应该在安装时设置为默认值，来允许未配置的安装有用，且远离 DNS 放大攻击。

-2， --no-dhcp-interface=<interface name>::
不要在指定的界面上提供 DHCP 或 TFTP，但会提供 DNS 服务。

-a, --listen-address=<ipaddr>::
监听给定的一个或多个地址。`--interface` 和 `--listen-address` 也可一同指定，此时全部指定的接口和地址会被使用。注意若不指定 `--interface`，但指定了 `--listen-address`，那么 dnsmasq 就不会自动监听回环接口。要监听它，它的 IP 地址 127.0.0.1 必须要明确地在 `--listen-address` 选项中指出。

-z, --bind-interfaces::
在支持的系统上，dnsmasq 会绑定通配符地址，即便它仅会监听一些地址。此后，它会丢掉那些不应该被回复的请求。这有助于平顺地工作，即便接口可能会出现、消失或者改变地址。该选项会强制 dnsmasq 仅真实地绑定它会监听的接口。该选项有用的情景大概只有一个，就是在同一个机器上还运行着另一个名称服务器（或另一个 dnsmasq 实例）。启用该选项同样会让同一个机器上可以运行多个提供 DHCP 服务的 dnsmasq 实例。

--bind-dynamic::
启用一个网络模式介于 `--bind-interface` 和默认模式之间的模式。dnsmasq 绑定独立接口的地址，允许多个 dnsmasq 实例，但如果新接口或地址出现，它会自动监听它们（受到访问控制配置的限制）。者让动态创建的接口与默认接口一样能工作。实现该选项要求非标准的网络 API，它仅出现在 Linux 上。其它平台则回落至 `--bind-interfaces` 模式。

-y, --localise-queries::
从 /etc/hosts 和 `--interface-name` 返回 DNS 请求的回答，其取决于请求接受的接口。若一个名字关联了多个地址，且其中至少有一个地址与请求发送的接口在相同的子网，那么仅返回在那个子网上的地址。它允许服务器在 /etc/hosts 中为它的每个接口设置地址，而主机则能依照它所在的网络获得正确的地址。当前该设置仅限 IPv4。

-b, --bogus-priv::
虚空化对私有地址的反向查询。全部对私有 IP 范围（比如 192.168.x.x）的反向查询，若无法再 /etc/hosts 或者 DHCP 租用文件中找到的，均会回复 **no such domain**，而不会转发至上游。受影响的 IPv4 以及 IPv6 前缀由 RFC6303 中的列表给出。

-V, --alias=[<old-ip>]|[<start-ip>-<end-ip>],<new-ip>[,<mask>]::
修改由上游名称服务器返回的 IPv4 地址；用 __new-ip__ 替换 __old-ip__。若给出了可选的 __mask__ 那么任何可以匹配该带掩码的 IP 的地址都会被重写。所以，对于 `--alias=1.2.3.0,6.7.8.0,255.255.255.0` 将会把 `1.2.3.56` 映射为 `6.7.8.56`。这就是被 Cisco PIX 路由称为 DNS doctoring 的东西。若旧 IP 以 IP 范围的形式给定，则仅有该范围内的 IP，而非整个子网会被重写。于是 `--alias=192.168.0.10-192.168.0.40,10.0.0.0,255.255.255.0` 将会把 `192.168.0.10` 至 `192.168.0.40` 映射至 `10.0.0.10` 到 `10.0.0.40`

-B, --bogus-nxdomain=<ipaddr>::
将包含指定 IP 地址的回复替换为 **no such domain** 回复。这是为了消去 Verisign 在 2003 年 9 月开始实行的迷惑操作：它们考试对于未注册的名称的请求返回一个广告页的地址，而非正确的 `NXDOMAIN` 响应。该选项告诉 dnsmasq 当它看到这种行为时应该伪造正确的响应。在 2003 年 9 月时 Verisign 返回的地址为 64.94.110.11。

--ignore-address=<ipaddr>::
忽略包含了指定地址的 A 记录的回复。不会生成错误，dnsmasq 简单地监听其它回复。在正确的回复到达前，它可以使用快速伪造对于特定域名的回复的方法来抵御封锁策略。

-f, --filterwin2k::
较新版本的 windows 会周期性地发送 DNS 请求，这些请求不会从公共 DNS 上获得什么有意义的回复，但会触发按需拨号链接而导致问题。启用该选项会过滤这类请求。会阻止的请求为具有 SOA 和 SRV 类型的请求，以及类型为 ANY、请求的名称中具有下划线的请求，也就是 LDAP 请求。

-r, --resolv-file=<file>::
从文件 __file__ 而非 /etc/resolv.conf 中读取上游名称服务器的 IP 地址。对于该文件的格式参见 {resolv_conf_man5}。与 dnsmasq 相关的行仅为 namserver 行。可以让 dnsmasq 轮询多个 resolv.conf 文件以拉取信息，指定的首个文件名将替换默认的，其后的每一个都会追加在列表后。仅在轮询时允许；会使用文件的最近修改时间。

-R, --no-resolv::
不要读取 /etc/resolv.conf。仅从命令行以及 dnsmasq 配置文件中读取上游服务器。

-1, --enable-dbus[=<service-name>]::
允许 dnsmasq 的配置由 DBus 方法调用修改。可以被修改的配置为上游 DNS 服务器（以及对应的域名）以及清空缓存。需要 dnsmasq 构件为支持 DBus。若给出了服务名，那么 dnsmasq 将提供该名称的服务，而非默认值 **uk.org.thekelleys.dnsmasq**。

--enable-ubus[=<service-name>]::
启用 dnsmasq UBus 接口。DHCPACK 和 DHCPRELEASE 事件会触发它在 UBus 上发送信息。而且它还提供 mdetrics。需要 dnsmasq 构件为支持 UBus。若给出了服务名，那么 dnsmasq 将提供该名称的服务，而非默认值 **dnsmasq**。

-o, --strict-order::
默认情况下，dnsmasq 会向任何一个已知的上游服务器发送请求，且偏好其中已知在线的服务器。设置该标示强制让 dnsmasq 严格按照 /etc/resolv.conf 中定义的服务器顺序逐次请求每个服务器。

--all-servers::
默认情况下，若 dnsmasq 具有多个可用的上游服务器，它仅会向其中一个服务器发送请求。设置该标示会强制 dnsmasq 向全部可用的服务器发送请求。首个回复请求的服务器的回复会被发送回原始的请求者。

--dns-loop-detect::
启用检测 DNS 转发回环的代码；比如向上游服务器发送的请求最终会作为一个新的请求返回该 dnsmasq 实例。该流程会通过生成一个 `<hex>.test` 形式的 TXT 请求，并向每个上游服务器发送该请求实现。__hex__ shi 发送请求的 dnsmasq 和接收该请求的上游服务器编码而成的 UID。若请求被发回了发送它的服务器，则会停用该上游服务器，并记录日志。每次上游服务器的变动，都会重新检测它们，包含以前被停用的服务器。

--stop-dns-rebind::
拒绝（并记录）上游名称服务器返回的在私有范围内的地址。它阻止了一个防火墙后的浏览器侦察本地局域网上的机器的攻击。对于 IPv6，私有让位包含了 IPv4 私有空间映射、本地链路（LL）地址，以及本地站点（ULA）地址。

--rebind-localhost-ok::
不对 127.0.0.0/8 和 ::1 执行 rebind 检查。这些地址由实时黑洞服务器返回，封锁它们也许会阻止这些服务。

--rebind-domain-ok=[<domain>]|[/<domain>/[<domain>/]]::
不要检测和阻止对于指定的域名的 dns-rebind 请求。如同 `--server` 的语法，参数可以为单一域名，或者多个由 `/` 包围的域名，比如 `--rebind-domain-ok=/domain1/domain2/domain3/`

-n, -no-poll::
不要轮询 /etc/resolv.conf 的修改。

--clear-on-reload::
每当重读 /etc/resolv.conf 或者通过 DBus 重设上游服务器时，清除 DNS 缓存。当新名称服务器具有的数据与缓存中的不同时十分有用。

-D, --domain-needed::
告诉 dnsmasq 不要将直接名称（plain name）——不含点号或者域名部分——的 A 或者 AAAA 请求转发给上游名称服务器。若名称不能从 /etc/hosts 或者 DHCP 中找到，那么返回回答 not found。

-S, --local, --server=[/[<domain>]/[domain/]]<ipaddr>[\#<port>]][@<source-ip>|<interface>[#<port>]]::
直接指定上游服务器的 IP 地址。设置该标示并不会抑制读取 /etc/resolv.conf，要抑制读取，请使用 `--no-resolv`。若给出了一个或多个可选域名，那么这些服务器仅用于解析这些域名，且这些域名也仅由这些服务器解析。它意在用于私有名称服务器：若在你的网络上有一个地址为 192.168.1.1 的名称服务器，其用于处理具有 xxx.interal.thekelleys.org.uk 格式的地址，那么给定标示 `--server=/internal.thekelleys.org.uk/192.168.1.1` 会让全部查询内部机器的请求流向该名称服务器，其他的依旧使用 /etc/resolv.conf 中指定的服务器。会关闭对这类私有服务器的 DNSSEC 校验，除非为该域名指定了 `--trust-anchor`。若指定了空域名，`//` 具有特殊的含义——仅为未限定名称，比如名称中不具有点号。可以使用非标准端口作为 IP 地址的组成部分，用 `#` 分隔。可以指定多个 `--server`，每次指定都需要对应的 __domain__ 或者 __ipaddr__。 +
更详细的域名会覆盖不详细的域名，所以 `--server=/google.com/1.2.3.4 --server=/www.google.com/2.3.4.5` 将把 *.google.com 的请求发送至 1.2.3.4，但会单独把 *www.google.com 的请求发送至 2.3.4.5。 +
特殊的服务器地址 `#` 表示 使用标准服务器，所以 `--server=/google.com/1.2.3.4 --server=/www.google.com/#` 将把 *.google.com 的请求发送至 1.2.3.4，而让 *www.google.com 的请求通常转发。 +
也可以指定域名而不指定 IP 地址；这告诉 dnsmasq 该域名为本地域名，它可以从 /etc/hosts 和 DHCP 查询地址，但永远不要将该域名的查询转发至上游服务器。`--local` 为 `--server` 的同义词，意在明确配置文件中的这种情况。 +
IPv6 地址可以包含一个 `%interface` 限定 id，比如 fe80::202:a412:4512:7bbf%eth0。 +
可选的在 `@` 之后的字符串告诉 dnsmasq 如何设置到该名称服务器的请求的源。它可以是 IP 地址、一个界面名，或者两者皆有。IP 地址应该属于 dnsmasq 所运行的机器，否则 server 行就会被忽略，并记录日志。若给定了一个接口名，那么发给服务器的请求会强制走所指定的接口；若给定了一个 IP 地址，那么请求的源地址就会设为该地址；若两者皆设置了，那么 IP 地址和接口名均会用于限制发送至服务器的请求。若指定了源地址，那么会忽略任何为该服务器设置的 `query-port` 选项，这是由于可以直接在源地址中指定端口。强制请求走某个端口并非在全部 dnsmasq 支持的平台上可用。

--rev-server=<ip-address>/<prefix-len>[,<ipaddr>][\#<port>][@<source-ip>|<interface>[#<port>]]::
功能与 `--server` 一样，但提供了语法糖让指定 address-to-name 的请求更简单。举例来说 `--rev-server=1.2.3.0/24,192.168.0.1` 全等于 `--server=3.2.1.in-addr.arpa/192.168.0.1`

-A, --address=/<domain>[/<domain>...]/[<ipaddr>]::
指定域名中的主机对应的 IP 地址。域名中的请求永远不会被转发，并永远回复为给定的 IPv4 或 IPv6 地址。要同时为域名指定 IPv4 和 IPv6 地址，多次使用 `--adress` 标示。要在单个请求中包含多个 IP 地址，请转而使用 `--addn-hosts=<path>`。注意对于独立（individual）名称，/etc/hosts 和 DHCP 租用会覆盖该设置。一个常用的方法是将条目 doubleclick.net 域名跳转至更友好的局域网 web 服务器上，来防止顶部广告。域名指定与 `--server` 相同，且新增 `/\#/` 表示任意域名。因此 `--address=/#/1.2.3.4` 会对无法从 /etc/hosts 和 DHCP 中回复的请求直接返回 **1.2.3.4**，而并不会转发至 `--server` 指定的上游服务器。对于 `--server`，一个或多个不具有地址的域名将返回 no-such-domain 回答，所以 `--address=/example.com/` 等价于 `--server=/example.com/`，并对 example.exe 以及其子域名返回 NXDOMAIN。由 `#` 指定的地址会被翻译为 NULL 地址 **0.0.0.0** 以及等价的 IPv6 地址 **::**，于是 `--address=/example.com/#` 将会对 example.com 以及其子域名返回 NULL 地址。这部分是 `--address=/example.com/0.0.0.0` 以及 `--address=/example.com/::` 的语法糖，但因为合并了两者而减少了配置文件的行数。注意 NULL 地址通常与 localhost 的作用相同，因此要注意查找这些名字的客户端最后都容易和自己对话。

--ipset=/<domain>[/<domain>...]/<ipset>[,<ipset>...]::
将一个或多个请求的域名所解析出来的 IP 地址放入指定的 Netfilter IP set 中。若给出了多个 setname，那么会在每个 set 中放置它们，但也会受到 IP set 的限制（IPv4 地址不能放在 IPv6 IP set 中，反之亦然）。域名和子域名的配置方法同 `--address`。这些 IP sets 必须预先存在。参见 **ipset(8)** 了解更多详情。

-m, --mx-host=<mx name>[[,<hostname>],<preference>]::
返回一个名为 __mx name__ 的 MX 记录，该记录指向（若给出）给出的主机名，或者在 `--mx-target` 指定的主机，若均为指定，则指向 dnsmasq 所运行的主机。默认值长用于将邮件从一个本地系统上转发至一个中心服务器上。__preference__ 值为可选的，若不给定默认为 1.可以为一个主机指定多条 MX 记录。

-t, --mx-target=<hostname>::
指定 dnsmasq 返回的默认的 MX 记录的目标。参见 `--mx-host`。若给定了 `--mx-target` 但不给定 `--mx-host`，dnsmasq 返回一个 MX 记录，该记录包含了 dnsmasq 所在机器的主机名的 MX 目标。

-e, --selfmx::
对每个本地机器都返回一条指向其自身的 MX 记录。本地机器存在与于 /etc/hosts 和 DHCP 租用中。

-L, --localmx::
对于每个本地机器都返回一条指向 `--mx-target` 给出的主机（或者 dnsmasq 运行的主机）的 MX 记录。本地机器存在与于 /etc/hosts 和 DHCP 租用中。

-W, --srv-host=<_service>.<_port>.[<domain>],[<target>[,<port>[,<priority>[,<weight>]]]]::
返回一个 SRV DNS 记录。参见 RFC2782 了解详情。若不给出，则由 `--domain` 给出。默认的目标域名为空，默认的端口为 1，默认的权重和优先级为 0。要小心从 BIND zone 文件转换而来的数据：port、weight、priority 数字的顺序不同。可以为一个 service/domain 设置多于一个的 SRV 记录，所有的匹配值均会被返回。

--host-record=<name>[,<name>....],[<IPv4-address>][,<TTL>]::
向 DNS 添加 A、AAAA、PTR 记录。它向 DNS 中追加一个或多个关联了名称的 A（IPv4）或 AAAA（IPv6）记录。一个名称可以出现在多个 --host-record 中，此时它会对应多个地址。仅有第一个创建了 PTR 记录的地址会被链接至名称。于读取 hosts 文件的规则相同。`--host-record` 选项先于 host 文件读取，如果在该选项中出现，也同时出现在 hosts 文件，那么他就会阻止 PTR 记录的生成。与 hosts 文件不同，名称不会被扩展，即便 `--expand-hosts` 有效。短名和长名可以同时出现在一个 `--host-record` 中，比如 `--host-record=laptop,laptop.thekelleys.org,192.168.0.1,1234::100`。 +
如果给出了 time-to-live，那么它会覆盖默认值，默认值要么是 0 要么是 `--local-ttl`。该值为正整数，且以秒计数。

-Y, --txt-record=<name>[[,<text>],<text>]::
返回一个 TXT DNS 记录。TXT 记录的值为一系列字符串，因此可以包含任何用逗号分隔数字；可以用引号将逗号放入字符串。注意单个字符串的最大长度为 255 个字符，大于该长度的字符串将被分为长度为 255 个字符的分块。

-ptr-record=<name>[,<target>]::
返回一个 PTR DNS 记录。

--naptr-record=<name>,<order>,<preference>,<flags>,<service>,<regexp>[,<replacement>]::
返回一个 RFC3403 中定义的 NAPTR DNS 记录。

--caa-record=<name>,<flags>,<tag>,<value>::
返回一个 RFC6844 定义的 CAA DNS 记录。
