= DNSMASQ

== 名称

dnsmasq - 一个轻量的 DHCP 以及缓存型 DNS 服务器。

== 语法

**dnsmasq** __[选项]...__

== 描述

dnsmasq 是一个轻量的 DNS、TFTP、PXE、路由宣告及 DHCP 服务器。它意在为局域网提供耦合的 DNS 和 DHCP 服务。

dnsmasq 接受 DNS 请求，要么从一个小型的、局部的缓存回应请求，要么将它转发至一个真实的、递归的 DNS 服务器上。它读取 /etc/hosts 的内容，以解析未出现在全局 DNS 的本地主机名，并响应由 DHCP 所配置的主机的 DNS 请求。它可以作为一个或多个域名的权威 DNS 服务器存在，允许将本地名追加至全局 DNS 中。它也可以被配置未执行 DNSSEC 验证。

dnsmasq DHCP 服务器知此恨静态地址分发，以及多重网络。它会自动发送有意义的默认 DHCP 选项集，也可以被配置未发送任何所需要的 DHCP 选项集，包括 vendor-encapsulated 选项。它包含一个安全的、只读的 TFTP 服务器，允许 DHCP 主机执行 net/PXE 启动，同时也支持 BOOTP。对 PXE 的支持是全功能的，并包含一个代理模式，它支持向客户端发送 PXE 信息的同时把 DHCP 地址分配交由用另一个服务器执行。

dnsmasq DHCPv6 服务器提供了与 DHCPv4 服务器相同的特性，额外的，它包括了路由宣告，且支持一个不错的特性：它允许为使用 DHCPv4 的客户端命名，而仅对 IPv6 配置使用无状态自动配置。它也支持为子网分配地址（通过 DHCPv6 或者 RA），该子网是通过 DHCPv6 前缀授权动态授权的。

dnsmasq 在编写时谨记微型嵌入式系统。它的目标就是在支持功能的同时做到最小的内存印记，并允许不需要的功能从编译后的程序中隐去。

== 选项

[WARNING]
====
译者注：本段**仅记录翻译者本人**认为较为有用的选项，完整列表请参阅 +
link:https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html[]
====

注意，通常来说，允许丢失参数，者将关闭该功能，比如 `--pid-file` 将金庸写入一个 PID 文件。在 BSD 上，除非链接了 GNU getopt 库，否则选项的长形式无法在命令行中使用；但依旧可以在配置文件中识别。

--test::
读取配置文件并检查语法。若退出码为 0，则可用，否则不可用。不会启用 dnsmasq。

-w, --help::
显示全部命令行选项。`--help dhcp` 将显示已知的 DHCPv4 配置选项，`--help dhcp6` 将显示 DHCPv6 选项。

-h, --no-hosts::
不要读取 /etc/hosts 中的主机名。

-H, --addn-hosts=<file>::
额外的主机文件。同时读取指定的文件和 /etc/hosts。若给出了 `--no-host`，那么仅读取所指定的文件。该选项可指定多次来追加多个 hosts 文件。若给定了一个文件夹，则读取文件夹中的所有文件。

--hostsdir=<path>::
读取目录中的全部 hosts 文件。新加入的文件或者修改过的文件会被自动读取。参见 `--dhcp-hostsdir` 了解详情。

-E, --expand-hosts::
向 /etc/hosts 中的简单名称追加域名，如同 DHCP 发送的名称一样。注意这不适用于 cnames、PTR 记录、TXT 记录中的域名。

-T, --local-ttl=<time>::
当返回来自 /etc/hosts、配置文件、DHCP 租用文件的信息时，dnsmasq 默认会将 time-to-live 字段设置为 0，表示请求者自身不应该缓存信息。该设置在几乎全部的情况下都是正确的。该选项允许指定这些返回的 time-to-live（单位为秒）。它能降低服务器的负载，但会在在部分情况下导致客户端使用过期的数据。

--dhcp-ttl=<time>::
同 `--local-ttl`，但仅影响回复自 DHCP 租用的信息。如果两者都给出，`--dhcp-ttl` 应用于 DHCP 信息，`--local-ttl` 应用于其它。将该值设置为 0 将会消去 `--local-ttl` 对 DHCP 的影响。
