= dig - DNS 查找工具

[TIP]
====
翻译自 link:https://bind9.readthedocs.io/en/v9_17_9/manpages.html#dig-dns-lookup-utility[dig - DNS lookup utility]
====

== 语法

*dig* [@server] [*-b* address] [*-c* class] [*-f* filename] [*-k* filename] [*-m*] [*-p* port#] [*-q* name] [*-t* name] [*-v*] [*-x* addr] [*-y* [hmac:]name:key] [ [*-4*] | [*-6*] ] [name] [type] [class] [queryopt...]

*dig* [*-h*]

*dig* [global-queryopt] [query...]

== 描述

`dig` 是一个灵活的用于查询 DNS 名称服务器的工具。它执行 DNS 查找，并显示来自所请求的名称服务器返回的回答。大多数 DNS 管理员使用 `dig` 排查 DNS 问题，因为它灵活、便于使用、输出清晰。其他的查找工具的功能大概比 `dig` 的少。

虽然 `dig` 通常与命令行参数连用，但它也有一个批量操作模式用于从文件读取查找请求。当给出 `-h` 选项时，会打印出一个简略的命令行参数和选项的摘要。BIND 9 所实现的 `dig` 允许从命令行发出多个查找。

除非它被要求请求特定的名称服务器，否则 `dig` 会尝试每个列举在 `/etc/resolv.conf` 中的服务器。若不存在可用的服务器地址，那么 `dig` 将会向本机发送请求。

当不给出任何命令行参数或选线时，`dig` 执行对 `.`（也就是根域名）的 NS 请求。

可以通过 `${HOME}/.digrc` 设置每用户的 `dig` 默认值。读取该文件，并将该文件中的任何选项附在任何命令行参数之前。`-r` 选项关闭该特性，对于需要可预测行为的脚本很有用。

IN 和 CH 类型名与 IN 和 CH 顶级域名重叠。要么使用 `-t` 或者 `-c` 选项分别指定类型和层级，或者使用 `-q` 指定域名，或者使用 `IN.` 和 `CH.` 来查找该顶级域名。

== 简单用法

一个典型的 `dig` 调用如下所示：

[source, sh]
----
dig @server name type
----

其中：

`server`::
是要请求的名称服务器的名称或 IP 地址。它可以是 点-数字 格式的 IPv4 地址，或者 分号分隔 格式的 IPv6 地址。当提供给 `server` 参数是一个主机名，`dig` 首先解析该名称，之后再请求该名称服务器。

若不给出 `server` 参数，那么 `dig` 就会参考 `/etc/resolv.conf`；若找到了一个地址，则向那个地址的名称服务器发送请求。如果使用了 `-4` 或者 `-6` 选项，那么仅会尝试该限定对应的地址。若不存在可用的地址，那么 `dig` 向本机发送请求。会显示来自名称服务器的响应。

`name`::
将要被查找的资源记录的名称。

`type`::
指出将要查找什么类型——ANY、A、MX、SIG 等。`type` 可以为任意有效请求类型。若不给出 `type`，那么 `dig` 执行 A 记录查找。
