= dig - DNS 查找工具

[TIP]
====
翻译自 link:https://bind9.readthedocs.io/en/v9_17_9/manpages.html#dig-dns-lookup-utility[dig - DNS lookup utility]
====

== 语法

*dig* [@server] [*-b* address] [*-c* class] [*-f* filename] [*-k* filename] [*-m*] [*-p* port#] [*-q* name] [*-t* name] [*-v*] [*-x* addr] [*-y* [hmac:]name:key] [ [*-4*] | [*-6*] ] [name] [type] [class] [queryopt...]

*dig* [*-h*]

*dig* [global-queryopt] [query...]

== 描述

`dig` 是一个灵活的用于查询 DNS 名称服务器的工具。它执行 DNS 查找，并显示来自所请求的名称服务器返回的回答。大多数 DNS 管理员使用 `dig` 排查 DNS 问题，因为它灵活、便于使用、输出清晰。其他的查找工具的功能大概比 `dig` 的少。

虽然 `dig` 通常与命令行参数连用，但它也有一个批量操作模式用于从文件读取查找请求。当给出 `-h` 选项时，会打印出一个简略的命令行参数和选项的摘要。BIND 9 所实现的 `dig` 允许从命令行发出多个查找。

除非它被要求请求特定的名称服务器，否则 `dig` 会尝试每个列举在 `/etc/resolv.conf` 中的服务器。若不存在可用的服务器地址，那么 `dig` 将会向本机发送请求。

当不给出任何命令行参数或选线时，`dig` 执行对 `.`（也就是根域名）的 NS 请求。

可以通过 `${HOME}/.digrc` 设置每用户的 `dig` 默认值。读取该文件，并将该文件中的任何选项附在任何命令行参数之前。`-r` 选项关闭该特性，对于需要可预测行为的脚本很有用。

IN 和 CH 类型名与 IN 和 CH 顶级域名重叠。要么使用 `-t` 和 `-c` 选项分别指定类型和类别，并使用 `-q` 指定域名，或者使用 `IN.` 和 `CH.` 来查找该顶级域名。

== 简单用法

一个典型的 `dig` 调用如下所示：

[source, sh]
----
dig @server name type
----

其中：

__server__::
是要请求的名称服务器的名称或 IP 地址。它可以是 点-数字 格式的 IPv4 地址，或者 分号分隔 格式的 IPv6 地址。当提供给 `server` 参数是一个主机名，`dig` 首先解析该名称，之后再请求该名称服务器。 +
若不给出 `server` 参数，那么 `dig` 就会参考 `/etc/resolv.conf`；若找到了一个地址，则向那个地址的名称服务器发送请求。如果使用了 `-4` 或者 `-6` 选项，那么仅会尝试该限定对应的地址。若不存在可用的地址，那么 `dig` 向本机发送请求。会显示来自名称服务器的响应。

__name__::
将要被查找的资源记录的名称。

__type__::
指出将要查找什么类型——ANY、A、MX、SIG 等。`type` 可以为任意有效请求类型。若不给出 `type`，那么 `dig` 执行 A 记录查找。

== 选项

-4::
该选项指出仅使用 IPv4。

-6::
该选项指出仅使用 IPv6。

-b __address__[#__port__]::
该选项设置请求的源 IP 地址。__address__ 必须为主机网络接口上的一个有效地址，或者为 `0.0.0.0` 或 `::`。可以额外地通过 `#port` 指定一个端口。

-c __class__::
该选项设置请求的类别。默认的 __class__ 为 IN；其它的类别有 HS 对应的 Hesiod 记录，或者 CH 对应的 Chaosnet 记录。

-f __file__::
该选项设置批处理模式，在此模式下 `dig` 从给出的 __file__ 中读取要处理的查找请求。文件中的每一行都应该以 `dig` 命令行界面所使用的方式来指定。

-k __keyfile__::
该选项告诉 `named` 用一个给定文件中读取的密钥以 TSIG 签名请求。密钥文件可以通过 `tsig-keygen` 生成。在 `dig` 中使用 TSIG 认证，所请求的名称服务器需要知道密钥以及所使用的算法。在 BIND 中，这些信息可以通过在 `named.conf` 中提供合适的 `key` 以及 `server` 语句来实现。

-m::
该选项启用内存使用排错。

-p __port__::
该选项将请求发送至服务器的非标准端口，而非默认端口 53。该选项用于测试被配置为监听非标准端口上的请求的名称服务器。

-q __name__::
该选项指定要请求的名称服务器。该选项方便将 __name__ 与其它参数区分开来。

-r::
该选项指出不应该读取来自 `${HOME}/.digrc` 的选项。它常用于需要可预测行为的脚本。

-t __type__::
该选项指出要请求的资源记录类型。可以为任何有效的请求类型。若它是被 BIND 9 支持的资源记录类型，那么它就可以以类型助记（比如 `NS` 或者 `AAAA`）的形式指定。默认请求类型为 `A`，除非使用了表示反向查询的 `-x` 选项。可以指定类型 `AXFR` 来请求 zone 转换。当需要增量 zone 转换（`IXFR`）时，设置 __type__ 为 `ixfr=N`。增量 zone 转换包含了自 zone 的 SOA 记录的序列号为 __N__ 之后的的全部修改。 +
全部的资源记录类型都可以以 `TYPEnn` 的形式表达，其中 __nn__ 为类型的数字。若是 BIND 9 不支持的资源记录类型，那么结果将以 link:https://tools.ietf.org/html/rfc3597.html[RFC 3597] 中描述的显示。

-u::
该选项指出打印出的请求时间应该以微秒而非毫秒作为单位。

-v::
该选项会打印版本号并退出。

-x __addr__::
该选项设置简单反向查询，以将地址对应名称。__addr__ 是一个 点-数字 格式的 IPv4 地址，或者 分号分隔 的 IPv6 地址。当使用 `-x` 选项是，就不需要提供 __name__、__class__ 和 __type__ 参数了。`dig` 会自动执行名称类似 `94.2.0.192.in-addr.arpa` 的查询，并分别设置请求类型和类别为 PTR 和 IN。 IPv6 地址以 IP6.ARPA 域中的 nibble 格式查询。

-y [__hmac__:]__keyname__:__secret__::
该选项用给定的认证密钥以 TSIG 签名请求。__keyname__ 是密钥的名称，`secret` 是 base64 编码的分享密钥。__hmac__ 是密钥算法的名称；有效值为 `hmac-md5` `hmac-sha1` `hmac-sha224` `hmac-sha256` `hmac-sha384` `hmac-sha512`。若不指定 __hmac__，那么默认值为 `hmac-md5`；若 MD5 不可用，则默认值为 `hmac-sha256`。

[NOTE]
====
仅应该使用 `-k` 选项，而不应该使用 `-y` 选项，因为 `-y` 中分享密钥以明文形式出现在命令行参数中。它可能会在 `PS1` 中输出，或者由用户 shell 维护的历史文件中出现。
====
