= config

== 名称

openssl CONF 库配置文件

== 描述

OpenSSL CONF 库可被用于读取配置文件。该库可用于 OpenSSL 主（master）配置文件 `openssl.cnf`，还有比如 `SPKAC` 文件这样的地方，以及 `x509` 工具的认证扩展文件中。OpenSSL 的应用也可将 CONF 库用于它们自己的用途。

一个配置文件可以被分为多个段（section）。每个段都以一行 `[ 段名 ]` 作为起始，并以另一个段的起始或者文件结束作为结尾。一个段名可以包含字母、数字字符，以及下划线。

配置文件的第一个段比较特殊，被称为 `default`（默认）段。该段通常不会有名字，并从文件头一直延续至第一个具名段。当查找一个键（key）时，它先在具名段中查找，若找不到再在默认段查找。

环境变量会被映射至 `ENV` 段。

井号 `#` 表示注释的开始。

包含其他文件可以用 `.include` 指令（directive）后缀一个路径来实现。若路径指向一个文件夹，文件夹中所有以 `.cnf` 或 `.conf` 后缀的文件均会被包含进来。不支持目录下文件的递归包含。这意味着，被包含的文件也可以具有 `.include` 指令，但该指令只会包含指定目录下的常规文件。对目录的包含是基于 POSIX IO 的。

强烈建议在 `.include` 指令中使用绝对路径。相对路径是基于应用当前的工作路径的，除非包含 `.include` 指令的配置文件是应用特有的，否则它就不能正常工作。

可以在 `.include` 指令和路径之间添加可选的等号 `=` 以及白空格，来提高该配置文件对不支持 `.include` 语法的旧版 OpenSSL 的兼容性。旧版软件会对不加等号的配置报错，但会直接忽略加了等号的包含语句。

配置文件的每个段都包括了一系列型如 `键=值` 的键值对。

**__键__**字符串可以包含任意字母数字字符，以及少量的标点符号，例如 `.` / `,` / `;` / `_`。

**__值__**字符串是等号之后、行尾之前的字符串，任何首位的白空格都会被忽略。

值字符串会执行变量扩展。可以通过 `$var` 或者 `${var}` 的形式来产生：该形式会在当前的段中查找该键对应的变量值。也可以使 `$section::name` 或者 `${section:name}` 形式的语法来引用其他段的变量。以 `$ENV:name` 的形式来获取环境变量中的值。也可以用 `ENV:name` 来设置环境变量值，这种方法仅对调用 `CONF` 库来查找环境变量时有效，对于直接调用 getenv() 无效。在变量扩展后，值字符串的长度不应该超过 64k，否则会出错。

可以用任何形式的引号或者反斜线 `\` 来转义特定的字符。在值字符串的行尾使用 `\`，让该值跨行。也可以识别转义序列 `\n` / `\r` / `\b` / `\t`。

上文中所有运用于**__值__**的的扩展和转义规则都适用于 `.include` 指令的路径中。

== OpenSSL 库配置

通过主 OpenSSL 配置文件，或者一个替换的配置文件，应用可以自动配置 OpenSSL 的特定部分。`openssl` 工具具有这样的功能：任何子命令都会使用主 OpenSSL 配置文件，除非子命令中通过选项指定了一个替换配置文件。

要启用库配置，默认段需要包含一个正确的行，用来指向主配置段。在 `openssl` 工具中，默认的键名为 `openssl_conf`。其他应用可以使用其它的键名，比如 `myapplication_conf`。所有库配置行均出现在配置文件头部的默认段中。

配置段应该有一系列包含特定模块配置信息的键值对。**__键__**表示__配置模块__的名称。而**__值_**的含义则是模块特定的：举例来说，它可以表示一个在下方定义的、包含了配置模块特定信息的配置段：

[source, openssl_conf]
----
# 这段配置必须出现在默认段中
openssl_conf = openssl_init

[openssl_init]

oid_section = new_oids
engines = engine_section

[new_oids]

... 新的 oid ...

[engine_section]

... 引擎相关 ...
----

每个配置模块的特性在下方描述。

=== ASN1 对象配置模块

该模块具有名称 `oid_section`。该变量的值指向一个包含 OID 键值对的段：键名为 OID 长名或短名，值为数值格式的 OID。虽然有些 `openssl` 工具的子命令已有它们自己的 ASN1 OBJECT 段，但并非每个都有。使用了 ASN1 OBJECT 配置模块后，所有的 `openssl` 工具的子命令和合规的应用都可以看见这些新的ui想。举例：

[source, openssl_conf]
----
[new_oids]

some_new_oid = 1.2.3.4
seome_other_oid = 1.2.3.5
----

也可以将值设置为长名称后跟随一个逗号，和一个数字形式的 OID。例如：

[source, openssl_conf]
----
shortName = some object long name, 1.2.3.4
----

=== 引擎配置模块

=== EVP 配置模块

=== SSL 配置模块

== 注释

== 案例

== 环境变量

== BUG

== 参见

== 版权

参见 link:https://www.openssl.org/docs/man1.1.1/man5/config.html[] COPYRIGHT 节
