= OpenSSL 生成证书的流程

该笔记记录了利用 OpenSSL 工具集生成自签名证书、证书链的过程

笔记并非使用了最简单的方式生成需要的结果，相反，使用了比较复杂的方式生成证书，主要是方便理解证书生成的过程。

== 术语简介 & 原理简介

=== RSA 算法

RSA 是一种加密 & 解密算法。

RSA 有两组__平行__的概念，这里请注意区分：

* 从 RSA 生成密钥对的概念上来说
** RSA 私钥：RSA 算法首先生成的密钥，一般来说由生成的人自己持有，**不公开**
** RSA 公钥：用 RSA 私钥**简单**推导后生成的密钥，该密钥可以**公开**发送给外部。

RSA 私钥能**简单**的推导出 RSA 公钥，但 RSA 公钥想要推导出 RSA 私钥**非常复杂**（几乎不能完成）。

* 从 RSA 密钥使用的方法上来说
** RSA 加密密钥：用于将明文加密为密文的密钥
** RSA 解密密钥：用于将密文解密为明文的密钥

常见的加密/解密算法会使用相同的密钥作为加密/解密密钥，但是， +
RSA 的算法特殊的地方就在于：

* 从 加密/解密密钥的角度来说
** RSA 的 加密密钥 和 解密密钥 并不相同
** RSA 的 加密密钥 和 解密密钥 一一对应（成对出现）
** 也就是说由 加密密钥 加密的数据，**仅能**由对应的 解密密钥 解密。
* 从 公钥/私钥的角度来说
** 公钥 和 私钥 都可以作为 加密密钥 和 解密密钥
** 一对公钥/私钥**互为**加解密密钥
** 也就是说，用公钥加密的数据**仅能**由**对应**的私钥解密，而用私钥加密的数据**仅能**由**对应**的公钥解密。

于是，这样来说，RSA 算法有两种用途：

1. 信息加密 +
事先获得接收方的公钥，用公钥加密明文数据，此时仅有持有私钥的人才能将密文数据解密为明文。

2. 信息签名（证明发送身份） +
事先获得发送方的公钥，要求信息发送方加密一段明文已知的信息，若信息接收方能用发送方的公钥解开，并获得正确的明文，则证明信息的确为发送方发送的。

=== 其他术语的简单说明

HTTPS::
超文本传输安全协议，一种使用了 TLS 的传输协议，网址中以 `https://` 开头的网站一般可以认为启用的 HTTPS。 +
这写网站通过 TLS 和相关的协议向浏览器证明自己的身份。

TLS::
传输层安全协议，一种用于网络数据传输中保证数据安全（不泄密、不被篡改）的协议。其底层算法包含了 RSA 算法。

TLS 证书::
在 TLS 中用于证明服务器身份的数据，这些数据一般以文件的形式存放在服务器上，在客户端访问服务器的时候，由服务器发送给客户端，客户端会通过一些方法验证该证书的有效性，从而验证服务器的有效性。

X509::
一种证书的格式的协议，该协议指定了证书该包含什么内容。

X509 V3::
X509 证书的扩展，也就是向 X509 证书中追加一些数据，提供一些额外的信息。

CA::
证书的发放机构/发放者，一般来说，CA 也会管理所发放证书的有效性。

PKI::
公开密钥基础建设，围绕证书的产生、使用、销毁的软件、硬件、人员、策略等的基础构架。

DER::
一种编码，指出证书如何用二进制方式表示（在硬盘上存储，或是在网络中传输）。

PEM::
用 base64 编码的 DER 编码的证书。

OpenSSL::
一套开源软件，可以用于生成、管理、验证、销毁证书。

== 用 OpenSSL 生成证书

[WARNING]
====
除了配置文件为明文文本文件意外，其余文件均为 PEM 编码的文件。
====

=== 生成自签名根证书

. 生成根 CA 所需要的密钥
+
[source, sh]
----
// 使用 genrsa 伪命令生成了 4096 位的 RSA 私钥
openssl genrsa -out my_rootCA.prikey 4096
----

. 【可选】检查私钥
+
[source, sh]
----
// 以可读文本的形式输出当前私钥的信息
openssl rsa -in my_rootCA.prikey -noout -text
----

. 书写证书请求的配置文件
+
[source, openssl.cnf]
.my_rootCA.cnf
----
# req 伪命令会读取的配置段
[req]
prompt = no                     # 禁用交互式输入，仅使用配置文件中的数据生成证书请求
distinguished_name = rootCA_dn  # 可辨识名的段名称，该段的内容用于确定证书的主体
req_extensions = v3_rootCA      # 扩展的段名称，该段用于为证书请求追加更多信息

# 证书主体的可辨识名，用于确定证书主体的唯一性
# 如同地址一样，写的越细致，发生同名碰撞的可能性就越低
[rootCA_dn]
countryName = CN                            # 两字母表示的国家名
stateOrProvinceName = Beijing               # 省名或州名
localityName = Beijing                      # 地区名（城市名）
organizationName = myself                   # 组织名（公司名）
organizationalUnitName = my root CA unit    # 组织单元名（部门名）
commonName = my root CA                     # 常见名

# 根证书扩展
[v3_rootCA]
basicConstraints = critical, CA:TRUE        # 基本约束，关键性约束，将证书设置为 CA
----

. 生成证书请求
+
[source, sh]
----
// 用 req 伪命令生成证书请求
openssl req -config my_rootCA.cnf -new -key my_rootCA.prikey -out my_rootCA.csr
----

. 【可选】检查证书请求
+
[source, sh]
----
// 虽然检查证书请求理论上不需要配置文件
// 但 OpenSSL 工具集似乎需要一个可以正常读取的配置文件才能运行该命令
openssl req -config my_rootCA.cnf -in my_rootCA.prikey -noout -text
----

. 书写证书签名配置文件 +
与证书请求的配置文件类似，自签名证书的配置文件仅需在证书请求配置文件上稍加修改即可
+
.rootCA.cnf
[source, openssl.cnf]
----
...

[req]
...
x509_extensions = v3_rootCA # 指定证书要读取的扩展段
----

. 生成自签名证书
+
[source, sh]
----
// 用 req 伪命令生成了一个有效期 365 天的自签名 CA 证书
openssl req -config my_rootCA.cnf -x509 -days 365 -in my_rootCA.csr -key my_rootCA.prikey -out my_rootCA.crt
----

. 【可选】检查证书
+
[source, sh]
----
openssl x509 -in my_rootCA.crt -noout -text
----
