= genrsa
:genrsa_man1: link:https://www.openssl.org/docs/man1.1.1/man1/genrsa.html[]

== 名称

openssl-genrsa genrsa - 生成 RSA 私钥

== 描述

`genrsa` 命令生成一个 RSA 私钥

== 选项

-help::
打印使用信息

-out filename::
输出密钥至指定的文件。若不指定该选线，则使用标准输出

-passout arg::
输出文件附带密码的来源。关于 **arg** 选项的更多信息，参阅 link:https://www.openssl.org/docs/man1.1.1/man1/openssl.html[openssl(1)] 的 **PASS PHRASE ARGUMENTS** 节。

-aes128, -aes192, -aes256, -aria128, -aria192, -aria256, -camellia128, -camellia192, -camellia256, -des, -des3, -idea::
这些命令在输出前用给定的方法加密私钥。若未指定任何选线，则不对密钥进行加密。若使用加密，且不指定 `-passout` 参数，则提示输入密码。

-F4 | -3::
要使用的公开指数，在 65537 或者 3 中选择一个。默认为 65537。

-rand file...::
指定单个或多个文件，包含随机数据，作为随机数生成器的种子。指定多个文件时，文件名之间用操作系统特定的分隔符加以区分。Windows 上用分号 `;`，OpenVMS 上用逗号 `,`，其它系统用 `:`。

[-writerand file]::
将随机信息输出至指定的文件中。可在 `-rand` 参数后使用。

-engine id::
指定一个（以唯一的 `id` 字符串确定的）引擎，让 `genrsa` 尝试获得指定引擎的可用参考，若需要也会初始化它。该引擎会设置为所有可用算法的默认引擎。

-primes num::
指定生成 RSA 密钥所使用的素数的数量。**num** 参数必须为正整数，且比 1 大，比 16 小。若 **num** 大于 2，则生成的密钥被称为 “多素数”（multi-prim） RSA 密钥，其在 RFC 8017 中定义。

numbits::
以位（bit）计的生成的四幺的长度。该选项必须位最后的选项。默认值为 2048，不允许该值小于 512。

== 备注

RSA 私钥生成过程基于生成两个或更多个素数的过程。当生成一个私钥时，会输出多个符号来指示当前的生成进度。一个点号 `.` 表示一个通过了初始素数筛测试的数，加号 `+` 表示一个通过了单轮米勒-拉宾素性检验（Miller-Rabin Primality test）的数，星号 `*` 表示当前当前素数由于一些测试失败，启动了再次生成过。换行表示数字通过了全部素数测试（实际的数字取决于密钥的长度）。

由于密钥生成是一个随机过程，所以生成一个密钥的时间会受到多种因素的影响。通常来说，素数越多，生成一个密钥的时间就越短。

== 参见

参见 {genrsa_man1}

== 版权

参见 {genrsa_man1}
