= req

== 名称

openssl-req, req - PKCS#10 认证请求以及认证生成工具

== 描述

`req` 命令主要用于创建和处理 PKCS#10 格式额认证请求。它可以额外地创建自签名认证，比如创建用于根 CA 的自签名证书。

== 选项
//
// -help::
//
// -inform DER|PEM::
//
// -outform DER|PEM::
//
// -in filename::
//
// -sigopt nm:v::
//
// -passin arg::
//
// -out filename::
//
// -passout arg::
//
// -text::
//
// -subject::
//
// -pubkey::
//
// -noout::
//
// -modulus::
//
// -verify::
//
// -new::
//
// -rand file...::
//
// [-writerand file]::
//
// -newkey arg::
//
// -pkeyopt opt:value::
//
// -key filname::
//
// -keyform PEM|DER::
//
// -keyout filename::
//
// -nodes::
//
// -digest::
//
// -config filename::
//
// -subj arg::
//
// -multivalue-rdn::
//
// -x509::
//
// -days n::
//
// -set-serial n::
//
// -addext ext::
//
// -extensions section::
//
// -reqexts section::
//
// -precert::
//
// -utf8::
//
// -nameopt option::
//
// -reqopt::
//
// -newhdr::
//
// -batch::
//
// -verbose::
//
// -engine id::
//
// -keygen_engine id::

略

== 配置文件选项

配置选项通过配置文件的 **req** 节指定。若在全部的配置文件中，特定节（比如 `req`）中不包含特定的值，则会搜索初始的未命名节或者 **default** 节。

可用的选项在下方说明。

input_password output_password::
输入私钥文件的密码（若存在），以及输出密钥文件的密码（若要创建）。命令行选项 `passin` `passout` 覆盖配置文件的值。

default_bits::
指定密钥的默认位（bit）长度。 +
该选项与 `-new` 选项连用，来生成一个新的密钥。可以在 `-newkey` 选项明确指定密钥的长度来覆盖该选项。最小可用值位 512 bits。若不指定则使用 2048 bits。

default_keyfile::
写入时，默认的私钥文件名。若不指定则写入标准输出。它可以由 `-keyout` 选项覆盖。

oid_file::
指定一个文件，包含额外的**对象标识符**（OBJECT IDENTIFIERS）。文件中的每行应该包含数字形式的对象标识符，一个白空格，接着是短名，一个白空格，最后是长名。

oid_section::
在配置文件中指定一个额外的节，该节用于包含额外的对象标识符。每行应该包含对象标识符的短名，后随一个等号 `=`，以及它的数字形式。使用该选项时，长名和短名是等价的。

RANDFILE::
在启动时，指定的文件会载入随机数生成器，在退出时，将向其中写入 256 字节的数据。它用于私钥的生成。

encrypt_key::
该值设置为 `no` 时，生成的私钥**不会**被加密。它等价于 `-nodes` 命令行参数。出于兼容性考虑，`encrypt_rsa_key` 为等价选项。

default_md::
该选项指定了要使用的摘要算法。任何被 OpenSSL **dgst** 命令接受的摘要算法都可以使用。该选项可以被命令行覆盖。特定的签名算法（比如 Ed25519 和 Ed448）将忽略任何已经设置的摘要算法。

string_mask::
该选项会为特定的字段屏蔽特定的字符串类型。大多数用户无需修改该选项。 +
（略）

req_extensions::
指定了配置文件中的一个节，该节包含了要加入认证请求的扩展列表。可以用命令行参数 `-reqexts` 进行切换。参见
link:https://www.openssl.org/docs/man1.1.1/man5/x509v3_config.html[x509_v3_config(5)] 手册了解扩展节的格式详情。

x509_extensions::
指定了配置文件中的一个节，该节包含了使用 `-x509` 命令行参数时，要加入生成出的证书的扩展列表。可以通过 `-extensions` 命令行切换。

prompt::
若设置为 `no`，则关闭认证字段的提示，而直接使用配置文件的值。它同样会修改 **distinguished_name** 节和 **attributes** 节所期望的格式。

utf8::
若设置为 `yes`，则字段的值将作为 UTF8 字符串解码，默用 ASCII 方式解码。这表示字段值，无论来自终端或者来自配置文件，必须是有效的 UTF8 字符串。

attributes::
指定一个节，该节包含了任何被要求的属性：其格式与 **distinguished_name** 相同。典型情况会包含 challengePassword 或者 unstructuredName 类型。它们当前被 OpenSSL 的签名请求工具忽略，但某些 CA 可能会要求提供。

distinguished_name::
指定一个段，包含了生成认证或认真请求时，要提示的识别名字段。格式在下节说明。

== 识别名和属性段格式

识别名和属性段有两种独立的格式。若 **prompt** 选项设置为 `no` 时，该段仅由字段和值组成：举例来说，

[source, text]
----
CN=My Name
OU=My Organization
emailAddress=someone@somewhere.org
----

它允许外部程序（比如 GUI）生成一个具有全部字段和值的模板文件，然后将这个文件传递至 `req` 命令。这些配置文件的案例可参阅**案例**节。 +
若 **prompt** 选项未出现或者设设置为 `no`，那么该文件包含字段提示信息。它由下面的形式组成：

[source, text]
----
fieldName="prompt"
fieldName_default="default field value"
fieldName_min= 2
fieldName_max= 4
----

“fieldName” 为要使用的字段名，举例来说 commonName（或者 CN）。字符串 “prompt” 用于请求用户输入相关值。若用户未输入任何值，则使用默认值，若依旧未设定默认值，则该字段被忽略。即使设置了默认值，用户也可以输入一个点号 `.` 来忽略该字段。 +
输入的字符的个数必须介于 fieldName_min 和 fieldName_max 之间：可能还要符合其他的要求（比如 countryName 必须是两字符长，且必须是 PrintableString）。 +
一些字段（比如 organizationName）可以在 DN 中多次使用。这会带来一些问题，因为配置文件不会二次辨识相同的名称。要避免这个文件，若 fieldName 包含了一些字符，后跟随一个点号 `.`，则点号和其前面的字符会被忽略。举例来说，第二个 organizationName 可以被称为 `1.organizationName`。 +
实际允许的字段名未任何对象标识符的长名或短名。通常它们是预先编译入 OpenSSL 的，包含了常用的值，比如 `commonName`，`countryName`，`localityName`，`organizationName`，`organizationalUnitName`，`stateOrProvinceName`。额外也会包含 `emailAddress`，`name`，`surname`，`givenName`，`initials`，`dnQualifier`。 +
额外的对象标识符可以用配置文件中的 **oid_file** 和 **oid_section** 选项定义。额外的字段均被视作 DirectoryString。

== 案例

检查并验证证书请求：

[source, bash]
----
openssl req -in req.pem -text -verify -noout
----

创建一个私钥，并从其中生成一个证书请求：

[source, bash]
----
openssl genrsa -out key.pem 2048
openssl req -new -key key.pem -out req.pem
----

相同结果，仅用 `req`：

[source, bash]
----
openssl req -newkey rsa:2048 -keyout key.pem -out req.pem
----

生成一个自签名根证书：

[source, bash]
----
openssl req -x509 -newkey rsa:2048 -keyout key.pem -out req.pem
----

通过 **oid_file** 选项指向的文件：

[source, text]
----
1.2.3.4        shortName       A longer Name
1.2.3.6        otherName       Other longer Name
----

通过 **oid_section** 指向的段，其中使用了变量扩展：

[source, text]
----
testoid1=1.2.3.5
testoid2=${testoid1}.6
----

用于提示字段值的配置文件：

[source, text]
----
[ req ]
default_bits           = 2048
default_keyfile        = privkey.pem
distinguished_name     = req_distinguished_name
attributes             = req_attributes
req_extensions         = v3_ca

dirstring_type = nobmp

[ req_distinguished_name ]
countryName                    = Country Name (2 letter code)
countryName_default            = AU
countryName_min                = 2
countryName_max                = 2

localityName                   = Locality Name (eg, city)

organizationalUnitName         = Organizational Unit Name (eg, section)

commonName                     = Common Name (eg, YOUR name)
commonName_max                 = 64

emailAddress                   = Email Address
emailAddress_max               = 40

[ req_attributes ]
challengePassword              = A challenge password
challengePassword_min          = 4
challengePassword_max          = 20

[ v3_ca ]

subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid:always,issuer:always
basicConstraints = critical, CA:true
----

包含全体字段值的配置文件：

[source, text]
----
RANDFILE               = $ENV::HOME/.rnd

[ req ]
default_bits           = 2048
default_keyfile        = keyfile.pem
distinguished_name     = req_distinguished_name
attributes             = req_attributes
prompt                 = no
output_password        = mypass

[ req_distinguished_name ]
C                      = GB
ST                     = Test State or Province
L                      = Test Locality
O                      = Organization Name
OU                     = Organizational Unit Name
CN                     = Common Name
emailAddress           = test@email.address

[ req_attributes ]
challengePassword              = A challenge password
----

用命令行给出最常用的属性（主要属性与扩展属性）：

[source, bash]
----
openssl req -new -subj "/C=GB/CN=foo" \
                 -addext "subjectAltName = DNS:foo.co.uk" \
                 -addext "certificatePolicies = 1.2.3.4" \
                 -newkey rsa:2048 -keyout key.pem -out req.pem
----

== 备注

== 诊断

== BUG

== 参见

== 版权
