= x509

== 名称

openssl-x509, x509 - 证书显示和签发工具

== 描述

`x509` 命令是一个多功能证书工具。它可以被用于显示证书信息，将证书转换为多种形式，像 “迷你 CA” 一样为证书请求签名，或者编辑证书可信（trust）设置。 +
由于有很多选项，它们将分为多个节。

== 选项

=== 输入，输出，以及通用选项

-help::
打印使用信息。

-inform DER|PEM::
通常情况下，该命令期望输入的格式为 X509 证书，可以通过该参数指定输入的格式。一般可以与 `-req` 等参数连用。

-outform DER|PEM::
指定输出格式，该选项具有与 `-inform` 选项相同的含义和默认值。

-in filename::
指定读入证书的文件名，若不指定则使用标准输入。

-out filename::
指定要写入的输出文件的文件名，默认输出至标准输出。

-__digest__::
要使用的摘要算法。该选项影响任何使用信息摘要的签名或者显示选项，比如 `-fingerprint`、`-signkey`、`-CA` 选项。任何被 OpenSSL **dgst** 命令支持的摘要算法均可被使用。若不指定，则在指定 `-fingerprint` 时，使用 SHA1 算法，其它签名算法使用其默认的摘要算法，主要是 SHA25。

-rand file...::
指定单个或多个文件，包含随机数据，作为随机数生成器的种子。指定多个文件时，文件名之间用操作系统特定的分隔符加以区分。Windows 上用分号 `;`，OpenVMS 上用逗号 `,`，其它系统用 `:`。

[-writerand file]::
将随机信息输出至指定的文件中。可在 `-rand` 参数后使用。

-engine id::
指定一个（以唯一的 `id` 字符串确定的）引擎，让 `x509` 尝试获得指定引擎的可用参考，若需要也会初始化它。该引擎会设置为所有可用算法的默认引擎。

-preserve_datas::
当签发一个证书时，保留 “notBefore” 以及 “notAfter” 数据，而不将其修改为当前的时间和有效期。不可以与 `-days` 选项连用。

=== 显示选项

[NOTE]
====
`-alias` 和 `-purpose` 选项同样为显示选项，但它们在 **信任设置** 节描述。
====

-text::
以文本形式打印证书。输出以下详情：公钥、签名算法、签发者和主体名、序列号、任何出现的扩展属性、以及可信设置。

-ext extension::
以文本的形式打印证书扩展。扩展用逗号分隔的字符串指定，比如“subjectAltName,subjectKeyIdentifier”。参见文档 link:https://www.openssl.org/docs/man1.1.1/man5/x509v3_config.html[x509v3_config(5)] 了解扩展名。

-certopt option::
在使用 `-text` 时，自定义输出格式。参数可以是单个选项，或者用逗号分隔的多个选项。也可以多次使用 **-certopt** 来设置多个选项。参见 **文本选项** 节了解更多信息。

-noout::
阻止输出编码过后的证书。

-pubkey::
输出 PEM 格式的证书的 SubjectPublicKeyInfo 块。

-modulues::
该选项输出证书中包含的公钥的模数的值。

-serial::
输出证书序列号。

-subject_hash::
输出证书主体名的“散列值”。可被 OpenSSL 用于构建一个序列，允许一个目录中的证书通过主体名来查找。

-issuer_hash::
输出证书签发者的“散列值”。

-ocspid::
输出主体名和公钥的在线证书状态协议（OCSP）散列值。

-hash::
出于向前兼容性的缘由，作为 `-subject_hash` 参数的同义词。

-subject_hash_old::
使用较旧的（OpenSSL 1.0.0 之前使用的）算法输出证书主体名的“散列值”。

-issuer_hash_old::
使用较旧的（OpenSSL 1.0.0 之前使用的）算法输出证书签发者名的“散列值”。

-subject::
输出主体名。

-issuer::
输出签发者名。

-nameopt option::
决定了主体名和签发者名如何被显示。参数可以是单个选项，或者用逗号分隔的多个选项。也可以多次使用 **-nameopt** 来设置多个选项。参见 **文本选项** 节了解更多信息。

-email::
若有，则输出电子邮件地址。

-oscp_uri::
若有，则输出在线证书状态协议响应端（OCSP responder）的地址。

-startdate::
打印证书的起始日期，也就是 notBefore 日期。

-enddate::
打印证书的过期日期，也就是 notAfter 日期。

-dates::
打印证书的起止日期。

-checkend arg::
检查一个证书是否在下 `arg` 秒后失效，若会失效则返回非零值，否则返回零。

-fingerprint::
计算并输出 DER 编码的整个证书的摘要（参见 digest 选项）。它通常被称为“指纹”。由于信息摘要的特性，一个证书的指纹是唯一的，两个具有相同指纹的证书可以被认为是相同的。

-C::
以 C 源码文件的格式输出证书。

=== 可信（trust）设置

一个**可信证书**（**trusted certificate**）是附加了额外信息的普通证书，附加的信息包含证书允许和禁止的使用范围，以及一个“别名（alias）”。 +
通常情况下，当一个证书被验证时，（信任链上）至少有一个证书是“可信的”。默认情况下，可信证书必须在本地存储，且必须为根 CA：此时任何该 CA 下的证书链可以用作任何目的。 +
可信设置当前仅用于根 CA。它们用于更精细地控制根 CA 的用途。举例来说，CA 可以用于 SSL 客户端而非 SSL 服务器上。 +
参见 **verify** 工具的描述了解可信设置的含义的更多信息。 +
未来版本的 OpenSSL 可以识别任何证书上的可信设置：并非仅有根 CA。

=== 签发选项

=== 命名选项

=== 文本选项

== 案例

== 备注

== 认证扩展

== BUGS

== 参见

== 历史

== 版权
